### ISSUE TITLE
Nuget package for Microsoft.Azure.IoT.Gateway 

### ISSUE THREAD

**Issue by tedvanderveen** [Azure/iot-edge#10]
When using .Net bindings and create a new module using .Net, it would be great to have a Nuget package available that adds the Microsoft.Azure.IoT.Gateway assemblies.

**Comment by aribeironovaes** [comment]
Thanks for the feedback Ted!
It is on our backlog to add a Nuget package.
Thanks,
Angelo Ribeiro. 

Get Outlook

		_____________________________

**Comment by aribeironovaes** [comment]
Hi Ted, 

Since it's on our backlog, I will close this Issue. 
Let us know if you have more feature request/suggestions. 

Angelo Ribeiro.

**Comment by tedvanderveen** [comment]
@aribeironovaes I'm not sure why you closed the issues, as the issue is not resolved. If it is on the backlog, the best practice I think is to apply milestone/assignee and leave the issue open so anyone can track progress?

**Comment by aribeironovaes** [comment]
Thanks for the Feedback Ted.
We use issue to track issues and not feature request/milestone tracking. I will talk with the team and check if they want to use issues to get feedback on feature request, but it ia not our practice to keep issues opened for tracking features/progress of product.
Thanks,
Angelo Ribeiro

Get Outlook

		_____________________________

**Comment by chipalost** [comment]
Hi Ted, send me an email at cstreet@microsoft.com and we can talk about the experience you'd like to see from such a package.

**Comment by tedvanderveen** [comment]
Hi @chipalost, at the moment if you want to implement the base classes and interfaces defined in the Microsoft.Azure.IoT.Gateway assembly, you have to add a reference to that project source code from your own code or copy a built DLL into your own project. This can be done more efficient just by adding a (pre-release) Nuget package for Microsoft.Azure.IoT.Gateway when it comes available.

**Comment by barnstee** [comment]
https://github.com/Azure/azure-iot-gateway-sdk/pull/103

**Comment by damonbarry** [comment]
Packages are available; see this blog post: https://azure.microsoft.com/en-us/blog/azure-iot-edge-packages/.
