### ISSUE TITLE
Node.js sample error on Raspberry Pi

### ISSUE THREAD

**Issue by iizotov** [Azure/iot-edge#226]
Hi, after all compiling the SDK with node.js support I am having issues running nodejs_simple_sample.

```
pi@raspberrypi:~/azure-iot-gateway-sdk/build/samples/nodejs_simple_sample $ pwd
/home/pi/azure-iot-gateway-sdk/build/samples/nodejs_simple_sample
pi@raspberrypi:~/azure-iot-gateway-sdk/build/samples/nodejs_simple_sample $ sudo ./nodejs_simple_sample ../../../samples/nodejs_simple_sample/src/gateway_sample_lin.json
Gateway is running. Press return to quit.
printer.receive - 0, 12
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
```

Once or twice it launched successfully and I saw data hitting the IoT Hub. Increased swap, no effect.
System: raspberry pi 3, 2016-11-25-raspbian-jessie
Node.js version 6.10.2, compiled from source using the ./tools/build_nodejs.sh script

```
root@raspberrypi:/home/pi/azure-iot-gateway-sdk/build/samples/nodejs_simple_sample# uname -a
Linux raspberrypi 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux
```
Any ideas?

Thanks!

**Comment by avranju** [comment]
I see that you're running on a Raspberry Pi Yes, we have run into an issue where using the Node.js SDK for Azure IoT Hub fails when run via the Gateway SDK on a Raspberry Pi. The `iothub_writer.js` module uses the Azure IoT Hub Node.js SDK to write to the hub. Till this issue is fixed, as a workaround, you might want to remove the `iothub_writer` module written in JS and use the [native IoT Hub module](https://github.com/Azure/azure-iot-gateway-sdk/tree/master/modules/iothub) to communicate with the hub. This is an issue only on the Raspberry Pi.

**Comment by iizotov** [comment]
Thanks, make sense.

Could you help me structure my json config properly for this demo? Do I need both the mapper and the IoTHub modules or is there a way to output data directly to the IoTHub sink bypassing the mapper straight out of node.js simulated devices? How do I add a mac address to a simulated device?

Thanks!
```
{
  "name": "IoTHub",
  "loader": {
    "name" : "native",
    "entrypoint" : {
      "module.path": "build/modules/iothub/libiothub.so"
    }
  },
  "args": {
    "IoTHubName": "<<Azure IoT Hub Name>>",
    "IoTHubSuffix": "<<Azure IoT Hub Suffix>>",
    "Transport" : "amqp"
  }
}
```
```
{
  "name": "mapping",
  "loader": {
    "name" : "native",
    "entrypoint" : {
      "module.path": "build/modules/identitymap/libidentity_map.so"
    }
  },
  "args": [
    {
      "macAddress": "<<AA:BB:CC:DD:EE:FF>>",
      "deviceId": "<<Azure IoT Hub Device ID>>",
      "deviceKey": "<<Azure IoT Hub Device Key>>"
    }
  ]
}
```

**Comment by iizotov** [comment]
Figured it out, will submit a pull request. It required changes to the device generator js code.

P.S.: tries flipping iothub_writer.js in amqp, http and amqpWs - amqp seems more stable (will run 1 time out of 5), http crashes all the time (same error as mqtt), amqpWs generates segfault.

**Comment by damonbarry** [comment]
We aren't going to take any action right now to fix this. There are known issues when using the iothub_writer.js Node.js module on Raspberry Pi. The workaround is to use the default (native) iothub module instead.
