### ISSUE TITLE
IoT Hub C module does not receive C2D messages if no D2C messages are sent

### ISSUE THREAD

**Issue by avranju** [Azure/iot-edge#241]
The C IoT Hub module as it is written will receive C2D messages only if at least one D2C message is sent first. This doesn't seem right. It's conceivable that there may be gateways where IoT Hub is only being used for commanding purposes and not for telemetry. In this case the C2D messages will not get delivered at all.

**Comment by darobs** [comment]
#321  has been merged.

**Comment by damonbarry** [comment]
Available in the 2017-08-21 release.
