### ISSUE TITLE
Content_Type for nodejs sample only accepts uint8Array

### ISSUE THREAD

**Issue by naveen26246** [Azure/iot-edge#243]
Hi, 
I have run the nodejs_simple_sample example provided with the sdk. However, the messages only support uint8array. I am not sure where to define the content_type so that I can use Number instead of uint8array. 

Thanks

**Comment by darobs** [comment]
Hello  @naveen26246, 

This is an interesting question.  The gateway core make no assumption about the data in the message, so we pass the contents of the message as a byte buffer.  This is what we do for all the modules and module bindings.  It's up to the module to transform the content into the appropriate content type.  

I expect you would want to define the content type in a property of the message. This is what I've seen done for other projects, either as an actual "content type" property, or keying off another known property like the characteristic UUID in the BLE module message.
