### ISSUE TITLE
Microsoft.Azure.Devices.Gateway.Native for any Linux?

### ISSUE THREAD

**Issue by yfakariya** [Azure/iot-edge#258]
As far as I know, there are no reason to limit native IoT Edge modules (.so) for Ubuntu 16.04, but `Microsoft.Azure.Devices.Gateway.Native.Ubuntu.x64` currently only supports Ubuntu as its name suggests. I think it is better to support any Linux distros.

So, I have three questions about it:

1. Is there any problem to use above .so in other distros such as debian 8 or centos 7 in x64 architecture?
2. Is there any plan to support other distros? I think it is better to support broader distros unless there are any technical problems. As far as I tried locally, changing folder name in nupkg from `runtimes/ubuntu.16.04-x64` to `runtimes/linux-x64` looks fine.
3. Is there any plant to distribute .so for ARM linux?

Thanks!

**Comment by aribeironovaes** [comment]
Thanks a lot for the feedback @yfakariya . 

I agree with you. Would you do us a favor and open a github issue on this github? 
https://github.com/Azure-Samples/iot-edge-samples

They are the team who built our Nuget Packages and they would like to get this feedback to make these packages better. 

Have you tried running this in another linux distros? I don't see a problem the only limitation I can see is having .NET Core supported on these distros, if you have .NET Core supported (and it's a 64 bit linux) I don't see why it wouldn't work. 

The same for ARM, just that for ARM you would have to use another package and I don't know if they have created these packages, you can also ask on their github. Let me know. 

Thanks, 

Angelo Ribeiro.

**Comment by yfakariya** [comment]
@aribeironovaes Thank you for quick response! I opened there. https://github.com/Azure-Samples/iot-edge-samples/issues/13

**Comment by yfakariya** [comment]
I didn't run .NET Core binding yet, but native modules should work fine for other distros, and the nupkg contains native modules.

As far as I know, debian, ubuntu14.04, open SUSE are also supported (and RHEL and CentOS are supported by RedHat), and .NET Core 2.0 will support arm.
