### ISSUE TITLE
fatal: The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by ajitz** [Azure/iot-edge#261]
Hi,

I am getting repeated error, as below for following command -
git clone --recursive https://github.com/Azure/Azure-iot-gateway-sdk.git
----
--------
Cloning into 'deps/ctest'...
remote: Counting objects: 236, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 236 (delta 7), reused 0 (delta 0), pack-reused 215
Receiving objects: 100% (236/236), 165.28 KiB | 0 bytes/s, done.
Resolving deltas: 100% (112/112), done.
Checking connectivity... done.
Submodule path 'deps/umock-c/deps/ctest': checked out 'f9f9c619b633dea1e033dd3d66e05599980e6c13'
Cloning into 'deps/testrunner'...
remote: Counting objects: 192, done.
remote: Compressing objects: 100% (5/5), done.
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Clone of 'https://github.com/Azure/azure-c-testrunnerswitcher.git' into submodule path 'deps/testrunner' failed
Cloning into 'deps/umqtt'...
remote: Counting objects: 2073, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 2073 (delta 0), reused 0 (delta 0), pack-reused 2071
Receiving objects: 100% (2073/2073), 555.37 KiB | 494.00 KiB/s, done.
Resolving deltas: 100% (1115/1115), done.
Checking connectivity... done.
Submodule path 'deps/umqtt': checked out 'ebb4d5d80f2b6c1749a9e2e553de46914dc82c78'
Submodule 'azure-c-shared-utility' (https://github.com/Azure/azure-c-shared-utility.git) registered for path 'c-utility'
Cloning into 'c-utility'...
remote: Counting objects: 14202, done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 14202 (delta 81), reused 1 (delta 1), pack-reused 14060
Receiving objects: 100% (14202/14202), 8.03 MiB | 831.00 KiB/s, done.
Resolving deltas: 100% (9880/9880), done.
Checking connectivity... done.
Submodule path 'deps/umqtt/c-utility': checked out '3a38c00dd4089fd5d58ee61cff13473993218645'
Submodule 'testtools/ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'testtools/ctest'
Submodule 'testtools/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'testtools/testrunner'
Submodule 'testtools/umock-c' (https://github.com/Azure/umock-c.git) registered for path 'testtools/umock-c'
Cloning into 'testtools/ctest'...
remote: Counting objects: 236, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 236 (delta 7), reused 0 (delta 0), pack-reused 215
Receiving objects: 100% (236/236), 165.28 KiB | 284.00 KiB/s, done.
Resolving deltas: 100% (112/112), done.
Checking connectivity... done.
Submodule path 'deps/umqtt/c-utility/testtools/ctest': checked out 'f9f9c619b633dea1e033dd3d66e05599980e6c13'
Cloning into 'testtools/testrunner'...
fatal: unable to access 'https://github.com/Azure/azure-c-testrunnerswitcher.git/': gnutls_handshake() failed: Error in the pull function.
Clone of 'https://github.com/Azure/azure-c-testrunnerswitcher.git' into submodule path 'testtools/testrunner' failed
Failed to recurse into submodule path 'deps/umqtt/c-utility'
Failed to recurse into submodule path 'deps/iot-sdk-c'
Failed to recurse into submodule path 'deps/umock-c'
Failed to recurse into submodule path 'deps/umqtt'

**Comment by ajitz** [comment]
Hi there,
I am running this for first time and facing this issue repeatedly to configure field iot gateway.

I am running command : git clone --recursive https://github.com/Azure/azure-iot-gateway-sdk.git
which abruptly finish with following outcome at end.  This does not allow full and proper population of tree and does not execute subsequent command - #git checkout develop
Early help in this will be highly appreciated.

.git) registered for path 'deps/testrunner'
Cloning into 'deps/ctest'...
remote: Counting objects: 236, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 236 (delta 7), reused 0 (delta 0), pack-reused 215
Receiving objects: 100% (236/236), 165.28 KiB | 0 bytes/s, done.
Resolving deltas: 100% (112/112), done.
Checking connectivity... done.
Submodule path 'deps/umqtt/c-utility/testtools/umock-c/deps/ctest': checked out 'f9f9c619b633dea1e033dd3d66e05599980e6c13'
Cloning into 'deps/testrunner'...
remote: Counting objects: 192, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 192 (delta 0), reused 0 (delta 0), pack-reused 187
Receiving objects: 100% (192/192), 835.59 KiB | 303.00 KiB/s, done.
Resolving deltas: 100% (92/92), done.
Checking connectivity... done.
Submodule path 'deps/umqtt/c-utility/testtools/umock-c/deps/testrunner': checked out '3143b1d2df56c0ec9ee517b40e2e29571b7669c0'

**Comment by darobs** [comment]
The gateway SDK repo has been renamed to iot-edge, I'm mildly surprised the command worked for you at all.  (I get a `remote: Repository not found.` error)

Please try:

git clone --recursive https://github.com/Azure/iot-edge.git

**Comment by darobs** [comment]
I tried `git clone --recursive https://github.com/Azure/Azure-iot-gateway-sdk.git` again this afternoon, and the command completed successfully.  I think it was a Github glitch you ran into.

Either 
`git clone --recursive https://github.com/Azure/Azure-iot-gateway-sdk.git`
or
`git clone --recursive https://github.com/Azure/iot-edge.git`

should work, as the repos are aliases.  Please let us know if you have any more difficulties.
