### ISSUE TITLE
Not able to run the sample GW module

### ISSUE THREAD

**Issue by girishlc** [Azure/iot-edge#264]
Not able to run the sample,

I checked the gateway_createfromjson.c file the path of the JSON file is correct.

C:\ff\azure-iot-gateway-sdk\build\samples\java_sample>Debug\java_sample.exe ..\..\..\samples\java_sample\src\java_sample_win.json
Error: Time:Mon May 15 08:33:02 2017 File:C:\ff\azure-iot-gateway-sdk\core\src\gateway_createfromjson.c Func:Gateway_CreateFromJson Line:116 Input file [..\..\..\samples\java_sample\src\java_sample_win.json] could not be read.
failed to create the gateway from JSON

**Comment by Gadnief** [comment]
I get the same message with the dotnet_core_module_sample:

`Error: Time:Thu May 18 15:58:51 2017 File:C:\Projects\iot-edge\core\src\gateway_createfromjson.c Func:_Gateway_CreateFromJson Line:116 Input file [dotnet_core_module_sample_win.json] could not be read.`

**Comment by zafields** [comment]
Also, the file path, ` [......\samples\java_sample\src\java_sample_win.json]`, looks suspicious.
Which directory are you running the sample from?

**Comment by girishlc** [comment]
This could have been the issue with the Json file, sorry I could not find the root cause, but you can close this ticket :) :+1: 

Thank you.
