### ISSUE TITLE
Python Binding

### ISSUE THREAD

**Issue by zerox1212** [Azure/iot-edge#27]
Is there a plan to make a Python wrapper for the C implementation like https://github.com/Azure/azure-iot-sdks ?

**Comment by avranju** [comment]
Adding @chipalost for comment.

**Comment by chipalost** [comment]
Is the ask for a Python binding so that people can write modules in Python, similar to the bindings which allow development of node.js, Java, and C# modules?

**Comment by myagley** [comment]
Thanks for the feature request. However, at this time, we are not planning to take on this work. We would be happy to take a pull request. Thanks!
