### ISSUE TITLE
Attempting to build `--config Release` with unit tests fails.

### ISSUE THREAD

**Issue by darobs** [Azure/iot-edge#271]
Tried to run:
```
tools/build.sh --config Release --run-unittests
```

and the build fails on c-shared utilities, sample errors below:

> In function ‘snprintf’,
>     inlined from ‘stringify_bytes.constprop’ at /home/darobs/repos/darobs/azure-iot-gateway-sdk/deps/c-utility/tests/uws_frame_encoder_ut/uws_frame_encoder_ut.c:78:9,
>     inlined from ‘uws_frame_encoder_encodes_a_reserved_control_frame_E’ at /home/darobs/repos/darobs/azure-iot-gateway-sdk/deps/c-utility/tests/uws_frame_encoder_ut/uws_frame_encoder_ut.c:849:5:
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: error: call to __builtin___snprintf_chk will always overflow destination buffer [-Werror]
>    return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
>           ^
> In function ‘snprintf’,
>     inlined from ‘stringify_bytes.constprop’ at /home/darobs/repos/darobs/azure-iot-gateway-sdk/deps/c-utility/tests/uws_frame_encoder_ut/uws_frame_encoder_ut.c:78:9,
>     inlined from ‘uws_frame_encoder_encodes_a_reserved_control_frame_F’ at /home/darobs/repos/darobs/azure-iot-gateway-sdk/deps/c-utility/tests/uws_frame_encoder_ut/uws_frame_encoder_ut.c:878:5:
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: error: call to __builtin___snprintf_chk will always overflow destination buffer [-Werror]
>    return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
>           ^
> cc1: all warnings being treated as errors
> make[2]: *** [tests/uws_frame_encoder_ut/CMakeFiles/uws_frame_encoder_ut_exe.dir/uws_frame_encoder_ut.c.o] Error 1
> make[1]: *** [tests/uws_frame_encoder_ut/CMakeFiles/uws_frame_encoder_ut_exe.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> make: *** [all] Error 2

If you do not attempt to build unit tests, the build completes, so I don't know how much of a problem this is.

**Comment by damonbarry** [comment]
I'm not sure we've ever supported unit tests in retail.

**Comment by myagley** [comment]
Won't fix.
