### ISSUE TITLE
User should be able to tell Loader where to find .NET Core without JSON config

### ISSUE THREAD

**Issue by damonbarry** [Azure/iot-edge#273]
The .NET Core binding looks for libcoreclr.so at a hard-coded location. The path includes not only the base install location (/usr/shared/dotnet/, C:\Program Files\dotnet, or something custom) but also the .NET Core version number "1.1.1". If your .NET Core is installed somewhere other than the hard-coded location, you can override in the JSON configuration by describing the .NET Core loader, e.g.:

```
  "loaders": [
    {
      "type": "dotnetcore",
      "name": "dotnetcore",
      "configuration": {
        "binding.coreclrpath": "/usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libcoreclr.so",
        "binding.trustedplatformassemblieslocation": "/usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/"
      }
    }
  ],
```

When I installed .NET Core on Ubuntu 16.04 earlier today (following the instructions [here](https://www.microsoft.com/net/core#linuxubuntu)), it installed 1.1.**2**. So even though I installed to the default location, I had to set `binding.coreclrpath` and `binding.trustedplatformassemblieslocation` to point to my installation.

We don't want to go change the #defines in the code every time the default install version changes. It's good that we have a way to override in JSON, but we shouldn't hard-code the default. Our other bindings don't. Of course, Java and Node bindings both dynamically link their runtimes, so they can use an environment variable (JAVA_HOME and NODE_LIB) at compile time. The .NET Core CLR is dynamically _loaded_ at _runtime_ (e.g. via `dlopen`) so we may have to do something a bit different. But we should be able to get rid of the hard-coded, per-platform defaults.

**Comment by avranju** [comment]
There's some information [here](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/corehost.md#runtime-resolution) on how the .NET host decides which runtime to load.

**Comment by myagley** [comment]
The config file is the supported method to specify the clr path. It would be nice to look in the PATH when the config doesn't specify it. Contributions are welcome.
