### ISSUE TITLE
How to develop iot-edge with node?

### ISSUE THREAD

**Issue by vslepakov** [Azure/iot-edge#274]
Hi,

I was wondering what my options are in terms of implementing iot-edge functionality using nodejs.
I successfully built and ran the nodejs sample on Raspi. 

- So if I would like to add my own modules am I supposed to just apply changes to the configuration? 
- Why is there a nodejs iothub_writer module which uses the device SDK if there is a ready to use iothub native module?
- I know there is an npm package available containing everything but it does not seem to work with ARM (on Raspi)

What is the guidance?

Thanks ins advance
Vitaliy

**Comment by avranju** [comment]
The quickest way to get started building your own modules using Node.js may be to use the [Yeoman](http://yeoman.io/) generator - `az-iot-gw-module`. You'll find setup instructions in the [generator's repo](https://github.com/Azure/generator-az-iot-gw-module#readme). Note that this is currently only supported on x86/x64 hosts on Windows and Linux.

> So if I would like to add my own modules am I supposed to just apply changes to the configuration?

Once you have built and debugged your modules (on your PC) you should be able to transfer your module JS files to your Raspberry Pi and run them there using your Pi build of iot-edge.

> Why is there a nodejs iothub_writer module which uses the device SDK if there is a ready to use iothub native module?

On the Raspberry Pi only the native IoT Hub module works reliably. We noticed that the Node.js IoT Hub SDK when run via iot-edge (which embeds the Node.js runtime in-memory) on the Pi, periodically produces errors that seem to originate in Node.js's SSL stack.

The `iothub_writer` module exists simply as a sample to showcase that it is possible to use the Node.js IoT Hub SDK directly should you choose to do so (at least on x86/x64 hardware).

> I know there is an npm package available containing everything but it does not seem to work with ARM (on Raspi)

Yes, the NPM package currently only supports x86/x64 CPU architectures on Windows and Linux. @shsushi might be able to advise on support for Pi.

**Comment by vslepakov** [comment]
@avranju thank you so much for this information.

when you say: 

> Once you have built and debugged your modules (on your PC) you should be able to transfer your module JS files to your Raspberry Pi and run them there using your Pi build of iot-edge.
> 

do you mean I would need to run ./nodejs_simple_sample with my custom configuration? Or what is the main executable?

Is the following statement correct: all native modules work on x86, x64, ARM etc. if they could be built on the target platform. All other bindings (node, dotnetcore, java, etc.) additionally depend on that technology being supported on that specific platform? 

Thanks and Regards

**Comment by avranju** [comment]
> do you mean I would need to run ./nodejs_simple_sample with my custom configuration? Or what is the main executable?

Yes, `nodejs_simple_sample` would be the executable you run on the Pi. I meant that you'd transfer just the JavaScript files for your module to the Pi, i.e., you'd build and test the module on your development PC first and then transfer the JavaScript files over to the Pi (using SCP for example) and then test it there.

> Is the following statement correct: all native modules work on x86, x64, ARM etc. if they could be built on the target platform. All other bindings (node, dotnetcore, java, etc.) additionally depend on that technology being supported on that specific platform?

Yes, that's a fair statement. With Node.js, .NET and Java you also have the additional benefit of *binary portability* of the module itself (well, with JS it's still the source of course).

**Comment by vslepakov** [comment]
Thanks!
