### ISSUE TITLE
Port build.sh to macOS

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge#276]
Code is in sync with master branch and installs libctest.a to install-deps/libs correctly on Ubuntu systems. But, the sdk fails to build on mac os x. I used os x 10.12.3, but feels the version doesn't matter.  The use of `execute_process()`, which doesn't take into consideration other variables like CMAKE_INSTALL_PREFIX etc is causing problems.

> $:cmake xxxxxxxx$ cmake ..
> -- The C compiler identification is AppleClang 8.1.0.8020041
> -- The CXX compiler identification is AppleClang 8.1.0.8020041
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- CMake Install Prefix is /usr/local
> -- AIG architecture: x86_64
> -- ctest not found...
> -- Building ctest...
> -- The C compiler identification is AppleClang 8.1.0.8020041
> -- The CXX compiler identification is AppleClang 8.1.0.8020041
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/xxxxxxxx/src/try/azure-iot-gateway-sdk/deps/ctest/build
> -- Installing ctest. Please wait...
> CMake Error at gatewayFunctions.cmake:170 (message):
>   Error installing ctest: 2
> Call Stack (most recent call first):
>   dependencies-test.cmake:9 (findAndInstall)
>   CMakeLists.txt:201 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/xxxxxxxx/src/try/azure-iot-gateway-sdk/cmake/CMakeFiles/CMakeOutput.log".
> yyyyyyyy:cmake xxxxxxxx$ 
> yyyyyyyy:cmake xxxxxxxx$ 
> yyyyyyyy:cmake xxxxxxxx$ cat /Users/xxxxxxxx/src/try/azure-iot-gateway-sdk/deps/ctest/build/error.txt 
> CMake Error at cmake_install.cmake:31 (file):
>   file INSTALL cannot copy file
>   "/Users/xxxxxxxx/src/try/azure-iot-gateway-sdk/deps/ctest/build/libctest.a"
>   to "/usr/local/lib/libctest.a".
> 
> 
> make: *** [install] Error 1
> $:cmake xxxxxxxx$ 

The intention of this issue, is not to get production quality sdk binary on mac os x which is not a supported platform for now. The intention is to get the SDK code into XCode/VS editor so that it is easily browseable. A good CMakeLists.txt is needed for cmake-generators([1](https://cmake.org/cmake/help/v3.0/manual/cmake-generators.7.html)) to work.

**Comment by damonbarry** [comment]
macOS actually _is_ officially supported, mostly. :) There are some gateway features we don't officially support yet for macOS, namely .NET Core modules and Node.js modules.

But if you look at the script our CI server uses to build for macOS, `jenkins/osx_c.sh`, you'll notice it doesn't use `build.sh`. It uses CMake directly.

Perhaps we should fix build.sh to support macOS, since people tend to use that script, but until then you can use `jenkins/osx_c.sh` as a pattern for how to build the SDK.

**Comment by kiranpradeep** [comment]
@damonbarry Earlier I was able to use Jenkins/osx_c.sh. Now neither that nor build.sh works. Fails during build/install of iot-sdk-c dependency

```
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/779591ardp/src/try/azure-iot-gateway-sdk/deps/iot-sdk-c/build
-- Installing azure_iot_sdks. Please wait...
CMake Error at gatewayFunctions.cmake:170 (message):
  Error installing azure_iot_sdks: 65
Call Stack (most recent call first):
  modules/dependencies.cmake:39 (findAndInstall)
  modules/CMakeLists.txt:6 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/779591ardp/src/try/azure-iot-gateway-sdk/build/CMakeFiles/CMakeOutput.log".
```

In ./deps/iot-sdk-c/build/error.txt

```
** BUILD FAILED **
The following build commands failed:
        CompileC build/iothub_service_client/azure_iot_sdks.build/Debug/iothub_service_client.build/Objects-normal/x86_64/iothub_devicetwin.o iothub_service_client/src/iothub_devicetwin.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by kiranpradeep** [comment]
@damonbarry It was failing for -Werror flag in iot-sdk-c dependency CMakeLists.txt. I removed the flag and build was successful.

But, still that will fail other users of this SDK.

**Comment by damonbarry** [comment]
I did a fresh clone, set JAVA_HOME, and ran osx_c.sh and the build succeeded.

@kiranpradeep Can you attach deps/iot-sdk-c/build/output.txt?

**Comment by kiranpradeep** [comment]
@damonbarry I too did a fresh clone, ran osx_c.sh/build.sh to get same error. Didn't set JAVA_HOME as I was building enable_java_binding=OFF. Attaching error.txt([1](https://github.com/Azure/iot-edge/files/1124205/error.txt)) and output.txt([2](https://github.com/Azure/iot-edge/files/1124203/output.txt)).

But this is not particular to mac osx and fails on Linux as well for -Werror flag([3](https://github.com/Azure/azure-iot-sdk-c/blob/master/CMakeLists.txt#L41)).

**Comment by damonbarry** [comment]
Sorry, I'm not able to reproduce this.
