### ISSUE TITLE
Issue installing IoT Edge on Raspberry Pi

### ISSUE THREAD

**Issue by FabianKLS** [Azure/iot-edge#277]
Hi, I'm following this [tutorial ](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-iot-edge-physical-device)and run into the error message below when building the IoT Edge GW (running build.sh)
Not sure how to troubleshoot this. Any suggestions?

Scanning dependencies of target parson
[  1%] Building C object core/deps/CMakeFiles/parson.dir/__/__/deps/parson/parson.c.o
[  2%] Linking C static library libparson.a
[  2%] Built target parson
Scanning dependencies of target gateway_static
[  3%] Building C object core/CMakeFiles/gateway_static.dir/adapters/dynamic_library_linux.c.o
[  4%] Building C object core/CMakeFiles/gateway_static.dir/adapters/gb_library_linux.c.o
[  5%] Building C object core/CMakeFiles/gateway_static.dir/src/message.c.o
[  5%] Building C object core/CMakeFiles/gateway_static.dir/src/message_queue.c.o
[  6%] Building C object core/CMakeFiles/gateway_static.dir/src/module_loader.c.o
[  7%] Building C object core/CMakeFiles/gateway_static.dir/src/module_loaders/dynamic_loader.c.o
[  8%] Building C object core/CMakeFiles/gateway_static.dir/__/proxy/message/src/control_message.c.o
[  8%] Building C object core/CMakeFiles/gateway_static.dir/__/proxy/outprocess/src/module_loaders/outprocess_loader.c.o
core/CMakeFiles/gateway_static.dir/build.make:230: recipe for target 'core/CMakeFiles/gateway_static.dir/__/proxy/outprocess/src/module_loaders/outprocess_loader.c.o' failed
CMakeFiles/Makefile2:987: recipe for target 'core/CMakeFiles/gateway_static.dir/all' failed
Makefile:138: recipe for target 'all' failed

**Comment by darobs** [comment]
Hello @FabianKLS  - It looks like we missed a documentation update on the tutorial.  I suspect libuv didn't build properly, and I can see that the tutorial is missing a library required to build libuv - libtool.
This line is from [our devbox setup for Linux](https://github.com/Azure/iot-edge/blob/master/doc/devbox_setup.md):
```
sudo apt-get install curl build-essential libcurl4-openssl-dev git cmake libssl-dev uuid-dev valgrind libglib2.0-dev libtool autoconf
```
Try running that command and attempt a rebuild.  It should work this time.  Please let us know if that works.

**Comment by zafields** [comment]
I would be nice to have more information, but we suspect you will need the prerequisites to install `libuv`. I have made a [pull-request](https://github.com/Microsoft/azure-docs/pull/1825) against the tutorial you referenced.

You will need to run `sudo apt-get install libtool` in order to build the gateway SDK.
You may also need to install python 2.7 if it is not installed on your machine already.

**Comment by FabianKLS** [comment]
Installing the packets suggested by @darobs  did the trick.

**Comment by cedarmill** [comment]
Thank you @darobs ... after a day of failure I found this link. All is good now :-)
