### ISSUE TITLE
Add gateway_config.json Help to NPM Packages

### ISSUE THREAD

**Issue by jonbgallant** [Azure/iot-edge#278]
As an outsider, I would not understand what #2 means below
 
https://www.npmjs.com/package/azure-iot-gateway
 
1.	npm install -g azure-iot-gateway
2.	Create your module pipeline config gateway_config.json
3.	azure-iot-gateway gateway_config.json
•	gateway_config.json should contain the module (native, .net, node, java) configuration.
 
 
Can we provide a link to a sample gateway_config?  Or include on in the npm install?

**Comment by furqanMM** [comment]
Good point, we'll clarify its purpose and include a pointer to the following tutorial which is more descriptive: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-linux-iot-edge-get-started#how-to-run-the-sample
The [Yeoman generator](https://www.npmjs.com/package/generator-az-iot-gw-module) does include a sample gateway_config file.

**Comment by furqanMM** [comment]
Latest NPM package README includes link to tutorial.
