### ISSUE TITLE
build.sh clones libuv for each build

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge#280]
Every run of `build.sh` deletes and clones libuv. Is this intentional ?

**Comment by damonbarry** [comment]
We'd be happy to have something more refined, but the "brute force" approach seemed acceptable as a first step.

**Comment by myagley** [comment]
Contributions welcome. Closing for now.

**Comment by kiranpradeep** [comment]
Can I try a pull request with libuv as a submodule in v1/deps folder? Likes to know the preferred way on this.

**Comment by darobs** [comment]
The cloning and building of libuv was intentional, because libuv is only needed for the out of process modules, and not everyone wants that. It also seems to be the pattern  However, building _every time_ is an annoyance we didn't find a great solution for. 

Yes please, pull requests are welcome.

**Comment by damonbarry** [comment]
I have a pull request nearly ready for this, but I’ve only tested on Mac. I can create the PR so people can look at it, then I can add the Windows/Linux support when I get time (or someone else can add it).
