### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by melzoghbi** [Azure/iot-edge#286]
When i am trying to build the solution on Win10 x64 bit with VS2017, The build failed and i get this error message:
![image](https://cloud.githubusercontent.com/assets/11993393/26526703/fb070dbe-4350-11e7-9ec9-47c0d99d3d56.png)

Any idea how to fix this issue?

Thanks

**Comment by aribeironovaes** [comment]
Hi Mostafa,

From your build looks like libuv is failing to build. Usually this is because you an incompatible version of Python or git.

Can you check if those version match with the recommended on the readme file.

Let us know,

Angelo Ribeiro

**Comment by melzoghbi** [comment]
Hi Angelo,

I checked, those are the versions that i have:

Python 2.7.9
git version 2.1.4

I ran 

> sudo apt-get update

 to make sure i have latest packages. I have reviewed the dev box setup article and i do not set any requirement for git but Python 2.7 which i already have.

Let me know what else could be the problem.

**Comment by melzoghbi** [comment]
I have excellent news, I was able to build the azure_iot_gateway_sdk solution after i digged into the errors and i found out the root cause of it. **The main cause of the problem was libuv did not build due to  VS2010 build does not exist on my machine**! The iot solution was looking into this folder 
"[RepoFolder]\iot-edge\build_libuv\dist\lib" to load libuv.lib which does not exist! 

So here is the steps you need to follow to upgrade libuv solution to use latest VC++ build tools for VS 2017 instead:

1) Open ux.sln from build_libuv ->libuv folder.
2) Once you open up the project, it will ask you to upgrade the solution to use the VS tools you have got on your machine. In my case was VS 2017.

![image](https://cloud.githubusercontent.com/assets/11993393/26594538/07e1b534-4536-11e7-875c-50e030c38a15.png)

3) Right click on the solution and click on retarget solution. select the latest VS build tools version.

4) Build a release build for libuv tool! you should be able to get a successful build!

![image](https://cloud.githubusercontent.com/assets/11993393/26594597/3af5276c-4536-11e7-8ca0-ab1bcb3f2a2a.png)

5) Copy the release build "libuv.lib" is located at the following folder "[RepoFolder]\iot-edge\build_libuv\libuv\Release\lib"

6) Paste the lib into the following folder path "[RepoFolder]\iot-edge\build_libuv\dist\lib"

7) Build the azure iot solution and you should be able to have a successful build with no errors!

Note: The copy and paste step of the release build lib should be taking care of by "**vcubuild.bat**" file which is looking for **VS2015 or earlier version which i don't have**. This file is being called when you build the azure iot solution since the libuv is one of its dependency. I am working with the product team to update the batch file to include vs2017 c++ build tools so you should not have this problem when you are using VS 2017 moving forward.


Enjoy!

**Comment by zafields** [comment]
@melzoghbi Your issue appears to be related to issue #218. The problem you are experiencing is that LibUV has not yet been upgraded to support VS2017. The work has been completed and is awaiting a merge; [tracked here](https://github.com/libuv/libuv/pull/1284).
It looks like your method works, but would not be the preferred way to compile. As soon as LibUV is updated (and preferably versioned), then we can snap to the appropriate commit to fully support VS2017.
If you wish to use the latest SDK, and do not need remote module support, then you can use the `--disable-native-remote-modules` flag with `build.com` to compile your solution

**Comment by melzoghbi** [comment]
Awesome! Looking forward to the update. as far as of now, i was able to build manually from VS 2017. Once this is merged #218, This would not be an issue with VS 2017 C++ build tools. Thanks a lot @zafields & @aribeironovaes.
