### ISSUE TITLE
IOT Edge with dotnet core binding for ARM Ubuntu

### ISSUE THREAD

**Issue by Zuendelmeister** [Azure/iot-edge#290]
Hi again,

I'm facing a new problem. I want to install IOT-Edge on an arm device (for example a Raspberry Pi).
My problem is that I cannot install the dotnet core sdk (with cli), which is needed for installing IOT-Edge with dotnet core binding. The  build_dotnet_core.sh uses cli commands (dotnet restore, dotnet build,...).

Also I tried to run the install script on a VM and edit the build_dotnet_core.sh like this:
![image](https://cloud.githubusercontent.com/assets/14317353/26619490/f9c11694-45de-11e7-857d-9b606505d344.png)

I hoped I could just copy the bindings/dotnetcore folder to my ARM device and everything just works, but it seems like it didn't.
![image](https://cloud.githubusercontent.com/assets/14317353/26619964/13663dc0-45e1-11e7-9865-2aeda4a0e261.png)

Do you have a way of getting a clean installation of IOT-Edge with dotnet core binding on arm?
As always thank you very much.

Best regards,
Zuendelmeister

**Comment by aribeironovaes** [comment]
HI @Zuendelmeister , 

.NEt Core is not officially supported on ARM, so, this repo doesn't yet support ARM. 

If you want to install our stuff in a raspberry pi and run the .NET Core binding you will have to change the scripts and possible CrossCompile (Last Time I checked you don't have SDK for ARM, just the runtime.). 

That said, I would do exactly what you are doing and editing the scripts myself. 

From the error you place the .NET Core Loader is not being compiled. Did you build on the ARM with .NET Core Binding flag enabled? Did that build successfully on ARM?

Let me know, 

Angelo Ribeiro.

**Comment by Zuendelmeister** [comment]
Hi @aribeironovaes ,
after trying and trying i finaly got it to work in my pi. Using the -r flag on a vm realy worked after i started from scratch.

Best regards,
Zuendelmeister

**Comment by faister** [comment]
Hi @Zuendelmeister ,
Just wondering how did it work for you, could you please share the exact thing you did to run the dotnet_core_managed_gateway upon rebuilding your dotnet_core_binding for arm?

I am also trying to install IoT Edge on a Raspberry Pi (I have two versions, one running on Raspbian 8 and another on Ubuntu 16.04 on arm-hf arch). So far I have better luck with Raspbian 8. I am running .NET Core 2.0 runtime on my RPI3 on Raspbian 8. Just to make sure everything works fine, I published a helloworld console app on my Windows machine using the command dotnet publish -r linux-arm, copied the files to my RPi3, ran it using my .NET Core 2.0 runtime and it works.

Just like you, I am able to do a dotnet restore -r linux-arm flag in my build_dotnet_core.cmd. In all the .csproj files I made sure that the target framework is as follows:
    <TargetFramework>netcoreapp2.0</TargetFramework>

I am sure I have all the .NET Core 2.0 DLLs and .so all within my bin\Debug folder. When I run it I get an exception:
pi@raspberryfai:~/iot-edge/samples/dotnet_core_managed_gateway/bin/Debug/netcoreapp2.0$ dotnet dotnet_core_managed_gateway.dll dotnet_core_managed_gateway_lin.json

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'dotnetcore': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Azure.Devices.Gateway.NetCoreInterop.InitializeDelegatesOnNative(IntPtr createAddress, IntPtr receiveAddress, IntPtr destroyAddress, IntPtr startAddress)
   at Microsoft.Azure.Devices.Gateway.NetCoreInterop.InitializeDelegates() in C:\Demos\iot-edge\bindings\dotnetcore\dotnet-core-binding\Microsoft.Azure.Devices.Gateway\NetCoreInterop.cs:line 279
   at Microsoft.Azure.Devices.Gateway.GatewayInterop.CreateFromJson(String file_path) in C:\Demos\iot-edge\bindings\dotnetcore\dotnet-core-binding\Microsoft.Azure.Devices.Gateway\GatewayInterop.cs:line 28
   at dotnet_core_managed_gateway.Program.Main(String[] args) in C:\Demos\iot-edge\samples\dotnet_core_managed_gateway\Program.cs:line 18
Aborted

I even added the loader in my gateway json file:
{
    "loaders": [
        {
            "type": "dotnetcore",
            "name": "dotnetcore",
            "configuration": {
                "binding.path": "/home/pi/iot-edge/samples/dotnet_core_managed_gateway/bin/Debug/netcoreapp2.0/dotnetcore.dll",
                "binding.coreclrpath": "/opt/dotnet-2.0.0/shared/Microsoft.NETCore.App/2.0.0/libcoreclr.so",
                "binding.trustedplatformassemblieslocation": "/opt/dotnet-2.0.0/shared/Microsoft.NETCore.App/2.0.0"
            }
        }
    ],

**Comment by aribeironovaes** [comment]
Hi @faister, 

Did you check if you have all the dependencies copied to folder /home/pi/iot-edge/samples/dotnet_core_managed_gateway/bin/Debug/netcoreapp2.0/? 
Check if you have libaziotsharedutil.so, libnanomsg.so and any other dependency that you may need. Try that and let us know. 

Another thing that can be happening with you is that dotnetcore.dll must be on your working folder. I'm assuming that your working folder is: /home/pi/iot-edge/samples/dotnet_core_managed_gateway/bin/Debug/netcoreapp2.0/ 
Just double check if all the other binaries are on this folder and that when you run "dotnet dotnet_core_managed_gateway.dll dotnet_core_managed_gateway_lin.json" you are loading your dotnet_core_managed_gateway.dll from this folder... 

Let us know how it goes, 

Angelo Ribeiro.

**Comment by Zuendelmeister** [comment]
Hi @faister,
I built everything on an ubuntu vm but changed the build_dotnet_core.sh.
I changed the lines "dotnet restore $project" and "dotnet build $build_config $project" and added the -r flag. 
And with that I could work just fine.

Best regards,
Zuendelmeister

**Comment by myagley** [comment]
Thanks @Zuendelmeister !
