### ISSUE TITLE
Segmentation fault in sample when iothub module uses HTTP

### ISSUE THREAD

**Issue by kevinpei2001** [Azure/iot-edge#291]
Hi, I set up the IoT gateway to my Fedora 24 without issue. However when I run the sample application of Simulated_device_cloud_upload. It got crashed. Although it showed 2 rows of data sent out to the Cloud I didn't see anything on the Cloud side (Didn't see incoming traffic). Anybody could help?

![samplecodeerror](https://cloud.githubusercontent.com/assets/29132822/26703697/d2a0a06e-46df-11e7-855e-c3b546535d4b.png)

**Comment by kevinpei2001** [comment]
Hi, there, I figured out the issue... I should have indicated MQTT protocol instead of HTTP in the JSON file. 
Now I have the data populated to the Azure. I saw the traffic from the IoT Hub Metrics.

However, do you have any ideas how to retrieve the data and show it up? I configured IoT Hub/Event Hub/Service Bus/Streaming Job etc based on the instructions.  I also set up the Input and Output in the Streaming Job. But I didn't see any data coming in...

Thanks..

**Comment by damonbarry** [comment]
> I should have indicated MQTT protocol instead of HTTP in the JSON file

Are you saying that if you change the setting back to `HTTP` in the JSON file, then `./simulated_device_cloud_upload` reliably core dumps? I'm glad you worked around it by specifying `MQTT`, but you ought to be able to specify `HTTP` too, so we'll need to investigate that.

> do you have any ideas how to retrieve the data and show it up?

There are all kinds of things you can do, but they're all outside the scope of the code in this repo. 😏 If you haven't already, take a look [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-operations-monitoring) for one example.

**Comment by kevinpei2001** [comment]
Thank you for your information and help, Damon.

**Comment by damonbarry** [comment]
Please reopen if you can reproduce the core dump in the HTTP case.
