### ISSUE TITLE
simulated_device_cloud_upload_sample can't run.

### ISSUE THREAD

**Issue by misoragod** [Azure/iot-edge#296]
Hi, everyone
I built iot-edge following command and  I'v done it.
 ./build.sh --disable-nodejs-remote-modules --disable-ble-module

I move to build directory and execute following command.  
./samples/simulated_device_cloud_upload/simulated_device_cloud_upload_sample ../samples/simulated_device_cloud_upload/src/simulated_device_cloud_upload_lin.json 

Then an error occurs.
Like this.
./samples/simulated_device_cloud_upload/simulated_device_cloud_upload_sample: error while loading shared libraries: libaziotsharedutil.so: cannot open shared object file: No such file or directory

I could find libaziotsharedutil.so in  iot-edge/install-deps/lib/x86_64-linux-gnu/
I use ubuntu 14.0.4 on x86_64.
What should I do? 
But  I can run it in azure-iot-gateway-sdk.
Sorry for my English.

**Comment by damonbarry** [comment]
Use the `ldd` tool in Linux to see what the dependencies of the application are, and where it expects to find them.

```
ldd samples/simulated_device_cloud_upload/simulated_device_cloud_upload_sample
```

**Comment by misoragod** [comment]
Thanks for your reply.
I  could solve this issue adding "iot-edge/install_deps/lib" to /etc/ld.so.conf.d.

**Comment by damonbarry** [comment]
Great. Closing...let's reopen if we continue to see. The samples *should* work as-is when you compile them (without the need to run `ldd` or similar...).
