### ISSUE TITLE
Naming of properties 'assembly.name" and "entry.type"

### ISSUE THREAD

**Issue by ddobric** [Azure/iot-edge#304]
Wouldn't be better to rename properties 'assembly.name" and "entry.type" to assemblyName and entryType respectively?

  "assembly.name": "xy",
  "entry.type": "xy"

Naming of properties as 'abc.def' is not a best practice and it will make difficulties on most platforms to build tools, which deal with such kind of configuration. Most JSON deserializers will fail or try to remove '.'.

**Comment by aribeironovaes** [comment]
Hi @ddobric , 

Thanks for the feedback.We will consider and let you know. 
Couple of questions: What are the platform build tools are you working on that had problem with this type of name? 
We are using parson (on native side) and we haven't been having problems with that. 
Right now we are being consistent with the rest of the Azure Edge SDK..

Thanks again, 

Angelo Ribeiro.

**Comment by damonbarry** [comment]
We've looked at a few different JSON parsers, and haven't encountered an issue.

If you have specific information about JSON parsers that don't like our dotted JSON value names, please reopen this issue and add more details. Thanks!
