### ISSUE TITLE
When we can expect the AI related stuff integrated in this SDK ?

### ISSUE THREAD

**Issue by ganeshmahajan1985** [Azure/iot-edge#306]
As Described in the Azure IoT Edge page. I would like to know about artificial intelligence integration using Azure IoT edge SDK. 
Can somebody please help ?
https://azure.microsoft.com/en-in/campaigns/iot-edge/

**Comment by chipalost** [comment]
We're busy coding up all the great features unveiled at Build; however we're not ready to release our timeline for when these features will be integrated into the repo. In the mean time, you can sign at the form below and we'll be sure to keep you up to date with all the latest developments. 

https://microsoft.qualtrics.com/jfe/form/SV_0V8Xr8y9c4mHUfb
