### ISSUE TITLE
How to add a node module to .Net Core managed Gateway

### ISSUE THREAD

**Issue by malichishti** [Azure/iot-edge#307]
Hi,

I would like to know how can one add a nodeJs module to a .Net Core Manage Gateway built using https://www.nuget.org/packages/Microsoft.Azure.Devices.Gateway.Module.NetStandard/
Do i need to add nodeJs bindings? If yes is it using npm or nuget?

Also what will be the format of JSON file?

Regards,
Ali

**Comment by aribeironovaes** [comment]
Hi @malichishti, 

So, you have to follow the guideline to add a module (Checking the samples). 
So, go to Node JS Sample: 
https://github.com/Azure/iot-edge/tree/master/samples/nodejs_simple_sample

Make sure you install Node and Everything it needs. 

Than you Can go back to managed gateway sample and add your node module and create the links. 
The Json file would look like this: 
{
    "loaders": [
        {
            "type": "node",
            "name": "node",
            "configuration": {
                "binding.path": "..\\..\\..\\bindings\\nodejs\\Debug\\nodejs_binding.dll"
            }
        }
    ],
    "modules": [
        {
            "name": "node_printer",
            "loader": {
                "name": "node",
                "entrypoint": {
                    "main.path": "../../../samples/nodejs_simple_sample/nodejs_modules/printer.js"
                }
            },
            "args": null
        },
        {
            "name": "node_sensor",
            "loader": {
                "name": "node",
                "entrypoint": {
                    "main.path": "../../../samples/nodejs_simple_sample/nodejs_modules/sensor.js"
                }
            },
            "args": null
        }, 
        {
            "name": "dotnet_sensor_module",
            "loader": {
                "name": "dotnetcore",
                "entrypoint": {
                    "assembly.name": "SensorModule",
                    "entry.type": "SensorModule.DotNetSensorModule"
                }
            },
            "args": "module configuration"
        },
        {
            "name": "dotnet_printer_module",
            "loader": {
                "name": "dotnetcore",
                "entrypoint": {
                    "assembly.name": "PrinterModule",
                    "entry.type": "PrinterModule.DotNetPrinterModule"
                }
            },
            "args": "module configuration"
        }
    ],
    "links": [
        {
            "source": "node_sensor",
            "sink": "node_printer"
        }, 
        {
            "source": "dotnet_sensor_module",
            "sink": "dotnet_printer_module"
        }
    ]
}

Of course, this sample doesn't make sense e2e, you just have a 2 printers 2 sensors... But it is just to give you an idea. 

Let me know if you have problems, 

Cheers, 

Angelo Ribeiro.

**Comment by malichishti** [comment]
Hi Thank you for the instruction; Im currently unable to setup node samples as per the error below:
![image](https://user-images.githubusercontent.com/17155996/27419936-cda3e8c2-5766-11e7-8052-ef3b3366f352.png)

**Comment by malichishti** [comment]
Looks like it needed python 2.7, to solve the above syntax issue.

I'm able to run nodeJs gateway. however when i try to include the nodeJs module into .net core managed gateway, i get following:
![image](https://user-images.githubusercontent.com/17155996/27422626-40779cb2-5772-11e7-9ba6-dd99da9eee84.png)

**Comment by aribeironovaes** [comment]
Hi @malichishti , 

Can you give me details on your environment and, if possible, you json file so I can try to reproduce here? 
are you trying to add samples modules, or modules you created?

Let us know, 

Angelo Ribeiro.

**Comment by aribeironovaes** [comment]
Hi @malichishti, 

I could repro your issue and here is how to fix: 
1-First you have to make sure you build nodejs binding on the same platform as your dotnet core (mine is 64bit, for example). 

2-Once you do that Go to the managed gateway and Publish Debug (So you can have all the libraries on the same folder. 

3-Copy all the dependencies to your publish folder: 
Here is a printscreen of my publish folder for your reference: 
![image](https://user-images.githubusercontent.com/9369967/27461959-242c2bfe-5772-11e7-8ddd-b30a275d52da.png)

4-After that edit your json file. Here is mine: (Keep in mind that I'm using .NET Core 2.0.0-preview1-00211-00, make sure you configure dotnetcore loader according to your version. 
{
    "loaders": [
        {
            "type": "dotnetcore",
            "name": "dotnetcore",
            "configuration": {
                "binding.path": "dotnetcore.dll",
                "binding.coreclrpath": "C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.0-preview1-002111-00\\coreclr.dll",
                "binding.trustedplatformassemblieslocation": "C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App\\2.0.0-preview1-002111-00\\"
            }
        },
        {
            "type": "node",
            "name": "node",
            "configuration": {
                "binding.path": "C:\\repos\\azure-iot-gateway-sdk\\build\\bindings\\nodejs\\Debug\\nodejs_binding.dll"
            }
        }
    ],
    "modules": [
        {
            "name": "dotnet_sensor_module",
            "loader": {
                "name": "dotnetcore",
                "entrypoint": {
                    "assembly.name": "SensorModule",
                    "entry.type": "SensorModule.DotNetSensorModule"
                }
            },
            "args": "module configuration"
        },
        {
            "name": "dotnet_printer_module",
            "loader": {
                "name": "dotnetcore",
                "entrypoint": {
                    "assembly.name": "PrinterModule",
                    "entry.type": "PrinterModule.DotNetPrinterModule"
                }
            },
            "args": "module configuration"
        },
        {
            "name": "node_printer",
            "loader": {
                "name": "node",
                "entrypoint": {
                    "main.path": "../../../../../samples/nodejs_simple_sample/nodejs_modules/printer.js"
                }
            },
            "args": null
        },
        {
            "name": "node_sensor",
            "loader": {
                "name": "node",
                "entrypoint": {
                    "main.path": "../../../../../samples/nodejs_simple_sample/nodejs_modules/sensor.js"
                }
            },
            "args": null
        }
    ],
    "links": [
        {
            "source": "dotnet_sensor_module",
            "sink": "dotnet_printer_module"
        },
        {
            "source": "node_sensor",
            "sink": "node_printer"
        }
    ]
}

5-And Finally go to your publish directory and run the command: 
dotnet dotnet_core_managed_gateway.dll dotnet_core_managed_gateway_win.json

That it! :D If you have any problem just to make sure to play with your paths..

Let us know if it works for you, 

Thanks, 

Angelo Ribeiro.

**Comment by malichishti** [comment]
Hi @aribeironovaes 

Thanks a lot for all the details, however due to my lack of knowledge of nodeJs i was getting nowhere. As a result i have created a sample VS2017 project which includes Printer and Sensor module. Please find it in [dropbox](https://www.dropbox.com/s/3ee1kqq91p92cfb/TestGateway.zip?dl=0).

It runs fine if you remove the nodeJs module from gateway.json but as soon as you add nodeJs module it gives above error.

It will help tremendously if you can point out what i'm doing wrong in this solution. I can confirm nodeJs sample gateway runs fine on my computer.

Please note the projects use nuget packages which might need to be restored.

Regards,
Ali

**Comment by malichishti** [comment]
Hi @aribeironovaes , Did you get a chance to look at above?

**Comment by aribeironovaes** [comment]
Hi Ali,

Unfortunately not. I am in the middle of something. I will try to get into that this week.

Meanwhile, can you try what I mentioned and copy the nodejs binaries I mentioned (and showed on my picture)?

Let me know how that goes.

Thanks

Angelo Ribeiro

**Comment by malichishti** [comment]
Hi @aribeironovaes,

I can confirm that running it in dot net core 2.0.x resolves the issue. Thank you for your help.

Regards,
Ali
