### ISSUE TITLE
Error: undefined symbol: node_module_register when use 'serialport' NPM package with iot-edge

### ISSUE THREAD

**Issue by gregtoth** [Azure/iot-edge#308]
When the 'serialport' NPM package is used in a Node.js module running under azure-iot-gateway it always generates this error when starting up the application:

```
ERROR: Error: [app path]/node_modules/serialport/build/Release/serialport.node: undefined symbol: node_module_register
Error: Time:Tue Jun 13 15:16:27 2017 File:/home/vsciot/agent/_work/4/s/iot-edge/bindings/nodejs/src/nodejs.cpp Func:NODEJS_Create Line:135 Node process failed to start
Error: Time:Tue Jun 13 15:16:27 2017 File:/home/vsciot/agent/_work/4/s/iot-edge/core/src/gateway_internal.c Func:gateway_addmodule_internal Line:446 Module_Create failed.
Error: Time:Tue Jun 13 15:16:27 2017 File:/home/vsciot/agent/_work/4/s/iot-edge/core/src/gateway_createfromjson.c Func:Gateway_CreateFromJson Line:78 Failed to create gateway using lower level library.
Error: Time:Tue Jun 13 15:16:27 2017 File:/home/vsciot/agent/_work/4/s/src/gw/src/main.c Func:main Line:50 An error occurred while creating the gateway.

Gateway child process exited with code = 1
```

Has anyone had this problem and found a solution?

Other types of NPM packages work okay and using 'serialport' in a standalone Node.js application works fine under node v6.11.0. The problem is when serialport is used in an application that runs via azure-iot-gateway.

`nm node_modules/serialport/build/Release/serialport.node | grep node_module_register` shows `U node_module_register` 

Environment is Ubuntu 16.04.2, x64, node v6.11.0, npm 3.10.10 or 5.0.3, serialport v4.0.7 (some earlier versions have also been tested but also fail) as well as serialport@beta (currently 5.0.0-beta3) (also fails).

The built-in samples in iot-edge have the same problem when serialport is added to them. I've rebuilt iot-edge nodejs runtime and nodejs bindings from latest source and it still has the same problem when serialport is added.

**Comment by damonbarry** [comment]
We've seen this before internally. It seems to be a limitation in Node.js when built as a shared object. If you're using Node.js as a shared object (which we require to run Node.js modules in-proc), you probably won't be able to use Node.js libraries that interop with native code via node-gyp (as `serialport` does). I saw this a very long time ago so I forget the details...

If you need to use a library that interops with native code, I'd recommend writing an out-of-process Node.js module. This feature was added only recently, but allows you to run a Node.js app as an Edge module using your default installation of the Node runtime. There's more info [here](https://github.com/Azure/iot-edge/blob/master/samples/nodejs_remote_sample/README.md).
