### ISSUE TITLE
activation.type: launch - doesn't launch out of process module on OS X - inconsistent launches on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge#320]
I am using  samples/proxy-sample([1](https://github.com/Azure/iot-edge/tree/master/v1/samples/proxy_sample)) as 
`./samples/proxy_sample/proxy_sample ./launch_sample_lin.json`

The remote module(_proxy_sample_remote_) doesn't launch at all on Mac OS X. On an Ubuntu 14.04 LTS, it occasionally launches the remote module.

In both operating systems, if I manually launch the remote module in a second terminal as `./samples/proxy_sample/proxy_sample_remote outprocess_module_control`, then sample works well.

Is the sample expected to be use as above ? 

Operating System: Mac OS X 10.12.3
Build: Xcode 8.3.1
git describe: 2017-04-27-60-g5fea2f7

**Comment by damonbarry** [comment]
I've confirmed that it doesn't work on macOS. I made a few tweaks to the JSON file and got the application to launch, but then it fails to establish the nanomsg channel and exits. Need to do more investigation.

Given the changes I had to make to the JSON file just to get as far as I did, I'm actually surprised to hear you say it works on Ubuntu, even sometimes. I had to remove ".EXE" from name of the application (apparently a copy/paste bug from the Windows JSON file).

**Comment by kiranpradeep** [comment]
@damonbarry Ofcourse - I too did those changes(.exe part) on Ubuntu for it to launch :) Some time launches. Some times doesn't.

**Comment by zafields** [comment]
@kiranpradeep Can you map "inconsistent launches" to a percentage? I have observed it happening about once in every seven attempts. Is this consistent with your experience? It _feels_ like system resources are not getting cleaned up properly, but I will have to continue to investigate.

**Comment by kiranpradeep** [comment]
@zafields for me it is more like, once it works, it keeps working for long. Once it fails, it keeps failing for long.

**Comment by damonbarry** [comment]
I've confirmed (on Mac) that this issue is fixed by PR #507. I also tried it on Ubuntu 17.10 (in a VM), and confirmed that `./samples/proxy_sample/proxy_sample ./launch_sample_lin.json` behaves as expected. Please reopen if you continue to see this problem. Thanks!
