### ISSUE TITLE
running remote/outprocess modules in docker containers

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge#327]
Nanomsg supports TCP option. Is it possible to run outprocess/remote modules in docker containers( as mentioned in [README.md](https://github.com/Azure/iot-edge/blob/master/README.md) ) ? I am fine even if inter-module communication is insecure.

**Comment by darobs** [comment]
We're currently prepending the "control.id" with "ipc:" to form the nanomsg uri, so we are always assuming IPC.

If you want to connect to a Docker container, we could fix this to allow the user to specify their own uri, protocol included, or you could map the ipc socket into the Docker container using the "-v" option.

For example, if you want a Docker container to access the docker service, you can run it like this:
docker run -v /var/run/docker.sock:/var/run/docker.sock [...]

I haven't tried this, but I expect this will work for the sockets nanomsg creates as well.

**Comment by kiranpradeep** [comment]
@darobs Thanks a lot. That helped and we are good containers.
