### ISSUE TITLE
NodeModuleLoader_LoadBindingModule returned NULL

### ISSUE THREAD

**Issue by anweiss** [Azure/iot-edge#331]
I've been exploring IoT Edge modules with Node and running in to the following error:

```sh
File:/home/vsciot/agent/_work/4/s/iot-edge/core/src/module_loaders/node_loader.c Func:NodeModuleLoader_Load Line:79 NodeModuleLoader_LoadBindingModule returned NULL
```

Using `azure-iot-gateway` npm package v1.1.3. Used the [`generator-az-iot-gw-module`](https://github.com/Azure/generator-az-iot-gw-module) Yeoman generator to spin up a project. Running the module in a container using the following Dockerfile:

```Dockerfile
FROM node:6
RUN echo "deb http://httpredir.debian.org/debian/ jessie-backports main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb-src http://httpredir.debian.org/debian/ jessie-backports main contrib non-free" >> /etc/apt/sources.list
RUN apt-get update && \
    apt-get install -t jessie-backports -y openssl
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
CMD npm start
```

**Comment by jeffreyCline** [comment]
@anweiss Debian currently is not supported by our npm packages, this is a future work item. We do have Debian NuGet packages if that helps. You can find the NuGet package [here](https://www.nuget.org/packages/Microsoft.Azure.Devices.Gateway.Native.Debian.x64/).

**Comment by anweiss** [comment]
Thanks @jeffreyCline ... running this with an Ubuntu image worked great! Closing
