### ISSUE TITLE
What is the proper way to implement logging and error handling in modules?

### ISSUE THREAD

**Issue by ddobric** [Azure/iot-edge#343]
Logging for proposed way for error handling and logging in all supported languages.
There is internally a function LogError(), which might me used for this purpose. Can/should we use it?
How to us it (i.e.: .net)?

What is the best way to handle errors? I looks as we should use logger module, but logger module can only be used to trace messages and not the program state.

Thanks

**Comment by poleindraneel** [comment]
Having the same issue. 
Should logger be implemented as a separate module?

**Comment by ddobric** [comment]
Hi Indraneel,

logger can be implemented as separate module to protocol expected operation state. However, I see tracing of internal module state more interesting. I.E.: LogError().
But here is LogError() in .NET modules? How about LogWarning() etc., etc...

**Comment by damonbarry** [comment]
We don't currently have specific guidance or patterns RE how to do logging & error handling consistently across all supported languages and environments. For now, it's up to you to do something consistent within the application/modules that make up your gateway application. Of course, this approach is very flexible but also very primitive--we intend to provide stronger guidance and a more seamless solution in the next version. Thanks!
