### ISSUE TITLE
libcurl CURL_OPENSSL_3 error when running gw from node npm package on Arch linux

### ISSUE THREAD

**Issue by 345paul** [Azure/iot-edge#347]
On Arch Linux (kernel 4.11.9-1-ARCH), I've created a node project that uses the azure-iot-gateway npm package which just runs the simple sample using just the sensor.js and printer.js modules.  When calling run() function on the Gateway class, the spawned gw application fails with:

/<project-path>/node_modules/azure-iot-gateway-lin/bin/gw: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /<project-path>/node_modules/azure-iot-gateway-lin/bin/libaziotsharedutil.so)

If I add the **LD_PRELOAD** environment variable in the **index.js** file in the _azure-iot-gateway-lin_ package just before the spawn of the **gw** application, it will work.

```
  const options = {
    stdio: 'inherit',
    env: {
      'LD_PRELOAD': 'libcurl.so.3',
      'LD_LIBRARY_PATH': './:./bin:' + lib_file_folder
    }
  };
```

On Arch Linux, libcurl.so.3 comes with the libcurl-compat package and is a symlink to the libcurl-compat.so.4.4.0 library.  I can (and have tried) changing libcurl.so.3 above to libcurl.so.4.0.0 (which is also a symlink to the compat library) and that works.

The libcurl.so file on Arch Linux is a symlink that points to libcurl.so.4.4.0, which exhibits the CURL_OPENSSL_3 error.  I expect if I change the symlink for libcurl.so and point to libcurl-compat.4.4.0 it will work for this scenario although I've no idea what else I will break in the process if I do that.

So, without the LD_PRELOAD environment variable, it won't work on Arch Linux.

**Comment by damonbarry** [comment]
I'd suggest you file this issue in the [edge samples repo](https://github.com/Azure-Samples/iot-edge-samples/issues). However, the sample only officially supports Windows and Ubuntu Linux so you may be on your own here.

Would you say that the use of LD_PRELOAD is not acceptable? It seems like a pretty common way to fix up the paths when binaries are installed to a different location than where they were built.

**Comment by 345paul** [comment]
This isn't an issue with the samples as such, more to do with the npm package.  I appreciate though that Azure IoT Edge itself may not (yet?) be supported on Arch Linux (although this issue might be useful to other Arch users).

Once I'd added LD_PRELOAD, Azure IoT Edge seems to run absolutely fine on Arch.  I've even created an MQTT receiver module (very basic) that will pull in telemetry from local devices to push out to IoT Hub, so from an Arch Linux perspective, it looks good.

The only reason I raised the issue is because of the newer libcurl version on Arch Linux which in order to get CURL_OPENSSL_3 support, requires the use of a separate compatible library and LD_PRELOAD environment variable and for which I had to manually update the npm installed index.js file in the azure-gateway-lin pacakge.  The libcurl binaries are installed, at least on Arch, in their standard places, so that isn't the issue.

I'm assuming that the intention is that Azure IoT Edge will be compatible across a broad range of systems, including Arch in time?

**Comment by damonbarry** [comment]
The code in this repo is designed to be compatible across a broad range of systems, and abstractions are introduced where needed to facilitate porting to various platforms. Also, we have added/will add _official_ support for a small subset of platforms. But we don't intend to support lots and lots of platforms directly in this repo. Many platforms can be supported by the communities/users that need them.

I don't know specifically about Arch Linux.

Thanks,
Damon
