### ISSUE TITLE
Dependency Injection with Modules

### ISSUE THREAD

**Issue by vslepakov** [Azure/iot-edge#352]
Hi,

in order to keep the code testable I would like to insert some dependencies into iot-edge modules. What is the recommended way of doing this? ServiceLocator?

(Using .NET)

Thanks and best regards!

**Comment by damonbarry** [comment]
If you'd like to use a DI framework inside a .NET module you're developing, you can certainly do that. We don't have any recommendation for a particular framework.

**Comment by vslepakov** [comment]
How about passing dependencies into the module? 
Inside a module is a bit late, isn't it? Why close?
If I setup a container inside a module, than I would register concrete classes, how can I vary the behavior?

**Comment by vslepakov** [comment]
Or do you mean the whole logic is supposed to live outside the actual module class which just services as kind of a "main" method for a specific concern?
