### ISSUE TITLE
I can't build iot-edge on debian 9  

### ISSUE THREAD

**Issue by misoragod** [Azure/iot-edge#353]
Hi.

I’m trying to build iot-edge  on debian 9 that was installed  Drgonboard410c  but I can’t build it.
I was successful buil it on debian 8 to use  same board. 
I realized that differrence of version of libopenssl between debian 8 and debian 9.
Debian was   installed libopenssl 1.0.1t-1 and  Debian 9 was  installed libopenssl 1.1.0f-3.
How can I buid iot-edge on debian 9 or I can’t build it  ?   

- debian9

- gcc version 6.3.0 20170516 (Debian 6.3.0-18) 

- Qualcomm Dragon board 410c 

### **iot-edge/deps/c-utility/build/error.txt**
mnt/git/debian9/iot-edge/deps/c-utility/src/tlsio_openssl.c: In function ‘add_certificate_to_store’:
/mnt/git/debian9/iot-edge/deps/c-utility/src/tlsio_openssl.c:790:38: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
             BIO_METHOD* bio_method = BIO_s_mem();
                                      ^~~~~~~~~
/mnt/git/debian9/iot-edge/deps/c-utility/src/tlsio_openssl.c: In function ‘create_openssl_instance’:
/mnt/git/debian9/iot-edge/deps/c-utility/src/tlsio_openssl.c:856:5: error: ‘TLSv1_method’ is deprecated [-Werror=deprecated-declarations]
     const SSL_METHOD* method = TLSv1_method();
     ^~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /mnt/git/debian9/iot-edge/deps/c-utility/src/tlsio_openssl.c:5:
/usr/include/openssl/ssl.h:1612:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
 ^
/mnt/git/debian9/iot-edge/deps/c-utility/src/tlsio_openssl.c:860:9: error: ‘TLSv1_2_method’ is deprecated [-Werror=deprecated-declarations]
         method = TLSv1_2_method();
         ^~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /mnt/git/debian9/iot-edge/deps/c-utility/src/tlsio_openssl.c:5:
/usr/include/openssl/ssl.h:1624:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_method(void)) /* TLSv1.2 */
 ^
/mnt/git/debian9/iot-edge/deps/c-utility/src/tlsio_openssl.c:864:9: error: ‘TLSv1_1_method’ is deprecated [-Werror=deprecated-declarations]
         method = TLSv1_1_method();
         ^~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /mnt/git/debian9/iot-edge/deps/c-utility/src/tlsio_openssl.c:5:
/usr/include/openssl/ssl.h:1618:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_method(void)) /* TLSv1.1 */
 ^
/mnt/git/debian9/iot-edge/deps/c-utility/src/tlsio_openssl.c: In function ‘tlsio_openssl_deinit’:
/mnt/git/debian9/iot-edge/deps/c-utility/src/tlsio_openssl.c:1002:5: error: ‘ERR_remove_state’ is deprecated [-Werror=deprecated-declarations]
     ERR_remove_state(0);
     ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /mnt/git/debian9/iot-edge/deps/c-utility/src/tlsio_openssl.c:5:
/usr/include/openssl/err.h:248:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/aziotsharedutil.dir/src/tlsio_openssl.c.o] Error 1
make[1]: *** [CMakeFiles/aziotsharedutil.dir/all] Error 2
make: *** [all] Error 2
~

**Comment by marcschier** [comment]
Debian 9 resolves to 1.1 openssl package by default and the c-utility dependency was only tested and built against 1.0.2.  The current master of c-utility however does build against 1.1 as well.  Ahead of the team updating the dependencies in iot-edge repo, you could try to sync to master in c-utility.  But, there is a slight chance that this would break you somewhere else due to API changes.  Another option is to port the changes from tlsio_openssl.c and x509_openssl.c to get it building.  Or to somehow force building against 1.0.2 headers and libs on Debian 9.

**Comment by misoragod** [comment]
Thank you for the rapid response.
I'll use Debian 8.
