### ISSUE TITLE
Floating point values in data

### ISSUE THREAD

**Issue by abhatikar** [Azure/iot-edge#354]
Hi,

I am referring to [link](https://github.com/Azure/iot-edge/blob/master/bindings/nodejs/devdoc/nodejs_binding_hld.md)
and section below
/**
 * A message object that can be published to a message broker or
 * is received from a message broker.
 */
interface Message {
    properties: StringMap;
    content: Uint8Array;
}

What should be done if I want to send / publish floating point data like temperature of 23.45 C ?
Currently I see that it will round out to 23.
The content parameter is fixed as Uint8Array

Thanks
Abhijeet

**Comment by abhatikar** [comment]
@damonbarry Any ideas ?

**Comment by damonbarry** [comment]
@abhatikar The message payload is a byte array. The expectation is that users will serialize their data into byte array before sending to the broker, then deserialize back to the original data type (e.g. 64-bit floating point value) on the other end. E.g.:

```
#include <stdio.h>
#include <stdint.h>

int main() {
    const double temp = 23.45;

    const uint8_t* data = (const uint8_t*)&temp;
    uint8_t buf[sizeof(temp)];
    for (size_t i = 0; i < sizeof(temp); ++i) {
        buf[i] = data[i];
    }

    const double deserialized = *(double*)buf;

    printf("temp = %f\n", temp);
    printf("sizeof(buf) = %d\n", sizeof(buf));
    printf("buf = [ ");
    for (size_t i = 0; i < sizeof(temp); ++i) {
        printf("%#x, ", buf[i]);
    }
    printf("]\n");
    printf("deserialized temp = %f\n", deserialized);

    return 0;
}
```
This code was hastily written, but hopefully it illustrates the idea correctly. 😬

**Comment by avranju** [comment]
And in JavaScript you could something like this:

```
const temperature = 23.45;
const buffer = Buffer.allocUnsafe(8);
buffer.writeDoubleBE(temperature 0);
const msg = {
  properties: {},
  content: new Uint8Array(buffer)
};
```

To de-serialize a`Uint8Array` back into a `number`, you'd do something like this:

```
const buffer = Buffer.from(msg.content.buffer);
const temperature = buffer.readDoubleBE();
```

**Comment by damonbarry** [comment]
@avranju Right...Node.js not C. Thanks for catching that!

**Comment by abhatikar** [comment]
Thanks Guys...!
