### ISSUE TITLE
Include system/runtime deps for Windows builds

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/iot-edge#356]
It would be nice if the following system deps could be copied for Windows builds into the output directories facilitating easier test & deploy to run time environments like Windows containers.

DEBUG deps:
ucrtbased.dll
vcruntime140d.dll
msvcp140d.dll

RELEASE deps:
vcruntime140.dll
msvcp140.dll

**Comment by damonbarry** [comment]
Here's some [guidance](https://docs.microsoft.com/en-us/cpp/ide/redistributing-visual-cpp-files) on deploying DLLs from the VC runtime. The article advises against copying DLLs directly into the application folder, although for our samples I think that's a reasonable solution.

**Comment by myagley** [comment]
Contributions welcome!
