### ISSUE TITLE
Need help in receiving Cloud to device message

### ISSUE THREAD

**Issue by abhatikar** [Azure/iot-edge#357]
Hi,

I have made some changes to the simple nodejs sample as follows but I am getting a runtime error.

./nodejs_simple_sample ../../../samples/nodejs_simple_sample/src/gateway_sample_lin.json
Gateway is running. Press return to quit.
printer.receive - 46, 19
printer.receive - 33, 2
printer.receive - 47, 46
printer.receive - 27, 24
printer.receive - 47, 29
printer.receive - 18, 29
Id: c7221e5d-0df1-4334-8fde-d8559ae84eb9 Body: {"device": "hello"}
Id: c7221e5d-0df1-4334-8fde-d8559ae84eb9 Body: {"device": "hello"}
/usr/lib/node_modules/azure-iot-device-amqp/node_modules/amqp10/lib/utilities.js:144
    first = last = message._deliveryId;
                          ^

TypeError: Cannot read property '_deliveryId' of undefined
    at Object.utilities.dispositionRange (/usr/lib/node_modules/azure-iot-device-amqp/node_modules/amqp10/lib/utilities.js:144:27)
    at ReceiverLink.settle (/usr/lib/node_modules/azure-iot-device-amqp/node_modules/amqp10/lib/receiver_link.js:119:17)
    at ReceiverLink.accept (/usr/lib/node_modules/azure-iot-device-amqp/node_modules/amqp10/lib/receiver_link.js:73:8)
    at AmqpReceiver.complete (/usr/lib/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/lib/amqp_receiver.js:66:28)
    at /usr/lib/node_modules/azure-iot-device-amqp/lib/amqp_receiver.js:65:25
    at /usr/lib/node_modules/azure-iot-device-amqp/node_modules/azure-iot-amqp-base/lib/amqp.js:637:51
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

diff --git a/samples/nodejs_simple_sample/nodejs_modules/iothub_writer.js b/samples/nodejs_simple_sample/nodejs_modules/iothub_writer.js
index ad68d36..ccab119 100644
--- a/samples/nodejs_simple_sample/nodejs_modules/iothub_writer.js
+++ b/samples/nodejs_simple_sample/nodejs_modules/iothub_writer.js
@@ -49,20 +49,27 @@ class IotHubWriterModule
     }

Patch here [URL](https://pastebin.com/CrMnyMbY)

I am trying to implement sensor -> iothub and then iothub -> some customer actuation via another custom module.
If there is some example it will be of great help.
Also, if you can help with my current code whats wrong that would also help.
                                   
regards
Abhijeet

**Comment by abhatikar** [comment]
@damonbarry

**Comment by damonbarry** [comment]
The change you made was to add a new listener for messages from IoT Hub _every_ time you receive a message for the IoT Edge broker. I think you should set up the listener just once, in `create()` right after `iothub_client` is initialized.

The error is in the AMQP library's receiver code so whatever is happening, it is related to the new code you wrote. I'd make the change to only create one listener and see if that fixes the problem.

Note also that iothub_writer is a sample module (and has known issues on certain platforms, like Raspberry Pi). Our "real" IoT Hub module (written in C) is already set up to receive messages from IoT Hub. It also handles connections from more than one device. Check out the `simulated_device_cloud_upload` sample to see how to use it.

**Comment by abhatikar** [comment]
Thanks for the input...I have reviewed the simulated_device_cloud_upload code and now I feel comfortable and fixed the issue as well in my code.
