### ISSUE TITLE
way for request-response in iot-edge 

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge#358]
Does iot-edge provide a way for doing a request-response between modules? Currently, every module accepts a message in Receive method and has to respond back to the sender with another Publish call.

Consider a case when a module handling encryption needs to accept encrypted data and respond back with decrypted data.

**Comment by damonbarry** [comment]
@kiranpradeep Thanks for the question. iot-edge doesn't currently have a built-in way to do request/response. If you need request/response between two modules, then you'd need to mimic that pattern by sending messages and setting up the links properly in the broker (and possibly adding properties to the messages).

If you're specifically communicating with an encryption/decryption component and you don't want decrypted data flying around the broker, then it might be best to set up an out-of-band communication channel with that component.
