### ISSUE TITLE
What's the ETA for .NET Standard 2.0 and .NET Core 2.0 implementation

### ISSUE THREAD

**Issue by 3DHDSoft** [Azure/iot-edge#361]
What's the **ETA** for **.NET Standard 2.0** and **.NET Core 2.0** implementation, please?

**Comment by aribeironovaes** [comment]
Hi Ivan,

Have you tried to run the binding with .net core 2.0?

AFAIK it would work, I don't see a reason why, although I haven't test myself.

And our currently implementation complies with net standard 1.6, so you would be able to write your module on 2.0 and run it normally, again try it out and let us know if you face any problem.

Thanks

Angelo Ribeiro

**Comment by 3DHDSoft** [comment]
Upgraded all projects in iot-edge\bindings\dotnetcore\dotnet-core-binding\dotnet-core-binding.sln solution to .NET Core 2.0 and .NET Standard 2.0 respectively and updated all NuGet packages to the latest, including prereleases.

Using
- Microsoft Visual Studio Enterprise 2017 Preview Version 15.3.0 Preview 7.1
- .NET Core 2.0 SDK preview2 006497

Compiled successfully and all 85 unit tests passed.
Thank you very much for the great and quick help Angelo.

Ivan Farkas

**Comment by damonbarry** [comment]
Great!
