### ISSUE TITLE
Please give an example of modules communicating with each other

### ISSUE THREAD

**Issue by AceHack** [Azure/iot-edge#374]
Please give an example of the following "modules can communicate with each other via declarative message passing".

**Comment by damonbarry** [comment]
@AceHack This is basically referring to the "links" object which you specify in your JSON configuration. All of the samples provide examples of this concept. A good place to start would be the [Hello World](https://github.com/Azure/iot-edge/tree/master/samples/hello_world) sample.

**Comment by AceHack** [comment]
Thanks so that is the extent of the module communications?  source and sinks?  Is there any documentation explaining this in detail?

**Comment by damonbarry** [comment]
Yes, that is how modules communicate, by sending messages to/receiving messages from the broker. The links tell the broker how to route messages. The documentation is primarily in the samples (which in some cases have hyperlinks to online tutorials).

**Comment by AnujaK** [comment]
Hi @damonbarry the link doesn't work anymore. I am trying to make my edge modules talk to each other. Any help would be useful.

**Comment by damonbarry** [comment]
Updated link to v1 Hello World sample: https://github.com/Azure/iot-edge/tree/master/v1/samples/hello_world.
