### ISSUE TITLE
The Java binding module could not be located.

### ISSUE THREAD

**Issue by malichishti** [Azure/iot-edge#377]
Hi,

I would like to know how can one add a JAVA module to a .Net Core Managed Gateway built using https://www.nuget.org/packages/Microsoft.Azure.Devices.Gateway.Module.NetStandard/ ?

I have followed the instructions [here ](https://github.com/Azure/iot-edge/tree/master/samples/java_sample) and added the following as a loader:

```
"loaders": [
  {
	  "type": "java",
	  "name": "java",
	  "configuration":{      
		  "jvm.options":{
			"library.path": "C:\\xyz\\java_module_host.dll"
		  },                        
		  "binding.path": "C:\\xyz\\java_module_host.dll"
	  }          
  }
]
```

But it gives me **Func:JavaModuleLoader_LoadBindingModule Line:75 The Java binding module could not be located.**
![image](https://user-images.githubusercontent.com/17155996/29761902-00066b82-8c0f-11e7-8d90-6c66937f8637.png)

Any idea on what i'm doing wrong?

Regards,
Ali

**Comment by ancaantochi** [comment]
Hi,

The nuget package is dependent on Microsoft.Azure.Devices.Gateway.Native.Windows.x64 which require JDK x64 to be installed, it doesn't work with JDK 32-bit. 

Please add to PATH environment variable the full path to the jdk1.x.x\bin (example: C:\Program Files\Java\jdk1.x.x\jre\bin) and full path to jdk1.x.x\jre\bin\server. Using %JAVA_HOME% to set the PATH didn't work and I got the same "Error Loading Library".

Thanks,
Anca

**Comment by malichishti** [comment]
@ancaantochi Thank that solved that problem. But now i'm getting following:
![image](https://user-images.githubusercontent.com/17155996/29806075-8a9f5f44-8cd0-11e7-9e11-1036ced57727.png)
Any ideas?

Ali

**Comment by ancaantochi** [comment]
Hi,

library.path from jvm.options has to be to directory where the dlls are (like C:\\xyz)

Thanks,
Anca

**Comment by malichishti** [comment]
Thank you @ancaantochi that solved it.
