### ISSUE TITLE
retry policy for iothub module

### ISSUE THREAD

**Issue by villepalo** [Azure/iot-edge#378]
Would it be feasible, to add retry policy  (IOTHUB_CLIENT_RETRY_INTERVAL, ..., OTHUB_CLIENT_RETRY_EXPONENTIAL_BACKOFF_WITH_JITTER) as a new configurable property for iothub module.

**Comment by darobs** [comment]
Hello @villepalo 

Currently, we use the default retry policy available for the transport type.

We have "Expose retry/backoff features in IoT Hub module" in our backlog, but I don't have an estimated time for completion.

**Comment by villepalo** [comment]
Hi @darobs 

I already started to implement this kind of feature. It is 'must have' feature for me.
