### ISSUE TITLE
Help - NULL for module iothub.dll

### ISSUE THREAD

**Issue by grtn316** [Azure/iot-edge#388]
I have compiled the IoT Edge software as a dotnet core application (using nuget packages; Microsoft.Azure.Devices.Gateway.Module.Standard). Upon moving it to Linux, it functions normal until I include the iothub.dll file in my json config file:

﻿{
  "modules": [
    {
      "name": "dotnet_sensor_module",
      "loader": {
        "name": "dotnetcore",
        "entrypoint": {
          "assembly.name": "GenericNugetGW",
          "entry.type": "SensorModule.DotNetSensorModule"
        }
      },
      "args": "Config.json"
    },
    {
      "name": "dotnet_sample_module",
      "loader": {
        "name": "dotnetcore",
        "entrypoint": {
          "assembly.name": "GenericNugetGW",
          "entry.type": "NetstandardModuleSample.SampleModule"
        }
      },
      "args": "module configuration"
    }**,
    {
      "name": "IotHub",
      "loader": {
        "name": "native",
        "entrypoint": {
          "module.path": "iothub.dll"
        }
      },
      "args": {
        "IoTHubName": "hubname",
        "IoTHubSuffix": "suffix.net",
        "Transport": "MQTT"
      }
    }**
  ],
  "links": [
    {
      "source": "dotnet_sensor_module",
      "sink": "dotnet_sample_module"
    }**,
    {
      "source": "dotnet_sensor_module",
      "sink": "IotHub"
    },
    {
      "source": "IotHub",
      "sink": "dotnet_sensor_module"
    }**
  ]
}

**Here is the error:**

Error: Time:Wed Sep 13 09:24:39 2017 File:/home/ubuntu/iot-edge/core/src/module_loaders/dynamic_loader.c Func:DynamicModuleLoader_Load Line:72 DynamicLibrary_LoadLibrary() returned NULL for module iothub.dll
Error: Time:Wed Sep 13 09:24:39 2017 File:/home/ubuntu/iot-edge/core/src/gateway_internal.c Func:gateway_addmodule_internal Line:400 Failed to add module because the module could not be loaded.

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SensorModule.DotNetSensorModule.Destroy() in /home/ubuntu/GenericNugetGW/GenericNugetGW/DotNetSensorModule.cs:line 66
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at Microsoft.Azure.Devices.Gateway.NetCoreInteropInstance.Destroy(UInt32 moduleID) in **C:\agent\_work\7\s\iot-edge\bindings\dotnetcore\dotnet-core-binding\Microsoft.Azure.Devices.Gateway\NetCoreInterop.cs:line 166**
   at Microsoft.Azure.Devices.Gateway.GatewayInterop.CreateFromJsonInternal(String file_path)
   at GenericNugetGW.Program.Main(String[] args) in /home/ubuntu/GenericNugetGW/GenericNugetGW/Program.cs:line 22
Aborted (core dumped)

Also - Not sure where this directory in the error is coming from: C:\agent\_work\7\s\iot-edge\bindings\dotnetcore\dotnet-core-binding\Microsoft.Azure.Devices.Gateway\NetCoreInterop.cs

**Comment by grtn316** [comment]
I tried changing the module.path: iothub.dll to another non existent file and I get the same error. Seems like it cannot find the file. I tried adding the absolute path but that didn't seem to work either.

/home/ubuntu/GenericNugetGW/GenericNugetGW/bin/Debug/iothub.dll

**Comment by damonbarry** [comment]
The IoT Hub module is a native module, not .NET. So on linux it's an SO file, not DLL. Look at [simulated_device_cloud_upload_lin.json](https://github.com/Azure/iot-edge/blob/master/samples/simulated_device_cloud_upload/src/simulated_device_cloud_upload_lin.json) to see how the module is described for Linux-based devices.

**Comment by grtn316** [comment]
Thanks. I had previously tried the .SO file with no luck. We finally figured out that the libdotnetcore.so file I was pulling from another machine that has different file paths hard coded into it.

Any idea how/where this file is created? I'd like to make it configurable or at least make a simple process to generate it on the host device during deployment instead of it trying to reference the hard coded path from the main github project.
