### ISSUE TITLE
Error  - Invalid period time specified

### ISSUE THREAD

**Issue by raja4014** [Azure/iot-edge#390]
When trying to run the simulated device cloud sample, i m getting error "Invalid period time specified".

Following is the code snippet causing the error
int period = (int)json_object_get_number(root, "messagePeriod");
                    if (period <= 0)
                    {
                        LogError("Invalid period time specified");
                        result = NULL;
                    }

But i didn't see any entity with "messagePeriod" in the configuration file "simulated_device_cloud_upload_win" for windows

**Comment by damonbarry** [comment]
In `samples\simulated_device_cloud_upload\src\simulated_device_cloud_upload_win.json`, each of the simulated_device modules ("BLE1" and "BLE2") has "args.messagePeriod" set to 2000 (2 seconds).

Did you modify your JSON file? If you pull the latest source, do you see it?

Thanks,
Damon

**Comment by raja4014** [comment]
@ Damon:
Thanks. I missed that in my local source file simulated_device_cloud_upload_win.json. I got the latest from the github again. Now its working

**Comment by raja4014** [comment]
Closing the issue as it resolved
