### ISSUE TITLE
'Message Delivered'-notification from IotHub

### ISSUE THREAD

**Issue by villepalo** [Azure/iot-edge#391]
Hi,

We need a 'message delivered' notification from IotHub when message is successfully delivered. 

Our 'buffer'-module stores messages to database before sending them to IotHub and removes them after message is successfully delivered. Hence we need some kind of notification from IotHub about delivered messages. 

Are you planning to implement or interested in having this kind of mechanism (message delivered notification) in the IotHub module?

**Comment by myagley** [comment]
Closing as the PR was merged.
