### ISSUE TITLE
build_nodejs.cmd fails on raspberry pi

### ISSUE THREAD

**Issue by luther-c** [Azure/iot-edge#397]
In following the instructions at https://github.com/Azure/iot-edge/blob/master/samples/nodejs_simple_sample/README.md for my raspberry pi 3, which is running Raspbian 8.0 (jessie), Linux version 4.1.19-v7+,  I executed  `~/iot-edge/tools/build_nodejs.sh`.

All seemed fine for several minutes until it stopped with the following output:

```
g++ '-DV8_TARGET_ARCH_ARM' '-DENABLE_DISASSEMBLER' '-DV8_I18N_SUPPORT' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC' '-DUCONFIG_NO_TRANSLITERATION=1' '-DUCONFIG_NO_SERVICE=1' '-DUCONFIG_NO_REGULAR_EXPRESSIONS=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=0' '-DUCONFIG_NO_BREAK_ITERATION=0' '-DUCONFIG_NO_LEGACY_CONVERSION=1' '-DUCONFIG_NO_CONVERSION=1' -I../deps/v8 -I../deps -I../deps/icu-small/source/i18n -I../deps/icu-small/source/common  -pthread -Wall -Wextra -Wno-unused-parameter -fPIC -fno-strict-aliasing -mfloat-abi=hard -marm -fdata-sections -ffunction-sections -O3 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/pi/iot-edge/build_nodejs/node/out/Release/.deps//home/pi/iot-edge/build_nodejs/node/out/Release/obj.target/v8_base/deps/v8/src/compiler/representation-change.o.d.raw   -c -o /home/pi/iot-edge/build_nodejs/node/out/Release/obj.target/v8_base/deps/v8/src/compiler/representation-change.o ../deps/v8/src/compiler/representation-change.cc
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
deps/v8/tools/gyp/v8_base.target.mk:506: recipe for target '/home/pi/iot-edge/build_nodejs/node/out/Release/obj.target/v8_base/deps/v8/src/compiler/pipeline.o' failed
make[1]: *** [/home/pi/iot-edge/build_nodejs/node/out/Release/obj.target/v8_base/deps/v8/src/compiler/pipeline.o] Error 4
make[1]: *** Waiting for unfinished jobs....
rm 39a20a15d55d37c08ac2b76e41e1c31308db1699.intermediate
make[1]: Leaving directory '/home/pi/iot-edge/build_nodejs/node/out'
Makefile:73: recipe for target 'node' failed
make: *** [node] Error 2
```

Can anyone explain and suggest what I need to do?

Thanks

**Comment by avranju** [comment]
Looking at the output it appears you're using gcc and are in a Linux environment. I am wondering how you were able to run `build_nodejs.cmd` in this case since that is a Windows batch file. Could you try running `build_nodejs.sh` and see if that works better?

**Comment by luther-c** [comment]
Sorry, Mistake in the post, I'll edit.  It was `build_nodejs.sh` that caused the problem. Is it that this can't be done on 32 bit linux, or can't be done on raspbian anyway?

**Comment by avranju** [comment]
Ah. Understood. I have been able to run `build_nodejs.sh` on a Raspberry Pi 3 before and while it took a very long time to complete (~6 hours) it did eventually get it done. I have run into the error you're seeing when I tried to build a debug version of Node.js on the Pi when it simply ran out of memory during the build. I believe I had Raspbian Lite with no GUI installed and with nothing else running.

What would be ideal is if we can cross-compile Node.js for ARM. Unfortunately I haven't had the time to set this up and running successfully so far.

**Comment by luther-c** [comment]
Thanks very much for your help. I am also using the no GUI version of raspbian. There were a few other things running before, so I killed about as many processes as I dared and got it down to:
```
free -m
-/+ buffers/cache:         39        886
```
But after only 20 minutes or so of the script it had an error again. This time it was clear that this was to do with memory.

```
 g++ '-DV8_TARGET_ARCH_ARM' '-DENABLE_DISASSEMBLER' '-DV8_I18N_SUPPORT' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC' '-DUCONFIG_NO_TRANSLITERATION=1' '-DUCONFIG_NO_SERVICE=1' '-DUCONFIG_NO_REGULAR_EXPRESSIONS=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=0' '-DUCONFIG_NO_BREAK_ITERATION=0' '-DUCONFIG_NO_LEGACY_CONVERSION=1' '-DUCONFIG_NO_CONVERSION=1' -I../deps/v8 -I../deps -I../deps/icu-small/source/i18n -I../deps/icu-small/source/common  -pthread -Wall -Wextra -Wno-unused-parameter -fPIC -fno-strict-aliasing -mfloat-abi=hard -marm -fdata-sections -ffunction-sections -O3 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/pi/iot-edge/build_nodejs/node/out/Release/.deps//home/pi/iot-edge/build_nodejs/node/out/Release/obj.target/v8_base/deps/v8/src/crankshaft/lithium-codegen.o.d.raw   -c -o /home/pi/iot-edge/build_nodejs/node/out/Release/obj.target/v8_base/deps/v8/src/crankshaft/lithium-codegen.o ../deps/v8/src/crankshaft/lithium-codegen.cc
cc1plus: out of memory allocating 650800 bytes after a total of 32174080 bytes
deps/v8/tools/gyp/v8_base.target.mk:506: recipe for target '/home/pi/iot-edge/build_nodejs/node/out/Release/obj.target/v8_base/deps/v8/src/counters.o' failed
make[1]: *** [/home/pi/iot-edge/build_nodejs/node/out/Release/obj.target/v8_base/deps/v8/src/counters.o] Error 1
make[1]: *** Waiting for unfinished jobs....
rm 39a20a15d55d37c08ac2b76e41e1c31308db1699.intermediate
make[1]: Leaving directory '/home/pi/iot-edge/build_nodejs/node/out'
Makefile:73: recipe for target 'node' failed
make: *** [node] Error 2
```

Do you think that 886MB of memory is not enough? Would freeing up more of the 39MB that was used by other stuff really make the difference?

**Comment by avranju** [comment]
I have been able to build Node.js (v6.10.1) on a Pi 3 before. This does seem a bit strange. Do you have another Pi 3 handy to test and see if that makes a difference? I only had memory issues when trying to build the debug version and even then it fails only in the final linking step when it attempts to statically link with the whole world and put the final bits together. In your case just compilation seems to fail.

Another other possible variable is the version of GCC. If I remember right I think I used GCC 5.

**Comment by luther-c** [comment]
Thanks very much for your help. Your mention of GCC version 5 led me to try with Raspbian Stretch, which has GCC 5 as native, unlike Jessie. That made the difference. Thanks again
