### ISSUE TITLE
Build failing - submodules?

### ISSUE THREAD

**Issue by iizotov** [Azure/iot-edge#399]
Hi all,

 Build is failing with the following error:
```
./build.sh --enable-nodejs-binding

... (lines skipped)
-- Building ctest...
fatal: reference is not a tree: 037e318716e37eba358424380659dd1cd6d0554e
Unable to checkout '037e318716e37eba358424380659dd1cd6d0554e' in submodule path                                                                                                                                                              'deps/ctest'
```
Similar git errors with recursive cloning:
```
git clone --recursive https://github.com/Azure/iot-edge.git

... (lines skipped)
Cloning into 'testtools/testrunner'...
remote: Counting objects: 208, done.
remote: Total 208 (delta 3), reused 3 (delta 3), pack-reused 204
Receiving objects: 100% (208/208), 836.48 KiB | 350.00 KiB/s, done.
Resolving deltas: 100% (100/100), done.
Checking connectivity... done.
fatal: reference is not a tree: ee279c8b72d64d9ee8ca917ce00c17e0b522461d
```

**Comment by villepalo** [comment]
Same problem here!

**Comment by villepalo** [comment]
A bug similar to this is reported on iot-sdk-c (https://github.com/Azure/azure-iot-sdk-c/issues/250).

**Comment by darobs** [comment]
It looks like the commit used in the release tag was on a branch, and the branch was removed.  I pushed up a branch which contains the commit we use, and I think that put a band aid on the problem.  Please let me know if you're able to build now.

I'm predicting we'll have to pull the latest C Devices SDK release for a long term solution.

**Comment by man2nainwal** [comment]
Now it is showing unable to checkout deps/unmock-c.

fatal: reference is not a tree: **f41aa23712d82a27998d6918d3533d150e636ae8**
Unable to checkout 'f41aa23712d82a27998d6918d3533d150e636ae8' in submodule path '**deps/umock-c**'
CMake Error at gatewayFunctions.cmake:122 (message):
  Error pulling submodules: 1
Call Stack (most recent call first):
  dependencies-test.cmake:19 (findAndInstall)
  CMakeLists.txt:207 (include)

**Comment by darobs** [comment]
OK, so I did the same band aid for umock-c, and I did a fresh clone to check to see I could successfully initialize all the submodules, and was successful. 

It should be back to normal for now. long term solution is still the same.
