### ISSUE TITLE
dynamically_add_module_sample - add/removing modules on running gateway processes

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge#401]
The iot-edge sample([1](https://github.com/Azure/iot-edge/tree/master/samples/dynamically_add_module_sample)) to dynamically add modules shows how to add modules and links before a gateway process is started. But differently to what is specified in its readme([2](https://github.com/Azure/iot-edge/tree/master/samples/dynamically_add_module_sample#azure-iot-edge---dynamically-add-module-sample)), it doesn't mention how to add/delete modules once the gateway process is started( _Gateway_Start_  method [3](https://github.com/Azure/iot-edge/blob/master/samples/dynamically_add_module_sample/src/main.c#L72)).

Is it possible to update the example or to give pointers on how to add/delete modules/links from a running gateway process? In gateway doc([4](https://github.com/Azure/iot-edge/blob/master/core/devdoc/gateway_requirements.md)) are references to `Gateway_AddModule`, `Gateway_StartModule`, `Gateway_AddLink` etc, but it is not clear when to call what and also the impact resulting from removing modules/links on running gateway processes.

**Comment by aribeironovaes** [comment]
Hi @kiranpradeep , 

Have you tested adding a module with the gateway running? 

I would assume that it would work, however I haven't test myself. 
The point is, adding a module on a gateway running should not be that different from adding a module on a new gateway, so I don't feel that we would gain that much on adding a sample on that. 

But, please, if you tested and you feel that this is not the case, so we would be happy to accept a contribution. 

Let us know, 

Angelo Ribeiro

**Comment by kiranpradeep** [comment]
@aribeironovaes From the existing documentation, I had queries below

1. If I add a module with `Gateway_AddModule`, does it's `*_Start` method automatically get invoked? Will the other lifecycle methods like _ParseConfiguration, _FreeConfiguration etc will get invoked on the newly added module?
2. What is the purpose of `Gateway_StartModule` method? 
3. If I remove a module before removing its links, then the links are invalid. Will this result in exceptions/errors? If I remove a link(`Gateway_RemoveLink`) while a module is publishing, will `Broker_Publish` return an error code?

To give more background, I started exploring these options since
1. We had a requirement which expects iot-edge modules to be activated and deactivated on demand from the Azure cloud. I was planning to use Gateway_AddModule/RemoveModule for this. Assuming we already have Azure IoThub channel established (with azure-iot-sdk-c), what would be your suggestions?  
2. If there is a requirement which expects pre-compiled iot-edge modules(modules contains processing logic which cannot be written as ASA Edge Refresh2 SQL) to be pushed from cloud to the gateway on the fly, do you consider it to be a valid use-case? What would be your suggestions?

**Comment by aribeironovaes** [comment]
Hi @kiranpradeep, 

As I mention, I haven't test all these scenarios, however I think it should work. It would be great if you could test and let us know if you find any problem. To answer your questions: 
1-If a gateway is already started and you add a module, start method shall be called. Again, let us know if it's not the case. I don't know anybody with this scenario, they will usually stop the gateway, remove the modules and start it again... Parse Configuration, FreeConfiguration, if I remember correctly is part of the tasks that gets done when you add a module, so they will be called. 
2-The purpose of Start Module is to signalize the modules that gateway is UP AND RUNNING, so, all modules planned to be added are ready to receive and send message and the gateway is ready to process. This is to help modules that has on it's design to don't lose the initial messages. 
3-I personally haven't test this scenario, but If I remember correctly, yes, the link where that module that is being involved shall be removed. Again, if this is included on your scenario, test if out and if you find a problem, please, file an issue and we will look into it. 

Your scenarios seems doable to me and should work. We had actually an internship project here that did exactly this that you are mentioned and that worked.  

You could implement your scenarios in a couple of ways, so I don't think there is an write answer. If you can't use ASA module, you could implement your module that uses File Download (Downloading your module from a Blob Storage, as an example), and adding that to your gateway. 
You could do the same thing  for remove, having this "manageability" module to take care of this for you. 

Hope this helps, and let me know how it goes, 

Angelo Ribeiro.

**Comment by kiranpradeep** [comment]
Feels all these should be documented.
