### ISSUE TITLE
System.ArgumentNullException from broker.Publish(message)

### ISSUE THREAD

**Issue by v-tbert** [Azure/iot-edge#404]
I have a .net module that uses this function to publish messages:

		public static async Task PublishAsync(this Broker broker, Message message) =>
			await Task.Run(() => broker.Publish(message)).ConfigureAwait(false);

I was running my modules in the debugger and stepped away for a while and it went to sleep. When it came back up, I got an ArgumentNullException. However, I can see that neither the broker or the message argument is null. The parameter name is "s" which I don't define in my code as far as I can tell, so believe this is getting thrown internally to the broker.

"Value cannot be null.\r\nParameter name: s"	System.ArgumentNullException

**Comment by v-tbert** [comment]
I think I may have tracked this down to a problem with the processing of the dictionary of properties passed with the message. Apparently the broker doesn't like any of the *values* to be null and this is the exception you get if they are. If there is a technical reason the values can't be null, it would be great if the exception message was more specific.

**Comment by damonbarry** [comment]
I don't know of any reason why the values can't be null...

**Comment by damonbarry** [comment]
@v-tbert Please reopen if you'd like to continue investigating this. We'd need the call stack for the exception you saw, and/or more specific steps to reproduce the error. Thanks
