### ISSUE TITLE
System.AccessViolationException on simultaneous calls to GatewayInterop

### ISSUE THREAD

**Issue by DarthVella** [Azure/iot-edge#411]
NuGet Package: Microsoft.Azure.Devices.Gateway.Module.NetStandard 1.0.5

I have a .Net Core process that is intended to run multiple gateways. While testing the ability to construct them in parallel, the process began crashing. Sometimes it displayed a generic "dotnet has failed unexpectedly" dialog box, other times a System.AccessViolationException was thrown originating from the ```GatewayInterop.CreateFromJson(file_path)``` method. Another error was displayed in the console and is likely related.
> Error: Time:Wed Nov 15 16:25:11 2017 File:C:\agent\_work\7\s\iot-edge\deps\c-utility\adapters\lock_win32.c Func:Unlock Line:106 ReleaseSemaphore failed: 298

Reducing the number of active gateways to one stopped the errors, as did constructing them in sequence.

**Comment by aribeironovaes** [comment]
Hi @DarthVella , 

It would require more investigation, but If I remember correctly CreateFromJSon is not thread safe/reentrant. So, make sure you protect these calls with lockers when you create multithreaded solutions. 

Hope this helps, 

Angelo Ribeiro

**Comment by DarthVella** [comment]
@aribeironovaes Thanks for the confirmation; since it's intended/unavoidable, I'll close the issue. Do you happen to know if Destroy is similarly unsafe?
