### ISSUE TITLE
C/C++ Interface support for file upload to IOT Hub feature

### ISSUE THREAD

**Issue by Senthamizhgp** [Azure/iot-edge#416]
Is there C/C++ interface support for the feature - Upload files to IOT Hub (as our devices run C/C++ based modules and no .Net/Nodejs support available on the device)?

Based on the documentation available in the below link I could understand there are .Net/NodeJs and Java interface to perform file uploads.
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-file-upload

Basically is there any C/C++ interface for the .NEt equivalent 'UploadToBlobAsync' REST API.

Thanks.

**Comment by aribeironovaes** [comment]
Hi,

Did you check the C Device Client SDK? 
If I remember correctly they have support.

I would put a question on their github sdk if they support it running in the Edge (connected via Edge Runtime).

Thanks,

Angelo Ribeiro

**Comment by Senthamizhgp** [comment]
@aribeironovaes I did get it and below is the link.
https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_upload_to_blob

Thanks.
