### ISSUE TITLE
KeyNotFoundException on Raspberry Pi

### ISSUE THREAD

**Issue by jonbgallant** [Azure/iot-edge#418]
Get the following output when running `docker logs edgeHub -f` on Raspbian/Stretch.

`2017-11-16 19:32:18 [INF] - Updating reported properties for jongpi5/$edgeHub in cloud failed with error System.Collections.Generic.KeyNotFoundException The given key was not present in the dictionary.`

**Comment by myagley** [comment]
This is fixed int the latest release `1.0.0-preview017`. Closing.
