### ISSUE TITLE
iotedgectl do not fully respect to docker env variables

### ISSUE THREAD

**Issue by gickis** [Azure/iot-edge#422]
When you change docker uri via iotedgectl setup --docker-uri tcp://x.x.x.x:2375 ctl utility do not use this uri when starting runtime via iotedgectl  start.

Bug in file dockerclient.py (line 14). docker.APIClient should be initialized not with default parameters but with uri from config file.

**Comment by mrohera** [comment]
Hello,
Thank you for your comment.

Could you kindly describe your host environment and how you have Docker setup? What we would like to understand is why you would need to specify the host URI? If your running iotedgectl in Windows Subsystem for Linux (WSL), we are aware that the current release will not work and are working on addressing this.

Just FYI, the  --docker-uri CLI arg, is not meant to be the host URI, rather this is the URI that the Edge Agent will use to communicate with the docker endpoint. One most configurations the host URI would be the same as the Edge Agent URI. On Windows running Linux containers this would be different. For example your specified URI will not work rather unix:///var/run/docker.sock will work.

Ideally we were hoping that the default parameters would suffice in determining how to connect with docker and not have to invent other means to set this up but we are open to feedback.

**Comment by gickis** [comment]
Hello,
Thank you for quick response.

Right now I'm trying to minimize dependencies on host machine to minimum - just install docker and run one single command and that's it - IoT Edge is up and running(In other words, i'm trying to remove Python prerequisites to be installed). In that case I've created docker image for iotedgectl tool based on python image. And I'm starting container with mapped volume to support persisted data to be stored outside of container. And I've found that python docker client (that you are using to pull agent images, etc.) is using default settings to determine Docker endpoint. But would be great to use env variables too.

I hope you understood my deployment scenario:)

**Comment by mrohera** [comment]
Yup, the fix is that the tool will honor these env vars when available.

DOCKER_CERT_PATH
DOCKER_HOST
DOCKER_TLS_VERIFY

**Comment by mrohera** [comment]
With the release of azure-iot-edge-runtime-ctl 1.0.0rc17 this issue has been addressed. Please upgrade to this version by running (sudo) pip install -U azure-iot-edge-runtime-ctl.

Thank you again for reporting this and let us know if you have any other feedback.
