### ISSUE TITLE
[v1] C# module stops receiving messages

### ISSUE THREAD

**Issue by grtn316** [Azure/iot-edge#423]
Hello,

I have 2 devices using IOT Edge. 1 has a great network connection and another one has a connection that is up and down. When looking at the IOT Hub (S1) metrics, it shows that I have 120 connections...I assume these are outstanding from the 2nd device that is constantly up and down? After awhile, I am unable to see messages from the device with a great connection and start getting the error: Operation timeout expired after I call: deviceClient.SendEventAsync in C#. I have also tried setting my OperationTimeoutInMilliseconds parameter to 2000ms.

How can I maintain 2 connections with sporadic internet on one of the devices? I am trying to transmit 1 second messages.

Thanks,
David

**Comment by myagley** [comment]
Hi David,

Is it possible to post the logs for the Edge Hub when this is failing?

`docker logs edgeHub > edgehub.log` 

This will help us diagnose why your messages are not reaching the cloud.

Regarding the metrics, I believe what you are seeing is a quirk in the way the connections are displayed in the portal's metrics section. Depending on the time range, the graph will "roll up" the connection count using a "sum". This means with two connections over an hour, "rolled up" on the minute, you will see the count as 120. I've engaged the IoT Hub team about this issue.

In the meantime, there are a couple of things we are doing on IoT Edge to help here. The Edge Hub stores and forwards messages to the cloud to help with intermittent connections. You can adjust the retention policy in the Edge Hub's twin. We will also be improving the connection multiplexing in an upcoming release, to minimize the connections from the edge to the cloud.

**Comment by grtn316** [comment]
Thanks for the response back. I am actually using V1 and have done a bit of troubleshooting since posting. Most of my errors from the DeviceClient were coming from my loop listening for C2D messages. I also added code to buffer messages when my connection goes down. This cleared up a lot of my errors and has just led me to the issue...that I am not sure how to troubleshoot yet.

I am using the nuget packages for the gateway & device client. 
So, I start my module like this: 
class IoTModule : IGatewayModule, IGatewayModuleStart

Then my Receive function:
public async void Receive(Microsoft.Azure.Devices.Gateway.Message received_message)
        {

            log.Debug("Received message to send to IOTHub");
            dynamic mymessage = new JObject();      // creating a JSON object as the message
            mymessage = System.Text.Encoding.UTF8.GetString(received_message.Content, 0, received_message.Content.Length);
            var sMessage = new Microsoft.Azure.Devices.Client.Message(Encoding.UTF8.GetBytes(mymessage.ToString()));

            try
            {

              
                if (resetStatus == false) //another function resets the connection after 5 disconn/reconn from connectionstatus handler
                {

                    await deviceClient.SendEventAsync(sMessage);

                    log.Debug("Sent message to IOTHub");
                }
                else
                {

                    bufferedMessages.Add(sMessage, Convert.ToDateTime(received_message.Properties["polltime"]));
                
            }
            catch (Exception ex)
            {

                bufferedMessages.Add(sMessage, Convert.ToDateTime(received_message.Properties["polltime"]));
                
                log.Error("Receive:" + ex.Message + " Poll Time:" + received_message.Properties["polltime"]);
            }

        }

After awhile, this function stops firing (I stop seeing log message: "Received message to send to IOTHub"). This seems like its related to the service bus or my module is unable to listen anymore. I have a separate function running in a loop to confirm that the module is still alive that will write to the log every 30 seconds. I am publishing a message every 1 second and I am wondering if its getting overloaded after 24 hours or something.

**Comment by damonbarry** [comment]
@grtn316 Are you running your gateway on Linux, or Windows (or something else)? If Linux, or another POSIX-based system, your problem might have been fixed by PR #507.

Can you try it again and let me know if you're still seeing it? I'll close this issue for now. Please reopen if you still encounter the problem. Thanks!
