### ISSUE TITLE
Discrepancy whether or not hostName is required in config file.

### ISSUE THREAD

**Issue by jonbgallant** [Azure/iot-edge#424]
This file: https://pypi.python.org/pypi/azure-iot-edge-runtime-ctl states that hostname is not required in config:

```
// IoT Edge device's DNS name;
// Specifying a FQDN is only required when operating the
// IoT Edge as a 'Gateway' for leaf device connectivity.
// If a FQDN is unavailable, the host name could be used. **If left blank,
// the utility will determine the FQDN if available or the machine name.**
// This hostname value is needed for certificate
// generation for the Edge Hub server. This certificate is used to enable
// TLS connections from IoT Edge modules and leaf devices.
"hostName": "<Hostname>",
```

If run without hostName you get this error:
```
ERROR: Error when parsing config data from file: c:\temp\edge\jongwindows3\config.json. Invalid hostname. Hostname cannot be empty or greater than 64 characters: .
ERROR: Please check the configuration values in the config file and re-run 'iotedgectl setup'
ERROR: Errors were observed. Return Code: 1
```

**Comment by mrohera** [comment]
Thank you for reporting this discrepancy. If using the --config-file option to setup the Edge, it is required that the file be fully specified and the behavior you report would be expected. 

We will fix this in the documentation.

**Comment by mrohera** [comment]
With the release of azure-iot-edge-runtime-ctl 1.0.0rc17 the documentation has been updated. Please upgrade to this version by running (sudo) pip install -U azure-iot-edge-runtime-ctl or visit https://pypi.python.org/pypi/azure-iot-edge-runtime-ctl/1.0.0rc17

Thank you again for reporting this issue and let us know if you have any other feedback.
