### ISSUE TITLE
[V2][Preview] Unable to send data to the IoT Hub using Azure Function Module

### ISSUE THREAD

**Issue by surabhshah** [Azure/iot-edge#425]
Hello All,

I have been following a document [here](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-function) to deploy an Azure function as an edge module from a couple of days but with no success.
**Background :**
I have successfully setup the environment and also got the simulated temperature sensor module working with data on IoT hub. Also, another tutorial which targets Azure Stream Analytics as a module worked fine for me. 

I have also successfully created and uploaded the Azure function as a docker image which is getting installed on the IoT Edge runtime.

I am using windows docker containers to achieve the same.

**Issue :**
The data is generated by the simulated temperature sensor (can see it in the docker logs). But, the data does not seem to appearing in the Azure function module. 
The docker logs for Azure function "Filter Function" module are as below:

> D:\IoTEdge_V2\AzureFunc>docker logs filterfunction
> info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
>       User profile is available. Using 'C:\Users\ContainerUser\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
> info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
>       Creating key {e7c9bc3d-04cf-45a2-971b-2c1d288b0823} with creation date 2017-11-21 18:40:37Z, activation date 2017-11-21 18:40:37Z, and expiration date 2018-02-19 18:40:37Z.
> info: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[39]
>       Writing data to file 'C:\Users\ContainerUser\AppData\Local\ASP.NET\DataProtection-Keys\key-e7c9bc3d-04cf-45a2-971b-2c1d288b0823.xml'.
> info: Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService[0]
>       Initializing WebScriptHostManager.
> Hosting environment: Production
> Content root path: C:\app
> Now listening on: http://localhost:5000
> info: Host.Startup[0]
>       Reading host configuration file 'c:\approot\host.json'
> info: Host.Startup[0]
>       Host configuration file read:
>       {}
> fail: Host.Startup[0]
>       Unable to configure java worker. Could not find JAVA_HOME app setting.
> fail: Host.Startup[0]
>       Could not configure language worker Java.
> info: Host.Startup[0]
>       Generating 0 job function(s)
> info: Host.General[0]
>       Starting Host (HostId=925bd22439f6-1776609483, Version=2.0.1.0, ProcessId=1368, Debug=False, ConsecutiveErrors=0, StartupCount=0, FunctionsExtensionVersion=)
> No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
> warn: Host.Startup[0]
>       No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
> Job host started
> info: Host.Startup[0]
>       Job host started

Thanks,
Surabh

**Comment by aribeironovaes** [comment]
Hi Surahb,

From your logs the function runtime could not find your hosts.json which indicates an error when creating the image.

Which folder did you choose when you create your image from the Docker File? 
It must be the root folder of your function project which contais hosts.json and your function folder.

You can ignore the JAVA errors they are known issues.

Let me know,

Angelo Ribeiro

**Comment by surabhshah** [comment]
Hi Angelo,

Thanks for a quick revert. I chose the **Docker/Linux-x64** as the directory for **EXE_DIR** as it is mentioned in the document under **Publish a Docker image** section.
As you mentioned, I would now try using the root directory and post my further observations.

Thanks,
Surabh

**Comment by aribeironovaes** [comment]
Thanks for confirming Surabh,

It should be updated already in the documentation.

Let us know how it works and i will follow up here.

Thanks

Angelo Ribeiro

**Comment by surabhshah** [comment]
Hi Angelo,

You are fab! It worked like a charm. Thanks mate you saved a lot of me and my time. 

Best Regards,
Surabh

**Comment by surabhshah** [comment]
Issue solved. Hence closing it.
