### ISSUE TITLE
[V2][Preview] Unable to pull azureiotedge-agent container in Win2016 Server

### ISSUE THREAD

**Issue by Banchio** [Azure/iot-edge#427]
**Expected:**
Use docker pull to download the agent container

**Result:**
At the end of the extraction I get an error on the _UtilityVM_ folder. I've already taken procmon dump and compared to a successful one taken on my machine (win10) but I was unable to figure out what can be the problem.
**Output is:**
PS C:\Program Files\docker> docker pull microsoft/azureiotedge-agent:1.0.0-preview012-windows-amd64
1.0.0-preview012-windows-amd64: Pulling from microsoft/azureiotedge-agent
407ada6e90de: Extracting [==================================================>]  81.04MB/81.04MB
ad09b0550b6c: Download complete
ae907c318f69: Download complete
1e4026051ed1: Download complete
f75ad15cdb68: Download complete
a7b0673b002e: Download complete
3078420d560d: Download complete
3e6a3a31d521: Download complete
73d06785e606: Download complete
49b49614df8b: Download complete
15b932e95102: Download complete
6852c38027a7: Download complete
676af27184a6: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\docker\windowsfilter\e37bb66f1e953ed9ad4b8416c71bce53840384be1a5a7c7821f8c88d62108185\UtilityVM: The system cannot find the path specified.

**Docker Info:** (_sensible information oscured_)
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.06.2-ee-5
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1770.amd64fre.rs1_release.170917-1700)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 32GiB
Name: _myHostName_
ID: TT2J:EL7S:AZ3V:5XCH:HQDP:FFXV:RP7R:UF7V:EFC3:6UXS:UGYG:PBIX
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: _http://myusername:pwd@proxyserver_
Https Proxy: _http://myusername:pwd@proxyserver_
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by veyalla** [comment]
Hi @Banchio From the logs it seems like you are using build 14393 (a.k.a. RS1) as your Host OS. Azure IoT Edge v2 Public Preview only supports build 16299-based Hosts when used with Windows containers.

Please take a look at the Note in the perquisites page: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-simulate-device-windows#prerequisites

**Comment by Banchio** [comment]
sorry, was my fault, closing the issue
