### ISSUE TITLE
iotedgectl with --config-file and --auto-cert-gen-force-no-passwords message not clear

### ISSUE THREAD

**Issue by jonbgallant** [Azure/iot-edge#429]
I run this:

`iotedgectl --config-file --auto-cert-gen-force-no-passwords
`
and see this:
```
********************************************************************************
You are being prompted to enter a passphrase for the Edge Device private key.

To prevent this prompt from appearing, enter the passphrase via the command
line options --device-ca-passphrase or --device-ca-passphrase-file.
 - If you choose not to supply any passphrases, use command line option
   --auto-cert-gen-force-no-passwords.
 - If using --config-file to setup the runtime, setup the input file
   with the same options described above.
********************************************************************************
```

the actual fix is to set `security.certifications.selfSigned.forceNoPasswords` to true in the config file.

It wasn't clear in the message that I had to do that.

Jon

Blog ref: http://blog.jongallant.com/2017/11/azure-iot-edge-config-file-force-no-passwords-msg/

**Comment by mrohera** [comment]
Thanks, I agree the error message could be made clearer about what to do for the --config-file option. Will patch this for the next release.

**Comment by mrohera** [comment]
With the release of azure-iot-edge-runtime-ctl 1.0.0rc17 this bug has been addressed. Please upgrade to this version by running (sudo) pip install -U azure-iot-edge-runtime-ctl. 

Thank you again for reporting this issue and let us know if you have any other feedback.
