### ISSUE TITLE
[V2][Preview] Route configuration for C2D

### ISSUE THREAD

**Issue by surabhshah** [Azure/iot-edge#451]
Hello,

I am stuck with configuring the valid route for Cloud to Device messaging.

_Background:_
I have two modules modbus and custom module. I am sending data from my custom module to IoT hub and want to receive some commands from IoT hub which would decide some processing on the data. I tried using the below route, but it fails.

```
{
  "routes": {
    "modbusToFilter": "FROM /messages/modules/modbus/outputs/* INTO BrokeredEndpoint(\"/modules/formattermodule/inputs/input1\")",
    "formatterToIoTHub": "FROM /messages/modules/formattermodule/outputs/output1 INTO $upstream",
    "C2D": "FROM $upstream INTO BrokeredEndpoint(\"/modules/formattermodule/inputs/input1\")"
  }
} 
```
Any comments regarding the same would be of great help.

Thanks,
Surabh

**Comment by damonbarry** [comment]
IoT Edge does not support C2D messages for modules. If you have a _device_ connected to IoT Hub _through_ IoT Edge, it can receive C2D messages. But for modules, the only option is to use [direct methods](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods).

**Comment by surabhshah** [comment]
Thanks for the reply @damonbarry. 
So, isn't there any provision yet with which I could redirect the C2D message from Device(edge runtime I suppose) to the module?
To elaborate a bit more, I am looking at the following use case that suppose I have a custom module and I wish to start sending data up to the IoT hub whenever and web app requires it. But I can't use module twin for that as I want it to happen at a click of button rather than going and changing the config in portal.

Thanks,
Surabh

**Comment by damonbarry** [comment]
No, modules cannot receive C2D messages.

If I understand your scenario correctly, then I believe [direct methods](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods) are the better approach anyway. Even if you could use C2D messages, they go into a queue and may not be received for some time, so I wouldn't recommend them for a button click. Rather, in the button click event handler, send a direct method. If the edge device or the module aren't able to receive the method invocation, you'll know right away because it will fail.

**Comment by surabhshah** [comment]
Okay Thanks @damonbarry . I would checkout _direct methods_ and would post here if I face any issue regarding it.

Best Regards,
Surabh

**Comment by surabhshah** [comment]
Hi @damonbarry, seems that the _direct methods_ is not working with IoT edge. It works fine for the sample example using console application but does not seem to work and fails with a _timeout exception_. 
I have done similar steps mentioned in the doc [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-direct-methods) and tried to fit in the same things for IoT edge scenario. Request you to guide me in order to get it working on IoT edge.

Regards,
Surabh

**Comment by damonbarry** [comment]
I verified it yesterday with the C# SDK. The direct method will fail immediately if the device is not connected, or if it hasn't registered to listen for the specific method you're calling.

In your module, using the device SDK, you call `Microsoft.Azure.Devices.Client.DeviceClient.SetMethodHandlerAsync(string methodName, MethodCallback methodHandler, object userContext)` to register a callback that will be invoked whenever direct method `methodName` is invoked from the cloud. The callback has the signature `Task<MethodResponse> MethodCallback(MethodRequest methodRequest, object userContext)`, where `MethodRequest` is an object that gives you the `Name` of the call and the `Data` as a byte array.

Then in your web app, using the service client, you'd call `Microsoft.Azure.Devices.ServiceClient.InvokeDeviceMethodAsync(string deviceId, string moduleId, CloudToDeviceMethod cloudToDeviceMethod)` to invoke the method.

For example:
```
// ** In your module
Task<MethodResponse> PingMethodCallback(MethodRequest req, object userObj) =>
    Task.FromResult(new MethodResponse(200));

// ...
DeviceClient deviceClient = DeviceClient.CreateFromConnectionString(connectionString);
// ...
await deviceClient.SetMethodHandlerAsync("ping", PingMethodCallback, null);

// ** In your web app
CloudToDeviceMethodResult result = await serviceClient.InvokeDeviceMethodAsync(
        deviceId, moduleId, new CloudToDeviceMethod("ping"));
if (result.Status == 200) { /* SUCCESS */ }
```

**Comment by surabhshah** [comment]
Hi @damonbarry, thanks for confirming it with an example. It really helped me cross check my implementation. 
The way I implemented it, seems to be matching with what you said except of _method invocation_ part. 
I am using version _1.5.0_ of _Microsoft.Azure.Devices_ and as of now, it seems to be lacking  an overload for _InvokeDeviceMethodAsync_ method which takes _module ID_ as a parameter. I guess that is the thing which is missing on my side and I am unable to invoke the method in a module.
Request you to confirm this.

Regards,
Surabh

**Comment by damonbarry** [comment]
The versioning is a little tricky right now because we have multiple teams contributing to the library for different feature sets...

You want version *1.5.0-preview-001*. Version 1.5.0 does not have edge features (modules) in it...1.5.0 was bumped from 1.4.x because of some other new features, not modules.

**Comment by surabhshah** [comment]
Ohh I see... Thanks @damonbarry for confirming it. I will check it with version _1.5.0-preview-001_ and would let you know.

Regards,
Surabh

**Comment by surabhshah** [comment]
Thanks @damonbarry , it works!

Regards,
Surabh

**Comment by damonbarry** [comment]
@surabhshah Excellent!
