### ISSUE TITLE
[v2] IoT Edge is not handling big batches of messages

### ISSUE THREAD

**Issue by aribeironovaes** [Azure/iot-edge#455]
This issue is to track a bug found here: 
https://stackoverflow.com/questions/47872292/messages-not-being-routed-between-edge-modules

Basically, if module sends messages in batches higher than 10 messages, Edge Hub doesn't not sent all messages at a time. 

Fix is on it's way. 

Thanks, 

Angelo Ribeiro.

**Comment by myagley** [comment]
Closing. This has been fixed and released in `1.0.0-preview019`.
