### ISSUE TITLE
Edge on WSL Does Not Work

### ISSUE THREAD

**Issue by jonbgallant** [Azure/iot-edge#456]
Using: iotedgectl 1.0.0rc17

Using the following config file:

```
{
  "deployment": {
    "docker": {
      "edgeRuntimeImage": "microsoft/azureiotedge-agent:1.0-preview", 
      "loggingOptions": {
        "log-driver": "json-file", 
        "log-opts": {
          "max-size": "10m"
        }
      }, 
      "registries": [
        {
          "address": "jongacr.azurecr.io", 
          "password": "", 
          "username": "jongacr"
        }
      ], 
      "uri": "tcp://0.0.0.0:2375"
    }, 
    "type": "docker"
  }, 
  "deviceConnectionString": "", 
  "homeDir": "/etc/azure-iot-edge", 
  "hostName": "jonghp", 
  "logLevel": "info", 
  "schemaVersion": "1", 
  "security": {
    "certificates": {
      "option": "selfSigned", 
      "preInstalled": {
        "deviceCACertificateFilePath": "", 
        "serverCertificateFilePath": ""
      }, 
      "selfSigned": {
        "forceNoPasswords": true, 
        "forceRegenerate": false
      }
    }
  }
}
```

and this command:
`sudo iotedgectl --verbose DEBUG setup --config-file build/config/runtime.json`

I get this error:
```
DEBUG: Checking Edge dependencies for deployment: docker
DEBUG: Trying paths: ['/home/jong/.docker/config.json', '/home/jong/.dockercfg']
DEBUG: No config file found
DEBUG: Trying paths: ['/home/jong/.docker/config.json', '/home/jong/.dockercfg']
DEBUG: No config file found
ERROR: Could not connect to docker daemon.
('Connection aborted.', error(2, 'No such file or directory'))
ERROR: Docker is unavailable
CRITICAL: IoT Edge dependency not available: docker
```

I'm also using the dockerpy package and you have to pass in a base_url = 'tcp://0.0.0.0:2375' and tls=False for WSL to work correctly.

```
docker_client = docker.DockerClient(base_url='tcp://0.0.0.0:2375', tls=False)
```

@mrohera

**Comment by mboujonnier** [comment]
Docker server doesn't work on WSL, you need to install the client and communicates with the Windows version.
https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

**Comment by jonbgallant** [comment]
I’m doing that and docker works, but the Edge runtime doesn’t.

**Comment by mrohera** [comment]
This is how I got it to work on WSL:

- Make sure Expose daemon on tcp://localhost:2375 is checked is checked via the Docker settings.
- Set the following docker environment variables:
DOCKER_HOST:tcp://0.0.0.0:2375
DOCKER_TLS_VERIFY: 0

- Run your iotedgectl command as normal.

Just a FYI: The stock Python released in WSL (2.7.6) did not work for me and I ran into a whole host of problems. I upgraded the Python release to 2.7.14, which I built from source and installed and things just worked.

**Comment by jonbgallant** [comment]
variables set.
![image](https://user-images.githubusercontent.com/2163001/34626308-069400a0-f211-11e7-9e27-258ff3cf5f9d.png)

error message
![image](https://user-images.githubusercontent.com/2163001/34626326-12f7ba94-f211-11e7-8aea-50ed2841f708.png)

python version 2.7.14

![image](https://user-images.githubusercontent.com/2163001/34627621-28b98434-f216-11e7-8e51-26c3247bf799.png)

I got this same error when I used from_env() directly.  I think there's a bug in dockerpy that doesn't recognize the env vars.

Can you please try again from a fresh machine and let me know if you can get it to work?

**Comment by mrohera** [comment]
Can you please try re-running your command as follows?
sudo DOCKER_HOST="tcp://0.0.0.0:2375" DOCKER_TLS=0 iotedgectl setup <your input args>

I have a sneaking feeling that docker env variables are somehow not being propagated to the iotedgectl program in your setup.

**Comment by jonbgallant** [comment]
That worked. I researched and found the -E command, which also worked.

`sudo -E iotedgectl --verbose DEBUG setup --config-file build/config/runtime.json
`
but I get this when I run start


`sudo -E iotedgectl --verbose DEBUG start
`
```
Traceback (most recent call last):
  File "/usr/local/bin/iotedgectl", line 11, in <module>
    sys.exit(coremain())
  File "/mnt/c/temp/azure-iot-runtime/edgectl/__init__.py", line 25, in coremain
    return cli.execute_user_command()
  File "/mnt/c/temp/azure-iot-runtime/edgectl/edgecli.py", line 54, in execute_user_command
    self._execute_command()
  File "/mnt/c/temp/azure-iot-runtime/edgectl/edgecli.py", line 64, in _execute_command
    edge_cmd.execute()
  File "/mnt/c/temp/azure-iot-runtime/edgectl/commandbase.py", line 47, in execute
    self._obj.start()
  File "/mnt/c/temp/azure-iot-runtime/edgectl/deploymentdocker.py", line 100, in start
    is_updated = self._client.pull(image, username, password)
  File "/mnt/c/temp/azure-iot-runtime/edgectl/dockerclient.py", line 50, in pull
    inspect_dict = self._api_client.inspect_image(image)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/image.py", line 262, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 191, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))
```

**Comment by jonbgallant** [comment]
Here's what I did to get it to work:


1.	Do not install Docker in WSL, you can use Docker on your Windows machine by modifying the path.
2.	In Docker Settings/General, Check "Expose Daemon on tcp:// without TLS"
3.	Execute the following in a Bash terminal. This will make docker available in your Bash terminal.

```
echo "PATH=\"$PATH:$HOME/bin:$HOME/.local/bin:/mnt/c/Program\ Files/Docker/Docker/resources/bin\"" >> ~/.bashrc
echo "alias docker=docker.exe" >> ~/.bashrc
echo "alias docker-machine=docker-machine.exe" >> ~/.bashrc
echo "alias docker-compose=docker-compose.exe" >> ~/.bashrc
echo "export DOCKER_HOST='tcp://localhost:2375'" >> ~/.bashrc
source ~/.bashrc

sudo sh -c "echo Defaults  env_keep += \"DOCKER_HOST\" >> /etc/sudoers.d/docker"
```
