### ISSUE TITLE
[v2] PyPi Docs Are Incorrect

### ISSUE THREAD

**Issue by jonbgallant** [Azure/iot-edge#457]
They give this example:
`$> iotedgectl setup --verbose DEBUG --config-file edge_config.json
`
But it gives this error:
```
jong@jonghp:~/edgeprojects/edgeproject1$ sudo iotedgectl setup --verbose DEBUG --config-file build/config/runtime.json
usage: iotedgectl [-h] [--version] [--verbose]
                  {setup,start,restart,stop,status,update,uninstall,login} ...
iotedgectl: error: unrecognized arguments: --verbose DEBUG
```

You have to put --verbose before the setup command.

@mrohera

**Comment by mrohera** [comment]
Thank you for reporting this. We will fix this.

**Comment by mrohera** [comment]
The documentation was fixed. Please have a look here: [https://pypi.python.org/pypi/azure-iot-edge-runtime-ctl](https://pypi.python.org/pypi/azure-iot-edge-runtime-ctl).

Please have a look and thank you for reporting this.
