### ISSUE TITLE
Missing repository for (V1) Gateway with RPI and SensorTag.

### ISSUE THREAD

**Issue by djaus2** [Azure/iot-edge#459]
**cd ~
git clone https://github.com/Azure/iot-edge.git**

**_Can we have an update for this as it doesn't return a buildable folder._**
I guess things have moved.

You only get the README.md from the root Edge repository in **~iot-edge**

**Comment by jonbgallant** [comment]
Try the /v1 folder
https://github.com/Azure/iot-edge/tree/master/v1

**Comment by djaus2** [comment]
Thx but had tried that, no luck.

Did: git clone --recursive https://github.com/Azure/v1/iot-edge.git
Then cd ~/iot-edge/v1

Build proceeded then.
After awhile:
**[100%] Built target ble_gateway**
👍

**Comment by darobs** [comment]
All the V1 code has been moved to the v1 directory in this repo, and if this is at all confusing, that means we didn't make it clear enough. I  think I can tweak the docs to make it more clear. 

By the **[100%]** above, I'm assuming the build worked correctly once you found it?

**Comment by djaus2** [comment]
(a) Yes the build worked OK.
There were some warnings

I suggest the following rewordings:

Change
git clone https://github.com/Azure/iot-edge.git
cd ~/iot-edge

to
git clone **--recursive** https://github.com/Azure/v1/iot-edge.git
cd ~/iot-edge**/v1**

**Comment by djaus2** [comment]
NB: The Mac Address in the json file (as attached) was correct for my SensorTag

[gateway_sample.json.txt](https://github.com/Azure/iot-edge/files/1614990/gateway_sample.json.txt)

**Comment by djaus2** [comment]
The relevant code for the first error is:
`                                BLE_CONFIG ble_config;
                                if (parse_mac_address(
                                        mac_address,
                                        &(ble_config.device_config.device_addr)
                                    ) == false)
                                {
                                    /*Codes_SRS_BLE_05_013: [ BLE_ParseConfigurationFromJson shall return NULL if the device_mac_address property's value is not a well-formed MAC address. ]*/
                                    LogError("parse_mac_address returned false");
                                    free_instructions(ble_instructions);
                                    VECTOR_destroy(ble_instructions);
                                    result = NULL;
                                }`

**Comment by aribeironovaes** [comment]
Hi @djaus2, 

On your comment you said: "I suggest the following rewordings", can you clarify where do you expect to have this reworded? Which document?

Thanks, 

Angelo Ribeiro.

**Comment by damonbarry** [comment]
> git clone --recursive https://github.com/Azure/v1/iot-edge.git

This command will fail. The URL for the `iot-edge` repo does not include a `v1/` segment.
Also, the `--recursive` flag will work, but it's optional and usually unnecessary. Our build script will pull in submodules as needed. We don't document it because it adds complexity which we're already hiding in the build script.
