### ISSUE TITLE
[v2] Downstream device of transparent gateway by Paho MQTT C Client Library .

### ISSUE THREAD

**Issue by tkanoh** [Azure/iot-edge#460]
I would like to make the downstream device of transparent gateway using Paho MQTT C Client Library .
According to Paho's debug message, X509 authentication seems to be successful, but it will be disconnected afterwards.
In the log of edgeHub, 'Unable to generate identity for clientID ...' is output, and it seems that some parameter is missing.
Although MQTT's username and password are set to NULL, should I give something like string when connecting to IoT Hub?

**Comment by tkanoh** [comment]
It possivle to resolve by reading the source code of the following URL.

     https://github.com/Azure/azure-iot-sdk-c/blob/modules-preview/iothub_client/src/iothubtransport_mqtt_common.c

The branch of repository is 'modules-preview', is that correct ?

**Comment by mrohera** [comment]
The Edge runtime currently uses SASTokens for authentication and X.509 is something that is planned for future releases. 

The Azure IoT SDK you have called out above has a sample MQTT client this is good place to start. You will notice a connection string being used contains a component SharedAccessKey. This key is used to generate the SASToken to authenticate with the IoT Hub in the cloud.

Once you get familiar with what needs to be done, you could tailor your client code to connect to the Edge runtime pretty easily. The only difference as compared to connecting up to the cloud end point, is that the connection string would have an extra component GatewayName=<your edge hostname>.

If you have specific questions about the SDK I would suggest filing a Github issue here: [https://github.com/Azure/azure-iot-sdk-c](https://github.com/Azure/azure-iot-sdk-c)

If you run into connectivity and messaging problems with the Edge runtime you can continue the conversation here or create a new issue in this repo.

**Comment by tkanoh** [comment]
Sorry for delayed to report.
I was able to connect.
Thanks for your cooperation.
