### ISSUE TITLE
[v2] Docs missing WSL Install Steps

### ISSUE THREAD

**Issue by jonbgallant** [Azure/iot-edge#462]
Please add this to runtime-ctl docs and work with docs team to get in docs.ms.com

1.	Do not install Docker in WSL, you can use Docker on your Windows machine by modifying the path.
2.	In Docker Settings/General, Check "Expose Daemon on tcp:// without TLS"
3.	Execute the following in a Bash terminal. This will make docker available in your Bash terminal.

```
echo "PATH=\"$PATH:$HOME/bin:$HOME/.local/bin:/mnt/c/Program\ Files/Docker/Docker/resources/bin\"" >> ~/.bashrc
echo "alias docker=docker.exe" >> ~/.bashrc
echo "alias docker-machine=docker-machine.exe" >> ~/.bashrc
echo "alias docker-compose=docker-compose.exe" >> ~/.bashrc
echo "export DOCKER_HOST='tcp://localhost:2375'" >> ~/.bashrc
source ~/.bashrc

sudo sh -c "echo Defaults  env_keep += \"DOCKER_HOST\" >> /etc/sudoers.d/docker"
```

**Comment by mrohera** [comment]
Will add this information to the docs.

**Comment by mrohera** [comment]
The necessary information was added to the documentation here: [https://pypi.python.org/pypi/azure-iot-edge-runtime-ctl](https://pypi.python.org/pypi/azure-iot-edge-runtime-ctl)

Please have a look and thank you for reporting this.
