### ISSUE TITLE
Can Azure IoT-Edge V1 install in Redhat linux 7.4 ?

### ISSUE THREAD

**Issue by man2nainwal** [Azure/iot-edge#464]
Hi all,

I am using Redhat linux 7.4, while installing iot-edge to it, it shows "You need to run this command from the toplevel of the working tree".
Could you please tell me, what do I have to do ?

Thanks,
Manoj

**Comment by damonbarry** [comment]
We'll need more information to figure out what's going on.

>I am using Redhat linux 7.4, while installing iot-edge to it

What do you mean? What exactly did you "install", and how?

>it shows "You need to run this command from the toplevel of the working tree".

What command were you running when you saw this message?

Thanks,
Damon

**Comment by man2nainwal** [comment]
Hi @damonbarry ,

I cloned git repository first.
go inside iot-edge/v1 folder, and run command ./tools/build.sh --disable-native-remote-modules, then it shows "You need to run this command from the toplevel of the working tree".

Thanks,
Manoj

**Comment by damonbarry** [comment]
That's a git error.

Was that the only output from build.sh? If not could you provide the full output? Also, did you do anything special when you cloned the repo, or was it simply `git clone https://github.com/azure/iot-edge.git` with no extra options?

**Comment by man2nainwal** [comment]
Hi @damonbarry ,

yes, it was the only output from build.sh.

just cloned with git clone https://github.com/azure/iot-edge.git.

Thanks,
Manoj

**Comment by damonbarry** [comment]
OK. The only `git` command used by our build script, as far as I know, is the one to clone our dependencies as submodules. And I believe those commands only happen if the dependencies are missing.

Can you try first running the command:

```
git submodule update --init --recursive
```

...and then call the build script?

I'm not sure what is causing the error, but this might work around the problem.

**Comment by man2nainwal** [comment]
@damonbarry ,

Same issue again.

**Comment by damonbarry** [comment]
I just noticed the following git command in build.sh before any cmake stuff is called:

```
git submodule foreach --recursive --quiet "rm -r -f build/"
```

This is likely the command that is failing. Can you add the `-x` option to build.sh and paste the output here?

Also, what version of git are you using (output of `git --version`)?

**Comment by man2nainwal** [comment]
@damonbarry ,

Here is the output ------

[root@scson0016634001 v1]# ./tools/build.sh -x
+ '[' -n '' ']'
+ [[ OFF == ON ]]
+ [[ OFF == ON ]]
+ [[ OFF == ON ]]
+ [[ OFF == ON ]]
+ get_cores
++ grep -c '^processor' /proc/cpuinfo
+ CORES=1
++ uname -s
+ [[ Linux != Darwin ]]
++ expr 500000 '*' 1
+ MINVSPACE=500000
+ MEMAR=($(sed -n -e 's/^MemTotal:[^0-9]*\([0-9][0-9]*\).*/\1/p' -e 's/^SwapTota                                                                                                             l:[^0-9]*\([0-9][0-9]*\).*/\1/p' /proc/meminfo))
++ sed -n -e 's/^MemTotal:[^0-9]*\([0-9][0-9]*\).*/\1/p' -e 's/^SwapTotal:[^0-9]                                                                                                             *\([0-9][0-9]*\).*/\1/p' /proc/meminfo
+ '[' -z 3882872 ']'
+ '[' -z 4194300 ']'
+ let VSPACE=3882872+4194300
+ '[' 8077172 -lt 500000 ']'
+ cd /root/Azure/iot-edge/v1
+ cmake_root=/root/Azure/iot-edge/v1/build
+ rm -r -f /root/Azure/iot-edge/v1/build
+ git submodule foreach --recursive --quiet 'rm -r -f build/'
You need to run this command from the toplevel of the working tree.

Regards,
Manoj

**Comment by damonbarry** [comment]
OK. It is failing on the `git submodule foreach ...` command as I expected. And you're using a very old version of git (nearly 4 years old). So I suspect that `git submodule foreach` behaved a little differently back then, and it's not compatible with the way we're using it today in our build script.

If you're building from a fresh `git clone`, or if you do `git submodule deinit -f .` before building (completely wipes out all the submodule subdirectories), _or_ if you manually do `rm -rf build/` in each submodule directory, then **you can safely remove or comment out the `git submodule foreach ...` line from your local script to get past this problem**.

**Comment by man2nainwal** [comment]
@damonbarry ,
Thank you, its git problem.

Now its working.

**Comment by damonbarry** [comment]
Glad to hear it! Closing...
