### ISSUE TITLE
[v2 request] Can modules be allowed to start when there is no network

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge#467]
As per iot-edge-runtime doc([1](https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-runtime)), during the public preview, the runtime must be connected every time it tries to authenticate a device. This is perfectly fine. But, currently, if the gateway is started without internet connectivity, only the edgeAgent module is started. All other modules including the edgeHub are not even started. We are trying to migrate a v1 application to v2. The failure to start the modules will result in failure to even collect data and hence we will lose data.

Can v2 modules be allowed to start even if there is no internet connectivity? Please see that request is only to allow modules to start. There is no necessity the modules be allowed to connect to edgeHub. This module to edgeHub connectivity could be delayed till there is internet connectivity (until then SendEventAsync/IoTHubClient_LL_SendEventToOutputAsync will fail).

We are ok write code to persist data locally within modules when there is no connectivity. We are ok to live with a local copy of module twin when there is no connectivity.

**Comment by avranju** [comment]
The Edge runtime does have support for this scenario, i.e., if it has started up at least once when it had connectivity then subsequent starts should work without connectivity. And by "work" here I mean that the modules should get started up automatically. Unfortunately, a recent change appears to have broken this functionality. Will take this up as a bug and get it resolved. Thanks for filing this.

**Comment by PtwHub** [comment]
Thanks. We have a hybrid design where we will require the IoT-Edge to install without the cloud and operate for extended periods without cloud connectivity. Is this in the cards, or do we need to move on? Thank you for a clear message regarding the strategy here.

**Comment by myagley** [comment]
This has been fixed in a recent release. Please reopen if you are still running into this issue. Thanks!
