### ISSUE TITLE
[V2][Preview] Direct Methods fail to work over long period

### ISSUE THREAD

**Issue by surabhshah** [Azure/iot-edge#468]
Hello,

I was recently figuring out direct methods to invoke edge module methods and got it working. However, the direct method does not seem to work over longer periods. What I mean by longer periods is, I started a module with a method handler which is running but not sending any payload to IoT hub. I am able to invoke the method if I try it in say half an hour after starting the module. However, if I try to invoke the method  after 12 to 14 hours, it fails with a timeout exception even if the module is in a running state. The direct methods work after restarting the module.

Steps to Reproduce:
1) Register a method handler in a module.
2) Try to invoke the method -> Find this to be working
3) Keep the module in a running state for around 12 hours
4) Again try to invoke the method.

Request you to help & appreciate comments if I am going wrong somewhere.

Regards,
Surabh

**Comment by aribeironovaes** [comment]
Hi @surabhshah , 

Can you turn logs on Edge Hub on? 
Take a look here: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot
Try to use this command: 
iotedgectl setup --runtime-log-level DEBUG
Check if you start getting [DBG].... 

If you can get a repro with that turned on it would help us to identify if it's a known issue. 

Thanks a lot in advance!

Angelo Ribeiro.

**Comment by surabhshah** [comment]
Hi @aribeironovaes ,

Sure. I will try to reproduce the issue with DEBUG logs and post them here.

Regards,
Surabh

**Comment by aribeironovaes** [comment]
Thanks @surabhshah , 

From your logs, looks like you hit a bug we have fixed lately. 
Fix for this will be on the next release. I will leave this issue opened till we have released and we will let you know so you can confirm it's working (I will test as well). 

Thanks, 

Angelo Ribeiro

**Comment by surabhshah** [comment]
Thanks for confirming it @aribeironovaes. Going in a standby mode till then :)

Regards,
Surabh

**Comment by myagley** [comment]
Closing as a fix was released in the February release. Please reopen if you are still facing issues.
