### ISSUE TITLE
[V2] auto start edgeAgent on Windows

### ISSUE THREAD

**Issue by mingwei0314** [Azure/iot-edge#472]
How to set auto start edgeAgent on Windows?

**Comment by aribeironovaes** [comment]
Hi @mingwei0314 , 

Are you asking about how to auto start edgeAgent on a windows container inside docker windows? 

Thanks, 

Angelo Ribeiro.

**Comment by aribeironovaes** [comment]
BTW, just got the information that it should actually just work. 
Did you test and it's not working?

Thanks, 

Angelo Ribeiro.

**Comment by mingwei0314** [comment]
Hi @aribeironovaes 
After I verified the function is working.
Thanks your replay.
