### ISSUE TITLE
iotedgectl can not pull the diy image（follow the doc about use machine learning as iot edgemodule ） from Azure Contanier Registry

### ISSUE THREAD

**Issue by ohmyheartbeat** [Azure/iot-edge#473]

**Comment by surabhshah** [comment]
Hi @ohmyheartbeat,

Please refer to issue #449 . As it is targeted at a similar issue. Request you to post your findings.

Regards,
Surabh

**Comment by ohmyheartbeat** [comment]
![default](https://user-images.githubusercontent.com/31534021/34940020-f52946d4-fa28-11e7-83fb-0498226ffdda.png)

**Comment by ohmyheartbeat** [comment]
may be the edgeAgent cash?

**Comment by surabhshah** [comment]
Hi @ohmyheartbeat,

It doesn't seem that the **edgeAgent** is crashing, it has just executed the pull command and waiting for the same to complete. Please run the _iotedgectl login_ command after setup command. Hope it helps.

Regards,
Surabh

**Comment by ohmyheartbeat** [comment]
Hi @surabhshah，
    I already run _iotedgectl login_  command set the container registery accesskey, I use the _docker exec edgeAgent printenv_ and the infos is right.
   Regards,
   ohmyheartbeat

**Comment by ohmyheartbeat** [comment]
and the Stream Analytics job as a module to deploying follow the doc , but when monitor temperature up 70 long time,nothing happend, but the doc say will be get 'reset' command

**Comment by ohmyheartbeat** [comment]
![default](https://user-images.githubusercontent.com/31534021/34970247-3464672c-faae-11e7-9ede-5eb28b7aa111.png)

**Comment by ohmyheartbeat** [comment]
@avranju Can you help me resolve this question

**Comment by avranju** [comment]
Are you able to pull these images via `docker pull`?

**Comment by ohmyheartbeat** [comment]
yes,the docker pull is work,but may ba happen  unkonwn blobs


 ______________________________________


Email: ForeverNone258@163.com
 
发件人： Rajasekharan Vengalil
发送时间： 2018-01-17 02:46
收件人： Azure/iot-edge
抄送： ohmyheartbeat; Mention
主题： Re: [Azure/iot-edge] iotedgectl can not pull the diy image（follow the doc about use machine learning as iot edgemodule ） from Azure Contanier Registry (#473)
Are you able to pull these images via docker pull?

**Comment by avranju** [comment]
If `docker pull` is working and Edge Agent is unable to pull the image then the credentials may not have been provided for this registry in Edge Agent. You may want to verify that the file `/etc/azure-iot-edge/config.json` contains the container registry credentials. Here's an example that contains the registry credentials in the `registries` array (I have elided the actual credentials below):

```json
{
  "schemaVersion": "1",
  "deviceConnectionString": "...",
  "homeDir": "...",
  "hostName": "edge1.devices.net",
  "logLevel": "debug",
  "security": {
    "certificates": {
      "option": "selfSigned",
      "selfSigned": {
        "forceRegenerate": false,
        "forceNoPasswords": true
      },
      "preInstalled": {
        "deviceCACertificateFilePath": "",
        "serverCertificateFilePath": ""
      }
    }
  },
  "deployment": {
    "type": "docker",
    "docker": {
      "uri": "unix:///var/run/docker.sock",
      "edgeRuntimeImage":
        "microsoft/azureiotedge-agent:1.0-preview",
      "registries": [
        {
          "address": "...",
          "username": "...",
          "password": "..."
        },
        {
          "address": "...",
          "username": "...",
          "password": "..."
        }
      ],
      "loggingOptions": {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "11m"
        }
      }
    }
  }
}
```
