### ISSUE TITLE
[v1] Documentation links lead to 404

### ISSUE THREAD

**Issue by wesyao** [Azure/iot-edge#476]
Links on Useful Resources Broken.

![image](https://user-images.githubusercontent.com/16310155/35066049-170c712a-fb84-11e7-82a1-50ba6c8e028f.png)

**Comment by aribeironovaes** [comment]
Thanks for reporting @wesyao , 

Looking into it.

**Comment by aribeironovaes** [comment]
This is going to be fixed by @darobs on the next release. 

Thanks for reporting.

**Comment by darobs** [comment]
Updated documentation links as part of the release process.
