### ISSUE TITLE
[v1] Raspberry and Assembly not found

### ISSUE THREAD

**Issue by malichishti** [Azure/iot-edge#483]
Hi,
I'm trying to run a Dot Net Core managed gateway on Raspberry Pi. Following are the steps i have taken:

1. Created a Dot Net Core application
2. Added [Microsoft.Azure.Devices.Gateway.Module.NetStandard](https://www.nuget.org/packages/Microsoft.Azure.Devices.Gateway.Module.NetStandard/) nuget package
3. Wrote following code
![image](https://user-images.githubusercontent.com/17155996/35210075-e477abe2-ffa4-11e7-923e-33bf34601084.png)
4. Built the application using Target Runtime as linux-arm to get [this output](https://www.dropbox.com/s/z4fmnqxdlzuy444/ConsoleApp3.zip?dl=0)
5. Followed [this ](http://blog.faister.com/2017/09/04/building-docker-container-with-azure-iot-edge-cross-compiled-libraries-for-raspberry-pi/)article to cross compile gateway for Raspberry Pi
6. Copied following files to my App folder from the [tar file](https://www.dropbox.com/s/x832lw3sa92ojk8/iot-edge-rpi.tar.gz?dl=0) created in above step
          a. \iot-edge\build\core\libgateway.so
          b. \iot-edge\build\samples\dotnet_core_module_sample\SensorModule.dll
          c. \iot-edge\build\samples\dotnet_core_module_sample\PrinterModule.dll
7. Copied this [schema file](https://www.dropbox.com/s/k6i9cqvj1l40baa/schema.json?dl=0) to my App folder
8. Ran my application to get following error:
![image](https://user-images.githubusercontent.com/17155996/35210712-5e7b388a-ffa7-11e7-986b-c8916a74febd.png)
9. Copied following files from [Step 5 tar file](https://www.dropbox.com/s/x832lw3sa92ojk8/iot-edge-rpi.tar.gz?dl=0) to /usr/lib/
          a. \iot-edge\build\core\libgateway.so
          b. \iot-edge\build\bindings\dotnetcore\libdotnetcore.so
          c. \iot-edge\deps\nanomsg\build\libnanomsg.so.5.0.0
10. Now it runs but i get following error:
![image](https://user-images.githubusercontent.com/17155996/35210891-1e036f38-ffa8-11e7-8366-ded4edbcc498.png)

Any ideas?

**Comment by damonbarry** [comment]
@malichishti Some of the [comments](https://github.com/Azure/iot-edge/issues/290#issuecomment-320545555) in #290 might be helpful.

**Comment by malichishti** [comment]
Yes, i followed his blog to cross compile for Raspberry Pi **Step 5** http://blog.faister.com/2017/09/04/building-docker-container-with-azure-iot-edge-cross-compiled-libraries-for-raspberry-pi/
And that issue gets resolved after Step 9 above. Only remaining issue is Step 10.

**Comment by damonbarry** [comment]
It sounds like you already have SensorModule.dll copied into your app directory. Is Microsoft.Azure.Devices.Gateway.dll there as well (comes from the Microsoft.Azure.Devices.Gateway.Module.NetStandard project you referenced)? How about libaziotsharedutil.so (from the tar file produced by that dockerfile)?

If those are in place, then you'll have to use `ldd` to look at the .SO (ELF) files and ensure all their dependencies are in place. You'd also need to check for any dependencies on the .DLL (PE) files, although I'm not sure how best to do that on RPi.

**Comment by malichishti** [comment]
I do have the SensorModule copies along with Microsoft.Azure.Devices.Gateway.dll and following:
![image](https://user-images.githubusercontent.com/17155996/35256731-4bb57bd2-0049-11e8-8abf-a012cee1504a.png)
`ldd` also comes back fine. The problem at this point is it is unable to find SensorModule.dll and i'm not aware of any option to specify its path etc.

**Comment by damonbarry** [comment]
I was able to get our dotnet_core_managed_gateway sample working on RPi3 (Rasbian Jessie), which should be very similar to your custom app. Here's what I did:

## Dockerfile
The Dockerfile from the [blog article](http://blog.faister.com/2017/09/04/building-docker-container-with-azure-iot-edge-cross-compiled-libraries-for-raspberry-pi/) you referenced doesn't package the .NET Core runtime libraries into the tarball, or at least I couldn't find it. So I updated the Dockerfile before I built it:
  - changed the git clone command so I could build a version of iot-edge from the time when this Dockerfile was written:
```
RUN git clone --branch 2017-08-21 https://github.com/Azure/iot-edge.git /iot-edge
```
  - added a dotnet publish step _after_ build.sh but _before_ tar:
```
RUN dotnet publish /iot-edge/samples/dotnet_core_managed_gateway --runtime linux-arm
```

## .NET Core dependencies
On the Pi, I installed a component required by .NET Core:
```bash
sudo apt-get install libunwind8
```

## ldconfig
Also on the Pi, I ran the `ldconfig` command to tell the OS where to find things like libgateway.so and libdotnetcore.so (there are probably other ways to do this too):
```bash
sudo ldconfig -v /home/pi/iot-edge/build/core /home/pi/iot-edge/deps/nanomsg/build /home/pi/iot-edge/install-deps/lib /home/pi/iot-edge/build/bindings/dotnetcore
```

## config.json
Finally I updated `samples/dotnet_core_managed_gateway/dotnet_core_managed_gateway_lin.json` with some information about where to find .NET Core-related bits (including our binding):

```json
{
  "loaders": [
    {
      "type": "dotnetcore",
      "name": "dotnetcore",
      "configuration": {
        "binding.path": "/home/pi/iot-edge/build/bindings/dotnetcore/libdotnetcore.so",
        "binding.coreclrpath": "/home/pi/iot-edge/samples/dotnet_core_managed_gateway/bin/Debug/netcoreapp2.0/linux-arm/publish/libcoreclr.so",
        "binding.trustedplatformassemblieslocation": "/home/pi/iot-edge/samples/dotnet_core_managed_gateway/bin/Debug/netcoreapp2.0/linux-arm/publish"
      }
    }
  ],
  "modules": ...
}
```

With these changes, I was able to do:
```bash
pi@raspberrypi:~ $ cd ~/iot-edge/samples/dotnet_core_managed_gateway/bin/Debug/netcoreapp2.0/linux-arm/publish
pi@raspberrypi:~/iot-edge/samples/dotnet_core_managed_gateway/bin/Debug/netcoreapp2.0/linux-arm/publish $ ./dotnet_core_managed_gateway ~/iot-edge/samples/dotnet_core_managed_gateway/dotnet_core_managed_gateway_lin.json
.NET Core Gateway is running. Press return to quit.
25/01/2018 03:42:53> Printer module received message: SensorData: 951757567
        Property[0]> Key=source : Value=sensor
25/01/2018 03:42:58> Printer module received message: SensorData: 510088861
        Property[0]> Key=source : Value=sensor
25/01/2018 03:43:03> Printer module received message: SensorData: 235503534
        Property[0]> Key=source : Value=sensor
25/01/2018 03:43:08> Printer module received message: SensorData: 298839206
        Property[0]> Key=source : Value=sensor
```

**Comment by damonbarry** [comment]
FYI I submitted a PR to update the Dockerfile: faister/iot-edge-rpi#2.

**Comment by malichishti** [comment]
@damonbarry your steps work flawlessly for samples/dotnet_core_managed_gateway

However my application still gave the same error, it turns out the modules need to be added as a reference to the project before its built. I some how thought only need to be in the bin folder and will be picked up.

Thank you for your patience and assistance.
