### ISSUE TITLE
[V2] Function Modules not working on ARM devices

### ISSUE THREAD

**Issue by aribeironovaes** [Azure/iot-edge#485]
Creating this Issue so we can track the status of creating our binding for Function on ARM. 
Function release an image of their runtime for ARM, so we need to update our binding: 
https://hub.docker.com/r/microsoft/azure-functions-runtime/tags/

**Comment by whatevergeek** [comment]
were you able to pull the 2.0.0-stretch-arm32v7 runtime successfully?
after download attempt i got this:
Pulling repository docker.io/microsoft/azure-functions-runtime
Tag 2.0.0-stretch-arm32v7 not found in repository docker.io/microsoft/azure-functions-runtime

**Comment by aribeironovaes** [comment]
Hi @whatevergeek , 

Yes, I was able to use this image: FROM microsoft/azure-functions-runtime:2.0.0-stretch-arm32v7

And we were able to generate our binding (Edge Binding) and tested end2end on a raspberry pi. 

Stay tunned, on the next official release you will have binding as images that you can use. 

If you use just the runtime you won't get the edge binding (although you can start playing with it and have other type of binding and run it on edge)... Don't know if this would be usefull for your scenario. 

Regards, 

Angelo Ribeiro.

**Comment by aribeironovaes** [comment]
Hi Everybody, 

Just to update that now we have ARM version for Function binding. So, this should work! Let us know if you find any problem! 

Closing this issue now. 

Thanks!

Angelo Ribeiro.

**Comment by whatevergeek** [comment]
hi @aribeironovaes, 
thanks for the update
i'll try this later

best regards,
Paul

**Comment by whatevergeek** [comment]
yup, it works!
thanks for this :-D

**Comment by ChristianWeyer** [comment]
Will there be an update for GA? @aribeironovaes 
https://hub.docker.com/r/microsoft/azureiotedge-functions-binding/tags/

**Comment by aribeironovaes** [comment]
HI @ChristianWeyer , 

We have a new image for GA. Following this doc: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-function you should see the link for the new image. 

Let us know if you face any problem. 

Angelo Ribeiro

**Comment by krunallokhande** [comment]
@aribeironovaes Hi have you tested this arm32 image on the arm64 device. We are facing issues while executing this images on  Nvidia Jetson TX2 hardware with arm64 architecture.
The preview version was running on this device ... but we are facing issues with GA deployments.

**Comment by aribeironovaes** [comment]
HI @krunallokhande , 

Nops, we haven't. Since we don't officially support arm64 we haven't test. That said, I believe there is another thread regarding arm64 that you can follow to check the steps David Robson said will help you out. 

Thanks, 

Angelo Ribeiro.

**Comment by krunallokhande** [comment]
Thanks, @aribeironovaes,
I am following the other threads for arm64 support. But no clear fix is there for implementation. I tried using arm32 images, using moby-engine instead or docker cs but nothing seems to work. We will try to investigate it further and check if something works.
