### ISSUE TITLE
Can't recognize add/remove module event

### ISSUE THREAD

**Issue by hirosho** [Azure/iot-edge#489]
For IoT Edge SDK version 1.
Current GATEWAY_EVENT has only GATEWAY_MODULE_LIST_CHANGED in event_system.h so that user can't distinguish timing of 'Add' or 'Remove' with this event type notification.
Why don't you add two enumeration value, GATEWAY_MODULE_ADDED and GATEWAY_MODULE_REMOVED ?

**Comment by damonbarry** [comment]
The eventing system is experimental; it's not part of the stable API and hasn't really been updated since it was originally introduced. I suppose that LIST_CHANGED was good enough for what we were doing at the time.
