### ISSUE TITLE
/build.sh --enable-nodejs-binding --> error

### ISSUE THREAD

**Issue by cmehtarahul** [Azure/iot-edge#490]
I am getting error with
https://github.com/Azure/iot-edge/tree/master/v1/samples/nodejs_simple_sample

A) ./build_nodejs.sh [RAN SUCCESSFULL AND TOOK HOURS more than 9 hours with lan connection on Pi with noobs]
As per instruction I have now got NODE_INCLUDE and NODE_LIB environment variables
Which is the correct place to set these?

B) WHEN I RUN ./build.sh --enable-nodejs-binding
I get error saying set the  NODE_INCLUDE and NODE_LIB environment variables.
What is the correct place/location to set this on raspberry pi?

**Comment by damonbarry** [comment]
Tracking this issue in #491.
