### ISSUE TITLE
DeviceClient SendEventAsync overload removed

### ISSUE THREAD

**Issue by Jan-Olof** [Azure/iot-edge#492]
I install the module template " Microsoft.Azure.IoT.Edge.Module 1.2.0". From this I create a module. 

To send an event the template uses DeviceClient.SendEventAsync(string outputName, Message message) from Microsoft.Azure.Devices.Client.

It uses version "1.6.0-preview-001" of this package. When I update the package (Microsoft.Azure.Devices.Client) to a new (non-preview) version (1.6.1) this overload is gone and the code does not build.

So, how do I send the event to a named output (for example "output1") without this overload?

**Comment by damonbarry** [comment]
To use IoT Edge features please continue to use the preview version of the SDK (1.6.0-preview-001). The SDK received a minor version bump to 1.6.1 when some other non-IoT Edge features were introduced, but IoT Edge is still in public preview so you won't find it in the stable version.
