### ISSUE TITLE
[v2] iotedgectl fail

### ISSUE THREAD

**Issue by mingwei0314** [Azure/iot-edge#498]
I get an error message when I run iotedgectl setup or start command.
![image](https://user-images.githubusercontent.com/13758955/35490896-bcf23752-04dd-11e8-9816-e56f76a90975.png)

And I found the root cause may be is pypiwin32 222 versions.
(https://pypi.python.org/pypi/pypiwin32)
If I return to the previous version pypiwin32 219, there is no any issue happened.

**Comment by darobs** [comment]
Hello @mingwei0314 

azure-iot-edge-runtime-ctl 1.0.0rc19 was released recently (Jan 26 2018) which addresses this issue by ensuring the correct pypiwin32 package is installed.

Would you please try the following?

To get the latest bits execute:
$> pip install -U azure-iot-edge-runtime-ctl
Check installed version:
$> iotedgectl --version
iotedgectl 1.0.0rc19

And attempt the command again?

I think this will address the problem.

Thanks,

**Comment by mingwei0314** [comment]
iotedgectl 1.0.0rc19 is work.
Thanks
