### ISSUE TITLE
[V2] Module twin update on a module with no SetDesiredPropertyUpdate callback causes modules to be remove

### ISSUE THREAD

**Issue by leeprtc** [Azure/iot-edge#504]
What should be the behavior if you do a module twin update but the module did not set a SetDesiredPropertyUpdate callback?

In my edge device, I have two modules (one to generate data and the other to do something with the data). Routes are set up so output of module1 is sent to input of module2. Output of module2 is sent to IoT Hub. If I do a module twin update on module2 and did not set a SetDesiredPropertyUpdate callback in module2, I'm seeing edgehub, module1, and module2 are stopped and then edgehub is restarted again. 

Should a missing SetDesiredPropertyUpdate callback take down all the modules?

**Comment by darobs** [comment]
This is unexpected behavior.  If you have no callback set, then updating the desired property of a module should be a no-op.  Nothing should happen, and we certainly should not reset any module.

A module shouldn't need to use a Twin if it doesn't want to.

I will investigate and reply with any questions if I'm having trouble reproducing it.

**Comment by leeprtc** [comment]
I think this issue may be an user error on my part. I was looking at IoT Edge deployments and my last deployment remove all the modules. I forgot about this and did not delete the deployment. Hence, the module being reset is probably because of my deployment.

I deleted all my deployments and now, I cannot repro this issue anymore.

**Comment by mrohera** [comment]
Thank you for your response. I am closing this issue but feel free to come with more feedback or open up a new issue.
