### ISSUE TITLE
[V1] Java_Home not defined on bindings/java/CMakeLists.txt on Debian

### ISSUE THREAD

**Issue by malichishti** [Azure/iot-edge#506]
Hi,

I'm using [this](http://blog.faister.com/2017/09/04/building-docker-container-with-azure-iot-edge-cross-compiled-libraries-for-raspberry-pi/) article to compile V1 Gateway for Raspberry Pi.

As dicussed [here](https://github.com/Azure/iot-edge/issues/483), it now works fine for .Net Core Modules but not for Java. I'm now trying to build Java bindings as below:
`./tools/build.sh  --enable-dotnet-core-binding  --enable-java-binding  --disable-native-remote-modules  --toolchain-file ./toolchain-rpi.cmake`

But java bindings fail:
![image](https://user-images.githubusercontent.com/17155996/35792603-1aec607a-0aa2-11e8-9c0f-80fe029cd671.png)

You can see that JAVA_Home is defined in /etc/environment

Is there something i'm supposed to do differently?
Regards,
Ali

**Comment by darobs** [comment]
You aren't the only person who seems to be having trouble with environment variables and CMake.

I haven't been able to repro this - I'm running cmake version 3.7.2, which version are you running?

**Comment by darobs** [comment]
Also, which release of Debian? I'm currently on Raspbian GNU/Linux 9.3 (stretch).

**Comment by malichishti** [comment]
I used `cmake -E environment` and found out that it was not being passed. I defined it in terminal like `export JAVA_HOME="/usr/lib/jvm/java-8-oracle"` and it worked. 
However, now i get following error:
![image](https://user-images.githubusercontent.com/17155996/35834759-391f72ba-0b2b-11e8-8bb2-01dfd2bb5869.png)

CMake and OS version below:
![image](https://user-images.githubusercontent.com/17155996/35834805-72b48236-0b2b-11e8-9317-790360d2b83e.png)

**Comment by malichishti** [comment]
BTW i'm using `git clone --branch 2017-08-21 https://github.com/Azure/iot-edge.git /iot-edge`

**Comment by darobs** [comment]
That looks like an incompatibility between the target architecture of your Java SDK and the target architecture of the build - something that would be happen if you're compiling the gateway for ARM32 and the Java SDK is ARM64.

**Comment by darobs** [comment]
Is it possible to use a 32-bit version of Java?

**Comment by malichishti** [comment]
I tried, but it doesn't let me install it on arm64.

I'm using [this ](https://hub.docker.com/r/aziotbld/raspberrypi-c/ )image to cross compile.

**Comment by malichishti** [comment]
Any ideas on how to cross compile V1 gateway along with dotnetcore and java bindings for Raspberry Pi?

**Comment by darobs** [comment]
I don't have a good story for you here. Right now, dotnet core only supports 32 bit executables. We could build the Java or the dotnet core module as an out of process module. Our current tooling would mean you need to have 2 copies of the project, one to build the 64 bit executables to connect to Java, and one to build the 32 bit executables to connect to dotnet core.

**Comment by malichishti** [comment]
So is it correct to say that currently there is no way to use a dotnetcore and a java module together on a Raspberry Pi deployment?

**Comment by malichishti** [comment]
Since the issue in the title has been resolved with the help provided, i will log the subsequent issue separately and close this one. Thank you.
