### ISSUE TITLE
Is it possible to send cloud 2 device message to a specific module. [question]

### ISSUE THREAD

**Issue by ddimitrov90** [Azure/iot-edge#508]
I find the edge device as a great concept, but didn't used the first version, so I'm wondering on this:

When I create a new edge module and use the environment variable for the connection string, the device client is tied to the deviceId and moduleId.
Is it possible to target the exact module with a device message by using the 
ServiceClient.SendEventAsync("deviceId", message) somehow? 

Otherwise I'll have to start a "router" module that will listen for  all messages to the edge device using the Device Connection string and then open another module device client using the environment variable in order to send the messages to the corresponding module. 

Would love to receive some feedback, if I'm missing something :/

**Comment by mrohera** [comment]
We do not have plans to support Cloud to Module messages directly which is what I believe you are asking for when you say you would like to use ServiceClient.SendEventAsync() to target a module.

I would suggest you look at [Direct Methods (DM)](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods) as a means to target a module. Using direct methods your code in your service can get feedback either in terms of the response from the targeted module or if the module was offline a timeout and so on. If you were to use DMs, you do not have to implement a router and really nor should you.

Please let us know if you have more questions or follow up, otherwise feel free to close this issue.

**Comment by ddimitrov90** [comment]
hey, sorry to bother again, i don't wanna reopen the issue nor open another, just want to ask a very simple question regarding the same topic.

Direct Methods seem just what I need, but the environment variable that holds the connection string EdgeHubConnectionString is very specific to the module and following [this](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-direct-methods) article there is a difference between the two connection strings.

EdgeHubConnectionString : HostName=iothubname.azure-devices.net;GatewayHostName=machinename;DeviceId=deviceid;ModuleId=mymodule;SharedAccessKey=accesskey1
The Device connection string does not have GateWayHostName and ModuleId and has different access key. 

The result is if I use EdgeHubConnectionString to initialize my DeviceClient and register for the direct method, it is not invoked ever.
If I use the Device connection string (by hardcoding it), then the method is called as expected.

If this is the expected behavior, is it possible to obtain the device connection string dynamically from the environment, because the two strings are pretty similar, but the access keys are different.

Thanks for the help :)

**Comment by mrohera** [comment]
I can see the disconnect that you are experiencing.

Since you are following [Direct Methods using C#](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-direct-methods), in your CallMethodOnDevice code I would suggest you do the following to send a DM to a module.
1) In your csproj file please use this SDK version
	<PackageReference Include="Microsoft.Azure.Devices" Version="1.5.0-preview-001" />

2) Modify your code in Program.cs 
	Use a different overloaded method to pass in the module id
	var response = await serviceClient.InvokeDeviceMethodAsync(<your-device-id-string>, <your-module-id-string>, methodInvocation);

The portal lacks the UI to target a specific module. I have filed a ticket for addressing this so this should be addressed soon. Therefore currently only the preview C# SDK release has the requisite support for targeting a module. Other languages will be on boarded in the next few weeks.

Let me know if this helps or if you have more questions. I will reopen this case so as to say visible.

**Comment by ddimitrov90** [comment]
Successfully implemented it and works as expected, there is just one small issue.
According to the docs here - https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#other-limits , the Maximum direct method payload size is 128 KB, but when I try to send around 30 kilobytes with this code, i get the following exception:

```csharp
var methodInvocation = new CloudToDeviceMethod("UpdateAvailable") { ResponseTimeout = TimeSpan.FromSeconds(5) };
            var data = new
            {
                Firmware = firmware
            };
            methodInvocation.SetPayloadJson(JsonConvert.SerializeObject(data));
            await this.serviceClient.InvokeDeviceMethodAsync(deviceId, "softwareUpdate", methodInvocation);
```

```
System.ArgumentException: '{"Message":"{\"errorCode\":400004,\"trackingId\":\"79938ffb17144c0283777b7ab0fec2ca-G:11-TimeStamp:02/16/2018 11:28:04\",\"message\":\"payload size should be less than 8192 bytes.\",\"timestampUtc\":\"2018-02-16T11:28:04.694868Z\"}","ExceptionMessage":""}'
```

thanks for the help :)

**Comment by mrohera** [comment]
Thank you for reporting this discrepancy, the limits described in the documentation are accurate. After checking with the IoT Hub cloud service there was an apparent misconfiguration which is in the process of bring resolved right away. Likely the patch will roll out in the next 24 hours. Please retry this later and let us know if this has been fixed.

The dates for IoT Edge GA are still being finalized, please check back with us in a month or so.

**Comment by ddimitrov90** [comment]
Thank you for the fast reaction, the message is sent and received on the device successfully, however an exception is being thrown right after the call to InvokeDeviceMethodAsync - FileNotFoundException, that you are searching for System.Net.Http.Formatting.Extension 5.2.3, so I had to manually install it in my project.
This was added to my packages.config file
```
  <package id="System.Net.Http" version="2.0.20126.16343" targetFramework="net461" />
  <package id="System.Net.Http.Formatting.Extension" version="5.2.3.0" targetFramework="net461" />
```

This is just a side note, but I don't know if this is a bug at my side or at yours or just some missing dependency :)

**Comment by mrohera** [comment]
- I looked at [https://github.com/Azure/azure-iot-sdk-csharp/blob/master/service/Microsoft.Azure.Devices/AmqpServiceClient.cs](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/service/Microsoft.Azure.Devices/AmqpServiceClient.cs) and sure enough I can see that  System.Net.Http is being used.

- Here is the Nuspec file, and I can see that the packages you called out are not included. [https://github.com/Azure/azure-iot-sdk-csharp/blob/master/service/NuGet/Microsoft.Azure.Devices.nuspec](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/service/NuGet/Microsoft.Azure.Devices.nuspec
)

- I would suggest filing a issue here [https://github.com/Azure/azure-iot-sdk-csharp](https://github.com/Azure/azure-iot-sdk-csharp)  and report your observation maybe there is something that needs to addressed for the type of DotNet framework you are using to build your application.

**Comment by rizwaans** [comment]
hey @ddimitrov90  can you please help me with the below request
I'm trying to invoke a method on the device module without having to provide any timeout number. my current code is as below
var methodInvocation = new CloudToDeviceMethod("invokesenddicomimages") { ResponseTimeout = TimeSpan.FromSeconds(300) };
 I know if don't specify the timeout it will be defaulted to 30 seconds but I just want to invoke the method and don't bother about the response.

**Comment by ddimitrov90** [comment]
```cshapr
var methodInvocation = new CloudToDeviceMethod("invokesenddicomimages");
methodInvocation.SetPayloadJson(JsonConvert.SerializeObject(payload));
await this.serviceClient.InvokeDeviceMethodAsync(device.Id, "ModuleName", methodInvocation);
```

**Comment by rizwaans** [comment]
@ddimitrov90 hey thanks for the response, but the code above will default the timeout to 30 seconds. correct me if I'm wrong. All I want is to just invoke the method with out any timeout or is there a way to extend the timeout to more than 300 seconds?
my method is downloading some images which takes more than 300 seconds.
