### ISSUE TITLE
[V2] What Message properties can modules expect to be set by IoT Edge?

### ISSUE THREAD

**Issue by leeprtc** [Azure/iot-edge#512]
When receiving a message in a module, which of the properties in Message will the IoT Edge platform set? 

I know some of the properties are set by the sender of the message. I'm not interested in these properties. Instead, I'm more interested in the properties that are under the control of IoT Edge platform.

When dumping the values for the properties in a message sent to a module, I see ConnectionDeviceId, ConnectionModuleId, and InputName properties are set. Are there other properties that IoT Edge platform will set in a message?

**Comment by varunpuranik** [comment]
ConnectionDeviceId, ConnectionModuleId and InputName are the 3 IoT Edge specific properties set by the Edge runtime. Other system properties (such as CorrelationId, MessageSchema, ContentType, ContentEncoding, etc.) will be forwarded by the Edge runtime (they are expected to be set by the sender module). 
Are you looking for any specific properties? If so, what are they, and what is your use case?

**Comment by leeprtc** [comment]
I was looking at SequenceNumber and EnqueuedTimeUtc properties.

The comment for SequenceNumber has "[Required]" but I noticed it was not set so was just wondering.

Likewise, the comment for EnqueuedTimeUtc mentioned "Time when the message was received by the server". I was not sure if the server mentioned here refer to edgeHub.

No particular use case but just want to know which of the message properties will be set by the Edge runtime.

**Comment by varunpuranik** [comment]
Both SequenceNumber and EnqueuedTimeUtc are applicable only to [cloud-to-device messages](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-c2d) . So the EdgeHub will not set those for module to module messages.

**Comment by leeprtc** [comment]
Thanks for the info.
