### ISSUE TITLE
[V2] SDK only supports RPI on ARM?

### ISSUE THREAD

**Issue by rmr** [Azure/iot-edge#525]
I think I have found out why my system runs strangely. It seems the examples I have run and installed on ClearFog Pro A38x (ARMv7) is not recognized because I have installed Armbian (before ubuntu based, now debian), NOT Raspbian. I have tried to run the JS examples, but it wants to use the x86-64 binaries because of the Debian keyword.

How do I overwrite this? Why is it dependent on the Rasbian distribution, and not the architecture description?

**Comment by rmr** [comment]
Great. The temperature sample works on Raspbian, on a RPI. What do I need to change to get the iot edge to run on ARM linux systems other than Raspbian?

Please...

**Comment by rmr** [comment]
What a hack. The samples now work (iot edge git samples JS) now works on ARMbian. The temperature sample (docker), however, does not. What on the RPI is used by the temperature sample that is board specific?

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by myagley** [comment]
Hello. I would like to help but am having trouble understanding your issue. Can you please be more specific about which samples you are attempting to run and what is not working properly? Do you have any error output or logs?

Thanks!

**Comment by rmr** [comment]
My issue is that when I run Armbian on the ClearFog Pro board, the edge runtime acts differently than when running Raspian on the Pi board. When I changed the ID to raspbian (as shown above), the Armbian no longer disconnects from the hub. Furthermore, the JS sample runs correctly on the Armbian distribution when I change the ID to Raspian.

I have seen that the ID is used somehow to determine what binaries to use. So the only ARM based system which runs correctly is Raspbian. All others, debian, ubuntu, (regardless if they are ARM based) install x86-64 binaries (wrt the node binaries).

**Comment by rmr** [comment]
Lastly, the microsoft/azureiotedge-simulated-temperature-sensor:1.0-preview runs perfect on the RPI. It hangs, however, on the Armbian (ClearFog) board (even though I have the ID changed to raspbian). There seems to be a board specific usage (RPI) in the simulated sensor.

_Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation timeout expired.) ---> System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass79_0.<ApplyTimeout>b__2(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_1(Object obj)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimulatedTemperatureSensor.Program.<MainAsync>d__4.MoveNext() in /opt/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 60
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SimulatedTemperatureSensor.Program.Main() in /opt/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 27_

**Comment by aribeironovaes** [comment]
Hi @rmr, 
Can you enable Debug logs and share with us (from the EdgeAgen and Edge Hub)? That would be better to  debug the problem you are having. 

Also, can you clarify what you mean by "the JS sample" ?

Thanks, 

Angelo Ribeiro.

**Comment by rmr** [comment]
The JS sample is
https://github.com/Azure-Samples/iot-edge-samples/tree/master/js/simple

This is the disconnect.
https://github.com/Azure/iot-edge/issues/519

This the temperature sample
https://github.com/Azure/iot-edge/issues/514

**Comment by aribeironovaes** [comment]
Hi @rmr , 

I think there are some confusions on this issue. The JS Sample you posted above is a Gateway V1 sample. 
Are you trying to run a gateway V1 sample and make it to work with Gateway V2?

Also, how is this issue different from the one you already reported on #514? 
Shall we track this issue in a single place?

**Comment by rmr** [comment]
Ok. I am not sure of what is V2 and what is V1. The source code in github has a v1, but many discussion threads refer to V1 and V2.. I was under the impression that V1 referred to the first customer preview, which was not open· But now as I write it, it really doesn't make sense... hehe.

I honestly don't know what version the simple JS sample is. I just followed the tutorial. I assume npm uses the correct version(s).

Yes, the issues i have opened (and closed) all seem to be the same issue. Where the central problem seems to revolve around the runtime preferring RPI and Raspbian.

**Comment by damonbarry** [comment]
Closing this issue. Please reopen if you think there's more to investigate...
