### ISSUE TITLE
v1 dotnet core modules support on macOS

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/iot-edge#530]
Is it dotnet core modules supported in macOS for iot-edge v1? The dotnet core bindings CMakeLists.txt([1](https://github.com/Azure/iot-edge/blob/50b0526a4cdbc362b58360a7ef53ed84ef4662d4/v1/bindings/dotnetcore/CMakeLists.txt#L6)) doesn't have entry for macOS.

**Comment by avranju** [comment]
.NET core bindings for macOS is not supported for v1 at this time unfortunately. It maybe possible to get it to work with a little investigation but this is not a priority for us right now.

**Comment by avranju** [comment]
cc @damonbarry

**Comment by damonbarry** [comment]
A few weeks back I tried to get .NET Core modules working on macOS. I had to make a few changes to the code; you can see my changes on my [fork](https://github.com/Azure/iot-edge/compare/master...damonbarry:dotnet-core-macos).

I couldn't quite get it to work. Here's what I was doing:

```
cd v1/
OPENSSL_ROOT_DIR=/usr/local/opt/openssl \
tools/build.sh \
  --disable-ble-module \
  --enable-dotnet-core-binding
cd build
LD_LIBRARY_PATH=/iot-edge/v1/build/samples/dotnet_core_module_sample \
samples/dotnet_core_module_sample/dotnet_core_module_sample \
  ../samples/dotnet_core_module_sample/src/dotnet_core_module_sample_lin.json
```

I was also adding this block to `../samples/dotnet_core_module_sample/src/dotnet_core_module_sample_lin.json`:

```json
    "loaders": [
        {
            "type": "dotnetcore",
            "name": "dotnetcore",
            "configuration": {
                "binding.path": "/iot-edge/v1/build/samples/dotnet_core_module_sample/libdotnetcore.dylib",
                "binding.coreclrpath": "/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.6/libcoreclr.dylib",
                "binding.trustedplatformassemblieslocation": "/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.6"
            }
        }
    ],
```

...and the output:

```
Error: Time:Tue Feb 27 18:13:01 2018 File:/Users/damonb/iot-edge/v1/bindings/dotnetcore/src/dotnetcore.cpp Func:DotNetCore_Create Line:188 Failed to create Create Delegate.
Error: Time:Tue Feb 27 18:13:01 2018 File:/iot-edge/v1/core/src/gateway_internal.c Func:gateway_addmodule_internal Line:446 Module_Create failed.
Error: Time:Tue Feb 27 18:13:01 2018 File:/iot-edge/v1/core/src/gateway_createfromjson.c Func:Gateway_CreateFromJson Line:78 Failed to create gateway using lower level library.
failed to create the gateway from JSON
```

Sorry I don't have better news. I haven't had time to resolve this, but I suspect it's close to working.

**Comment by damonbarry** [comment]
@kiranpradeep With a little effort I got `dotnet_core_module_sample` working on macOS. I pushed the changes to my fork. See the [README](https://github.com/damonbarry/azure-iot-gateway-sdk/tree/dotnet-core-macos/v1/samples/dotnet_core_module_sample) file there and let me know if my changes work for you.
