### ISSUE TITLE
IOT-Edge hub - back off state

### ISSUE THREAD

**Issue by GarthOlivier** [Azure/iot-edge#531]
I have run into issue where the edgeHub not starting the container in docker 
This results in hub having "backoff" status 128
This seems to be due to containers be used by another process.
I also noticed HNS failed with error file being used by another process.

I cannot even install sample example with tempSensor from documentation.

I have created new EdgeDevice and did factory reset of docker.
This has not solved the issue.

What is the process of resolving edgeHub that shows in BackOff status.

Thanks

Garth

**Comment by avranju** [comment]
Could you copy/paste the output of `docker logs edgeAgent` please?

**Comment by GarthOlivier** [comment]
Sorry, I no longer have them.
I solved the issue by rebuilding dev machine from clean windows 10 image.

**Comment by varunpuranik** [comment]
We haven't seen any other reports of such behavior on the Edge runtime. So I will go ahead and close this issue. If you are able to repro the problem, please reopen the issue and provide us the logs for debugging. 
Thanks.

**Comment by GarthOlivier** [comment]
Thanks will do.
Should have copied the logs before I rebuilt the machine.

Thanks

Garth Olivier

**Comment by MarijnCatthoor** [comment]
@varunpuranik I just encountered the same issue on my Windows 10 development machine. Hereby my edgeAgent log file.

[edgeagent.log](https://github.com/Azure/iot-edge/files/1870834/edgeagent.log)

**Comment by GarthOlivier** [comment]
Looks very similar to issue I had.
The only way I fixed was to rebuild development machine from clean windows image.
I hope you find a better way

Garth

**Comment by svencowart** [comment]
I am experiencing the same issue and I have the log output for the edgeAgent:
[edgeAgent.log](https://github.com/Azure/iot-edge/files/1896237/edgeAgent.log)

**Comment by GarthOlivier** [comment]
You may want to open new issue as this one is closed .... not sure they are getting notifications
Reference this issue in new one

Cheers

Garth

**Comment by svencowart** [comment]
I actually just resolved the problem by simply restarting docker on the windows machine.  Posting this for reference for anyone else that might run into the same issue.

**Comment by Vishwanath-Reddy-M** [comment]
Hi svencowart,

Yes, restarting docker on the windows or Linux machine resolved problem.

command for linux :-- 

sudo systemctl restart docker
sudo systemctl restart iotedge


Regards,
vishwa
