### ISSUE TITLE
Runtime doesn't start modules after wakes up from sleep

### ISSUE THREAD

**Issue by jonbgallant** [Azure/iot-edge#534]
When the computer wakes up it looks like all the modules are running, but no data is being sent.  You have to do a `restart` to get the modules to send data again.

To repro, you should just run the runtime, let computer go to sleep, then see edge activity.

**Comment by varunpuranik** [comment]
Seems like a bug, we will investigate.

**Comment by varunpuranik** [comment]
@jonbgallant I tried reproing this on my Mac - but I wasn't able to get a repro. The messages continued to flow. So can you please provide some more info -
- Did you have a consistent repro? 
- Was there anything special about the modules sending/receiving events?
- What version of EdgeHub you using?
Thanks.

**Comment by jonbgallant** [comment]
Closing. Will reopen if I get further reports.
