### ISSUE TITLE
Can't pull docker image with no errors

### ISSUE THREAD

**Issue by melzoghbi** [Azure/iot-edge#538]
Hi,
I am trying to pull a docker image in my ACR as in this [ml module](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-machine-learning) article. The iot is not able to pull my image without giving me any errors.

```
2018-03-12 16:08:10.087 +00:00 [INF] - Executing command: "Command Group: (
  [docker pull mlcrpacrfe3601798489.azurecr.io/machinelearningmodule:2]
  [docker create --name machinelearningmodule mlcrpacrfe3601798489.azurecr.io/machinelearningmodule:2]
  [docker start machinelearningmodule]
)"
2018-03-12 16:08:10.097 +00:00 [INF] - Executing command: "docker pull mlcrpacrfe3601798489.azurecr.io/machinelearningmodule:2"
```

I checked the config.json and the container username and password is correct. i do have other container images that are running with no issues but this ML module is showing as "Pending Deployment" after i deployed a new docker image for it.

Here is some of the troubleshooting steps i have done:

1) Check registry info in config.json, no issues the credentials are set  properly:

```
 "registries": [
        {
          "address": "MYREGISTRY.azurecr.io",
          "password": "MYPASSWORD",
          "username": "MYUSERNAME"
        }
```

2) The iot edge is not able to pull my docker image, since i don't see a container created of my docker image: docker ps -a

3) I stopped and restarted the iotedge multiple times but no luck to get the edge pull my docker image.

Any help is appreciated?

Thanks a lot.

**Comment by varunpuranik** [comment]
Your steps seem fine. Can you try the following steps - 
- The registry username/password should be the Shared access username and password (not your account username and password) - in Azure Portal, go to Your Registry -> Access keys 
- If that seems fine, then try to look at the EdgeAgent logs, to see if they give you any more information.
$>docker logs -f edgeAgent
- If that doesn't help either, then try to do a docker login to your registry with that username and password, and manually do a docker pull on the image. 
If that last step works, then please copy paste relevant the edgeAgent logs here, to givs us more context to debug the issue.

**Comment by melzoghbi** [comment]
I resolved this issue by executing set of commands to get up to date packages in step 6:

https://medium.com/@melzoghbi/troubleshooting-pending-deployment-status-in-iot-edge-cad7232b385a

Thanks @varunpuranik
