### ISSUE TITLE
[V2] Will IoT Edge only work with Python 2.x?

### ISSUE THREAD

**Issue by leeprtc** [Azure/iot-edge#539]
The documentation for IoT Edge lists Python 2.7 as a prerequisite.

I want to understand what is the Python requirements. Is there a hard dependency on Python 2.x or will IoT Edge also work with Python 3.x?

**Comment by jonbgallant** [comment]
Where do you see it say only 2.7?  It runs on 2.7 or 3.6.

Looks like a doc issue.

@kgremban

**Comment by leeprtc** [comment]
The QuickStart for Windows docs, https://docs.microsoft.com/en-us/azure/iot-edge/quickstart.

**Comment by aribeironovaes** [comment]
Thanks @jonbgallant and @leeprtc , 

If you think this is an issue with the document, can you open an issue on the doc github? 
https://github.com/MicrosoftDocs/azure-docs/issues?utf8=%E2%9C%93&q=%2217d9481c-a75b-bbfd-1f9a-76fc3d6b2930%22&in=body

I believe Jon is right, I don't think we have a hard dependency on python 2.7, so they probably should put on the document that 2.7 or higher, or put a list of version that we know works. 

Let me know if you need anything else on this issue so we can close. 

Angelo Ribeiro.

**Comment by leeprtc** [comment]
I'll filed an issue on the doc github to clarify the Python requirements.
