### ISSUE TITLE
[V1] free(): invalid pointer: 0xa6f3ac38

### ISSUE THREAD

**Issue by Zuendelmeister** [Azure/iot-edge#541]
Hi all,

I'm trying something fancy and it just does not work.
I'm trying to run Edge_V1 in a docker container.
This works like a charm on my windows pc. But I got some problems while running the container on an arm device.
The container starts (so base image and code should be ok), the modules send a few messages to each other and then this strange error occurs:

*** Error in `start_gateway': free(): invalid pointer: 0xa6f3ac38 ***
gateway successfully created from JSON
gateway shall run until ENTER is pressed
Aborted (core dumped)
Terminated

Any ideas what that could have coursed? 

Thanks as always.
Best regards,
Zudendelmeister

**Comment by aribeironovaes** [comment]
Hi @Zuendelmeister , 
Thanks for reporting this. We will investigate. 
Can you please give us some more info? 
1-Can you share the docker file and procedure to create your docker image? 
2-What are the sample that you are running on your container? 
3-Can you share your gateway configuration file? 

Thanks, 

Angelo Ribeiro.

**Comment by Zuendelmeister** [comment]
Hi @aribeironovaes 
its hard to get this reproducable for you. My hope is that this is due to an old version of Edge_V1 which I'm using.
At the moment I try to use your nuget package Microsoft.Azure.Devices.Gateway.Module.NetStandard to work on arm. I already notices that there are some missing librarys after building the project. I'll get back to you when I got this to work.

Best regards,
Zuendelmeister

**Comment by Zuendelmeister** [comment]
Hi again,

I finally got a gateway to work with the Nuget Package. Unfortunately this didn't change the outcome.
If I start the Gateway on my arm machine every thing is fine. If I start it in the container I still get the error. I'm pretty shure it has to do something with the messaging! I took the links out of the json config file => Now the error doesn't appear.
Here is my gateway code:

> static void Main(string[] args)
        {
            if (args.Length < 1 || !File.Exists(args[0]))
            {
                Console.Error.WriteLine("Usage: managed-gateway <<path to json>>");
            }
            else
            {
            var json_path = args[0];
            Console.WriteLine("New start");
            IntPtr gateway = GatewayInterop.CreateFromJson(json_path);
            Console.WriteLine(".NET Core Gateway is running. Press return to quit.");
            Console.ReadLine();
            GatewayInterop.Destroy(gateway);
            }
        }

I built everything for arm like this:

> dotnet clean && dotnet restore && dotnet build -r ubuntu.16.04-arm && dotnet publish -r ubuntu.16.04-arm

As baseimage in my dockerfile I use microsoft/dotnet:2.0-runtime-stretch-arm32v7. Also I install libunwind8 libunwind8-dev libcurl4-openssl-dev libssl-dev and copy the libcrypto.so.1.0.0 and libssl.so.1.0.0 to /lib/arm-linux-gnueabihf.

Do you have any idea where the problem could be or what I could try?
Thanks again.

Best regards,
Zuendelmeister

**Comment by Zuendelmeister** [comment]
It seems like this is a problem with my ConcurrentQueue and docker. So this is not due to Edge_V1.
