### ISSUE TITLE
[V2] How do I remove/delete an Azure IoT Edge module from the Azure IoT Hub portal?

### ISSUE THREAD

**Issue by HenrikBach1** [Azure/iot-edge#544]
Hi,

How do I remove/delete an Azure IoT Edge module from the Azure IoT Hub portal?

I cannot find this functionality in the portal. Isn't that a valid use case?

/Henrik

**Comment by aribeironovaes** [comment]
Hi @HenrikBach1 , 

When you choose Add Module you will get a JSON file with a deployment. Have you tried to remove the module you want to remove? 

Are you trying to remove a runtime module? (EdgeHub or EdgeAgent) or are you trying to remove a specific custom module you have added?

Let us know, 

Angelo.

**Comment by HenrikBach1** [comment]
Hi @aribeironovaes,

1. I haven't noticed whether I got an JSON file, when I used the "Set Modules" functionality in the "Device Details" blade.
3. If I got an JSON file from item 1 - How should I then use that file to delete the module in question?
2. However, I am trying, or rather want, to remove the specific custom tempSensor module from my device listed on the "Device Details" blade.

Thank you.

/Henrik

**Comment by jonbgallant** [comment]
1. Click on device
1. Click on Set Modules button
![image](https://user-images.githubusercontent.com/2163001/37598399-121b5280-2bbd-11e8-9812-2090c662e6d4.png)

1. Check checkbox next to module
1. Click Delete Button

![image](https://user-images.githubusercontent.com/2163001/37598410-1d35f80a-2bbd-11e8-93ed-138356ff34b8.png)

**Comment by HenrikBach1** [comment]
Yes, it works. Closing issue.
/Henrik
