### ISSUE TITLE
[V2] Remove the Azure IoT edge deployment

### ISSUE THREAD

**Issue by VitorX** [Azure/iot-edge#547]
Can I modify/remove the Azure IoT edge deployment at present?

**Comment by aribeironovaes** [comment]
HI @VitorX , 

Can you check issue: https://github.com/Azure/iot-edge/issues/544 and let us know if that covers your question? 

If not, what you mean by at present? (not using the portal? )

Let us know, 

Angelo Ribeiro.

**Comment by VitorX** [comment]
Hi @aribeironovaes 

The issue : [#544](https://github.com/Azure/iot-edge/issues/544) is different from mine. There are two ways to deploy modules to the Azure IoT edge. First is deploy the modules directly through **SetModule** button on the portal. And second way is through the Azure IoT edge deployment which can deploy the modules to the fleets of edge devices. 

**The question is after I deploy the modules through the second way, can I delete that deployment using the portal?**  

I can see that deployment on the detail detail page and on the bottom of that page, there are three tabs _Deployed Modules, IoT Edge Hub Connections and Deployments_ like figure below:
![untitled1](https://user-images.githubusercontent.com/12635993/37631488-e432c4da-2c24-11e8-9056-9f2d3fa7ad5b.png)

**Comment by varunpuranik** [comment]
Yes, you can delete deployments - In Azure Portal, go to your IoT Hub -> IoT Edge -> IoT Edge Deployments, then select your deployment, and the Delete button at the top should become active. 
See here for more details - https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-monitor#delete-a-deployment

The deployment can be updated as well - if you click on the deployment, it will open a form with the details. You can update them and hit Save.

**Comment by damonbarry** [comment]
Closing since this appears to have been answered. Please reopen if it isn't.
