### ISSUE TITLE
[V2] Communication between containers

### ISSUE THREAD

**Issue by ddimitrov90** [Azure/iot-edge#548]
Hello,

I'd like to make an HTTP call from one container to another. This should be pretty straight forward - the server container has port 80 exposed in the Dockerfile and I tried using the "Links" command from the documentation for the client container:
```json
{
  "HostConfig": {
   	"Links": [
		"ServerContainer : serverAlias"
	]
}
```

However, when I attach to the client container, the /etc/hosts file is as follows:
```
root@d00ad8476f8c:/app# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.18.0.6	d00ad8476f8c
```
The IP information about the Server Module is not present.
It should be something like this:
```
172.17.0.15 Servercontaienr 37f174130f75 serverAlias
```

The **Links** property should be taken into account, because when I initially setup the two container images on my device, I got an error that the ServerContainer module was not found when trying to link it, which is correct because it was not present at the moment. The next try to init my ClientModule was successful.

Is this the correct way for communication and is this a bug or I'm missing something :/

**Comment by avranju** [comment]
All the containers instantiated by the Edge Runtime for the modules are part of a custom bridge network in Docker. You should be able to directly connect between containers without needing to link them by using the module names as the host name. If you have a module named "web1" that hosts a web server on port 80 for example, then you should be able to connect to it from another Edge module by using the URL `http://web1`.

**Comment by sovanny** [comment]
I am experiencing a similar problem. I can ping/send POST request via bash/curl, but when I try to send a POST request via the Program/module/csharp, I get "System.Net.Http.CurlException: Couldn't resolve host name". Why is that and how can I solve it?

**Comment by sovanny** [comment]
I had mixed lowercase and uppercase, so that was the problem. Thank you!
