### ISSUE TITLE
[V2]Named pipes require absolute path

### ISSUE THREAD

**Issue by MarijnCatthoor** [Azure/iot-edge#550]
I'm running Windows Server 1709 with Docker EE version 17.06
`PS C:\ProgramData\azure-iot-edge\config> docker version
Client:
 Version:       17.06.2-ee-7
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    925df35
 Built: Fri Mar 16 22:29:37 2018
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-7
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   925df35
  Built:        Fri Mar 16 22:39:05 2018
  OS/Arch:      windows/amd64
  Experimental: true`

Whenever I'm trying to run the iotedge runtime, I'm getting the error message that the named pipe referencing the docker_engine cannot be mounted as it has to be an absolute path:

`INFO: Checking if image exists locally: microsoft/azureiotedge-agent:1.0-preview
INFO: Image exists locally. Id: sha256:642bd8dffa2084ed9e3170000a2fa9e8c39fae43afb9d53de3ee45d5115ae9d5
INFO: Creating network: azure-iot-edge
INFO: Executing docker create microsoft/azureiotedge-agent:1.0-preview  name: edgeAgent  detach: True network: azure-iot-edge
ERROR: Docker create failed for image: microsoft/azureiotedge-agent:1.0-preview
400 Client Error: Bad Request ("invalid mount config for type "npipe": invalid mount path: '\\.\pipe\docker_engine' mount path must be absolute")
ERROR: Exiting with errors. Return code: 1
ERROR: Exiting with errors. Return code: 1`

Any idea how I can fix this?

**Comment by veyalla** [comment]
@MarijnCatthoor 
Docker EE version 17.06 doesn't have the required named pipe support that IoT Edge depends on. 

Can you try the EE Preview per these instructions: [https://docs.docker.com/install/windows/ee-preview/#windows-server-1709](https://docs.docker.com/install/windows/ee-preview/#windows-server-1709)

**Comment by MarijnCatthoor** [comment]
@veyalla thanks. Adding the -verbose flag to that command revealed me that I had to enable Nested Virtualization. Once that was enabled, everything started to work.
