### ISSUE TITLE
MQTT/HTTP protocol ingester module ?

### ISSUE THREAD

**Issue by girishkumarbk** [Azure/iot-edge#551]
Hi,

Is there a MQTT/HTTP protocol module in the IoT edge code (v1) that terminates the Device telemetry data via MQTT/HTTP in the IoT edge ? 

I'm looking for MQTT/HTTP module similar in function like ble-gateway-device interaction with IoT-edge to IoT hub as described here in this example

https://github.com/Azure/iot-edge/blob/master/v1/samples/ble_gateway/iot-hub-iot-edge-physical-device.md

but my device is MQTT/HTTP capable hence I need a protocol terminator at Iot Edge.

Any pointers to build and load the same would be of great help.  

Thanks,
/Girish BK

**Comment by damonbarry** [comment]
IoT Edge v2 can accept incoming MQTT connections from devices, but v1 doesn't have anything like that out of the box. You'd have to build it. The BLE module sample and various docs in this repo could help guide you, but how you actually implement the MQTT server would be up to you.

**Comment by damonbarry** [comment]
I'm not familiar with that sample, but it looks like you filed issue Azure-Samples/iot-gateway-mqtt-http#2--that's the right thing to do.
