### ISSUE TITLE
[V2] ASA using Raspbian(RasPi)

### ISSUE THREAD

**Issue by matsujirushi** [Azure/iot-edge#553]
Edge v2 is running on Raspbian (RasPi).
[azureiotedge-simulated-temperature-sensor](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-simulate-device-linux#deploy-a-module) is fine.
But [ASA](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-stream-analytics#deploy-the-job) has error.

```
pi@raspberrypi:~ $ docker logs -f matsujirushi

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly '/app/ASA.Engine.dll'. An attempt was made to load a program with an incorrect format.
```

![image](https://user-images.githubusercontent.com/8079404/37809606-6a1de168-2e93-11e8-8ee4-c3686cf85e25.png)

**Comment by damonbarry** [comment]
I don't think you'll be able to get much help for the ASA module here. The [ASA on IoT Edge documentation](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-edge) says you can contact their team through [this survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR2czagZ-i_9Cg6NhAZlH9ypUMjNEM0RDVU9CVTBQWDdYTlk0UDNTTFdUTC4u), or that you can go to their [forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureStreamAnalytics).
