### ISSUE TITLE
Routes for Edge modules disappear when setting modules on Portal

### ISSUE THREAD

**Issue by Strandfelt** [Azure/iot-edge#554]
Starting today, we are experiencing issues when using the "Set Modules" wizard on the Azure portal.

When we change the routes (or just keep them as they were) and save, the routes disappear, and we can see that they are also removed from our twins, meaning that our modules have stopped sending data to the hub following the deployment of the "Set Modules" modification.

Steps to reproduce:
1. Select IoT Edge device on portal
2. Click "Set Modules"
3. Press "Next" and either define some routes or keep the ones already present
4. Press "Next" and "Submit"
5. Press "Set Modules" again and press "Next" to go to the routes configuration
6. The Json textbox is now empty and has discarded the route configurations

**Comment by damonbarry** [comment]
I've confirmed this. @iluican?

**Comment by darobs** [comment]
Hello @Strandfelt 

The UI team pushed out a fix for this.  I've confirmed the routes are not empty or malformed on a second "Set Modules..." invocation.

I'm closing this issue, please reopen or raise a new issue if you are still having trouble.

Thank you.
DAVE!!!
