### ISSUE TITLE
[V1] How to run in Alpine Docker Container?

### ISSUE THREAD

**Issue by malichishti** [Azure/iot-edge#569]
Hi,

I would like to know if V1 **dotnet core** **Managed** Gateway can be run in **Alpine docker container**? If yes is there any documentation or steps to follow?

Thank you,
Ali

**Comment by darobs** [comment]
Hello @malichishti 

The main barrier to running the v1 dotnet core gateway in Alpine is getting the dotnet core runtime installed in the container. 

An alpine base image is in preview for dotnet 2.1. https://github.com/dotnet/announcements/issues/49

Which may require some changes to the V1 project files, as mentioned in #567.

Unfortunately, we don't have any documentation or instructions for doing this.

**Comment by malichishti** [comment]
I was able to achieve this using the docker container referred above. Thank you.
