### ISSUE TITLE
[V1]Compilation Issue

### ISSUE THREAD

**Issue by lakshmisivareddy** [Azure/iot-edge#574]
Hi 
i am using 
IoT Client SDK Version = 1.1.31
OS Ubuntu -14-04 
getting below Error on Compiling 

[  2%] Building C object core/deps/CMakeFiles/parson.dir/__/__/deps/parson/parson.c.o
cc1: error: unrecognized command line option "-Wtrampolines"
make[2]: *** [core/deps/CMakeFiles/parson.dir/__/__/deps/parson/parson.c.o] Error 1
make[1]: *** [core/deps/CMakeFiles/parson.dir/all] Error 2

Regards
lakshmisivareddy.challa

**Comment by lakshmisivareddy** [comment]
i am able to fix the issue 
Thanks

**Comment by darobs** [comment]
Thank you for following up, I'm glad you got it working - I am going to close the issue, then.
