### ISSUE TITLE
The route example for azureiotedge-simulated-temperature-sensor is a little bit confusing

### ISSUE THREAD

**Issue by HenrikBach1** [Azure/iot-edge#577]
Hi,

I've build a module from the source code of the tempSensor module given in https://github.com/Azure/iot-edge/tree/master/v2/samples/azureiotedge-simulated-temperature-sensor and following the `Sample Route` example of the README.md to configure the module to output D2C messages:

```json
{
   "routes":{
      "yourModuleToSensor":"FROM /messages/modules/<YOURMODULE>/outputs/<YOUROUTPUTENDPOINT> INTO BrokeredEndpoint(\"/modules/tempSensor/inputs/control\")",
      "sensorToIoTHub":"FROM /messages/modules/tempSensor/outputs/temperatureOutput INTO $upstream"
   }
}
```

However, it turns out, when you are reading the example carefully, it should only be the the last line containing `sensorToIoTHub` that is resulting in any output from the module. If both lines are given, the egdeHub module presumable doesn't output any values from the module.

Ideally, the routes example should also state, that it may be safe to use

```json
{
  "routes": {
    "anything": "FROM /* INTO $upstream"
  }
}
```

in testing of the module output.

Thank you.

/Henrik

**Comment by dariuszparys** [comment]
Yes it should be more described what the purpose of this route is. Basically the _yourModuleToSensor_ route showcases the use of the restart behavior of the temperature module with a message send to the `control` input endpoint and _sensorToIoTHub_ is a full path route to `$upstream`, you wouldn't be normally interested in the messages of the first route in IoTHub as they just control the module on the edge device.

I'll fix this in an upcoming PR, but feel free to submit as well and mention me or @varunpuranik

**Comment by HenrikBach1** [comment]
@dariuszparys , Thank you.

Case is closed.
