### ISSUE TITLE
[V2] Any C#.net code examples for how to use reported properties for device and module twins?

### ISSUE THREAD

**Issue by HenrikBach1** [Azure/iot-edge#590]
Hi,

I've been looking around for some C#.net code examples for how to use reported properties for device and module twins, but hasn't found any working examples.

Can you help me on this?

Thank you in advance.

/Henrik

**Comment by varunpuranik** [comment]
Here is the link on the basics of device/module twins - https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins

Here are some samples on using twins (including reported properties) - https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-twin-getstarted

Note that the code to update reported properties for devices and modules should be very similar.

**Comment by mschulz531** [comment]
perhaps the updated sample module will provide that information?

https://github.com/Azure/iot-edge/commit/db4e50eb9902a0dfeffa0a4c52bc6b86d0dd2962

**Comment by dariuszparys** [comment]
The Temperature Simulator Sample uses Module Twin properties https://github.com/Azure/iot-edge/tree/master/v2/samples/azureiotedge-simulated-temperature-sensor

**Comment by HenrikBach1** [comment]
Thank you very much, everyone.

Issue is closed.
