### ISSUE TITLE
[V2] Array Object Support in ModuleTwin

### ISSUE THREAD

**Issue by matsujirushi** [Azure/iot-edge#593]
Hi,
When I set array object to module twin's desired properties, got below message:
```
Failed To Set Modules
BadRequest:{
 "Message": "ErrorCode:ArgumentInvalid;Provided json is not a valid 'tags' or 'properties' object: arrays are not supported."
```

I want to set leaf-device id's to module using module twin.
So, do you have plan to implement that feature?

**Comment by varunpuranik** [comment]
Hi Matsujirushi,

Yes, currently arrays are not supported in twin desired properties, as explained here - https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#tags-and-properties-format. 
Currently there is no plan to add support for arrays. 

Thanks,
Varun

**Comment by v-tbert** [comment]
What is the rationale for the various limitations like no arrays? This ends up being very limiting because you can't properly represent a device as a twin properly.

**Comment by darobs** [comment]
Hello @v-tbert 

You may want to provide [feedback to the IoT Hub Team](https://feedback.azure.com/forums/321918-azure-iot/suggestions/20162305-support-arrays-for-tags-in-device-twins).  

Specific use cases always help our team determine the need and priority of IoTHub features.

**Comment by ChrisGMsft** [comment]
Please submit your vote on UserVoice. It would be great if you could also leave a comment on the exact content you'd like to put into the array.

https://feedback.azure.com/forums/321918-azure-iot/suggestions/20162305-support-arrays-for-tags-in-device-twins#comments
