### ISSUE TITLE
Upload file from IoT Edge Module

### ISSUE THREAD

**Issue by shasdas** [Azure/iot-edge#603]
Can I use `UploadToBlobAsync(String, Stream)` method of `DeviceClient` to upload file from a edge module?
To validate this I created a module and trying to make use of `DeviceClient` from `Microsoft.Azure.Devices.Client` and `UploadToBlobAsync` is probably not getting executed when the module is added to the device.
Can anyone please let me know if upload feature from edge module is available at the moment?

**Comment by aribeironovaes** [comment]
HI @shasdas , 

This feature is not available yet on Edge. But it's on our backlog. Not sure about date yet. 

Thanks, 

Angelo Ribeiro.

**Comment by aribeironovaes** [comment]
Closing this issue. Since it's a feature request, can you check if this is on the list on this site: https://feedback.azure.com/forums/907045-azure-iot-edge. 
You can open a new request if you don't find or vote for this if you find. 

Thanks, 

Angelo Ribeiro.

**Comment by shasdas** [comment]
Thank you @aribeironovaes for confirming this.

**Comment by StefanSchoof** [comment]
The User Voice can be found under: https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/32576821-azure-blob-file-upload
